### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter
  id: ManifestWriter
  children:
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter.WriteManifest(Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest)
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter.WriteManifest(Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest,System.IO.Stream)
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter.WriteManifest(Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest,System.String)
  langs:
  - csharp
  name: ManifestWriter
  nameWithType: ManifestWriter
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter
  type: Class
  summary: Writes an object representation of a manifest to XML.
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public static class ManifestWriter
  inheritance:
  - System.Object
  implements: []
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-20
  - netframework-30
  - netframework-35
  - netframework-40
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter.WriteManifest(Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest)
  id: WriteManifest(Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter
  langs:
  - csharp
  name: WriteManifest(Manifest)
  nameWithType: ManifestWriter.WriteManifest(Manifest)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter.WriteManifest(Manifest)
  type: Method
  assemblies:
  - Microsoft.Build.Tasks
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: Writes the specified manifest object to XML.
  remarks: Writes the specified object representation of a manifest to XML. The name of the output file is inferred from the <xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.SourcePath%2A> property of the manifest.
  syntax:
    content: public static void WriteManifest (Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest manifest);
    parameters:
    - id: manifest
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest
      description: The manifest object.
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter.WriteManifest*
  exceptions: []
  version:
  - netframework-20
  - netframework-30
  - netframework-35
  - netframework-40
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter.WriteManifest(Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest,System.IO.Stream)
  id: WriteManifest(Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest,System.IO.Stream)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter
  langs:
  - csharp
  name: WriteManifest(Manifest,Stream)
  nameWithType: ManifestWriter.WriteManifest(Manifest,Stream)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter.WriteManifest(Manifest,Stream)
  type: Method
  assemblies:
  - Microsoft.Build.Tasks
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: Writes the specified manifest object to XML.
  remarks: Writes the specified object representation of a manifest to XML.
  syntax:
    content: public static void WriteManifest (Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest manifest, System.IO.Stream output);
    parameters:
    - id: manifest
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest
      description: The manifest object.
    - id: output
      type: System.IO.Stream
      description: Specifies an output stream.
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter.WriteManifest*
  exceptions: []
  version:
  - netframework-20
  - netframework-30
  - netframework-35
  - netframework-40
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter.WriteManifest(Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest,System.String)
  id: WriteManifest(Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest,System.String)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter
  langs:
  - csharp
  name: WriteManifest(Manifest,String)
  nameWithType: ManifestWriter.WriteManifest(Manifest,String)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter.WriteManifest(Manifest,String)
  type: Method
  assemblies:
  - Microsoft.Build.Tasks
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: Writes the specified manifest object to XML.
  remarks: Writes the specified object representation of a manifest to XML.
  syntax:
    content: public static void WriteManifest (Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest manifest, string path);
    parameters:
    - id: manifest
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest
      description: The manifest object.
    - id: path
      type: System.String
      description: The path name of the output file.
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter.WriteManifest*
  exceptions: []
  version:
  - netframework-20
  - netframework-30
  - netframework-35
  - netframework-40
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter.WriteManifest(Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter
  isExternal: false
  name: WriteManifest(Manifest)
  nameWithType: ManifestWriter.WriteManifest(Manifest)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter.WriteManifest(Manifest)
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  isExternal: false
  name: Manifest
  nameWithType: Manifest
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter.WriteManifest(Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest,System.IO.Stream)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter
  isExternal: false
  name: WriteManifest(Manifest,Stream)
  nameWithType: ManifestWriter.WriteManifest(Manifest,Stream)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter.WriteManifest(Manifest,Stream)
- uid: System.IO.Stream
  parent: System.IO
  isExternal: false
  name: Stream
  nameWithType: Stream
  fullName: System.IO.Stream
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter.WriteManifest(Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest,System.String)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter
  isExternal: false
  name: WriteManifest(Manifest,String)
  nameWithType: ManifestWriter.WriteManifest(Manifest,String)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter.WriteManifest(Manifest,String)
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter.WriteManifest*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter
  isExternal: false
  name: WriteManifest
  nameWithType: ManifestWriter.WriteManifest
