### YamlMime:ManagedReference
items:
- uid: System.Activities.XamlIntegration.ActivityWithResultValueSerializer
  id: ActivityWithResultValueSerializer
  children:
  - System.Activities.XamlIntegration.ActivityWithResultValueSerializer.#ctor
  - System.Activities.XamlIntegration.ActivityWithResultValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  - System.Activities.XamlIntegration.ActivityWithResultValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  langs:
  - csharp
  name: ActivityWithResultValueSerializer
  nameWithType: ActivityWithResultValueSerializer
  fullName: System.Activities.XamlIntegration.ActivityWithResultValueSerializer
  type: Class
  summary: Ensures that the result of an activity is properly converted to a string that can be used for serial transmission.
  syntax:
    content: 'public sealed class ActivityWithResultValueSerializer : System.Windows.Markup.ValueSerializer'
  inheritance:
  - System.Object
  - System.Windows.Markup.ValueSerializer
  implements: []
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.Windows.Markup.ValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Markup.ValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Markup.ValueSerializer.GetConvertFromException(System.Object)
  - System.Windows.Markup.ValueSerializer.GetConvertToException(System.Object,System.Type)
  - System.Windows.Markup.ValueSerializer.GetSerializerFor(System.ComponentModel.PropertyDescriptor)
  - System.Windows.Markup.ValueSerializer.GetSerializerFor(System.ComponentModel.PropertyDescriptor,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Markup.ValueSerializer.GetSerializerFor(System.Type)
  - System.Windows.Markup.ValueSerializer.GetSerializerFor(System.Type,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Markup.ValueSerializer.TypeReferences(System.Object,System.Windows.Markup.IValueSerializerContext)
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Activities.XamlIntegration\ActivityWithResultValueSerializer.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Activities.XamlIntegration/ActivityWithResultValueSerializer.xml
  version:
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.Activities.XamlIntegration.ActivityWithResultValueSerializer.#ctor
  id: '#ctor'
  parent: System.Activities.XamlIntegration.ActivityWithResultValueSerializer
  langs:
  - csharp
  name: ActivityWithResultValueSerializer()
  nameWithType: ActivityWithResultValueSerializer.ActivityWithResultValueSerializer()
  fullName: System.Activities.XamlIntegration.ActivityWithResultValueSerializer.ActivityWithResultValueSerializer()
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities.XamlIntegration
  summary: Creates a new instance of the <xref href="System.Activities.XamlIntegration.ActivityWithResultValueSerializer"></xref> class.
  syntax:
    content: public ActivityWithResultValueSerializer ();
    parameters: []
  overload: System.Activities.XamlIntegration.ActivityWithResultValueSerializer.#ctor*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Activities.XamlIntegration\ActivityWithResultValueSerializer.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Activities.XamlIntegration/ActivityWithResultValueSerializer.xml
  version:
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.Activities.XamlIntegration.ActivityWithResultValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Activities.XamlIntegration.ActivityWithResultValueSerializer
  langs:
  - csharp
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: ActivityWithResultValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Activities.XamlIntegration.ActivityWithResultValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities.XamlIntegration
  summary: Returns an indication whether an input object is an <xref href="System.Activities.XamlIntegration.IValueSerializableExpression"></xref> that can be serialized into a string.
  syntax:
    content: public override bool CanConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: The <xref href="System.Activities.XamlIntegration.IValueSerializableExpression"></xref> object that is verified for its ability to be converted to a string for serial transmission.
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: Defines a context for the serialization of <xref href="System.Activities.XamlIntegration.IValueSerializableExpression"></xref>.
    return:
      type: System.Boolean
      description: '`true` if the expression can be serialized; otherwise, `false`.'
  overload: System.Activities.XamlIntegration.ActivityWithResultValueSerializer.CanConvertToString*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Activities.XamlIntegration\ActivityWithResultValueSerializer.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Activities.XamlIntegration/ActivityWithResultValueSerializer.xml
  version:
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.Activities.XamlIntegration.ActivityWithResultValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Activities.XamlIntegration.ActivityWithResultValueSerializer
  langs:
  - csharp
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: ActivityWithResultValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Activities.XamlIntegration.ActivityWithResultValueSerializer.ConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities.XamlIntegration
  summary: Serializes the specified object into a string.
  syntax:
    content: public override string ConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: The object that is converted to a string for serial transmission.
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: Defines a context for the serialization of the object being that is converted into a string.
    return:
      type: System.String
      description: A string version of the serializable expression.
  overload: System.Activities.XamlIntegration.ActivityWithResultValueSerializer.ConvertToString*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Activities.XamlIntegration\ActivityWithResultValueSerializer.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Activities.XamlIntegration/ActivityWithResultValueSerializer.xml
  version:
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
references:
- uid: System.Windows.Markup.ValueSerializer
  isExternal: false
  name: System.Windows.Markup.ValueSerializer
- uid: System.Activities.XamlIntegration.ActivityWithResultValueSerializer.#ctor
  parent: System.Activities.XamlIntegration.ActivityWithResultValueSerializer
  isExternal: false
  name: ActivityWithResultValueSerializer()
  nameWithType: ActivityWithResultValueSerializer.ActivityWithResultValueSerializer()
  fullName: System.Activities.XamlIntegration.ActivityWithResultValueSerializer.ActivityWithResultValueSerializer()
- uid: System.Activities.XamlIntegration.ActivityWithResultValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Activities.XamlIntegration.ActivityWithResultValueSerializer
  isExternal: false
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: ActivityWithResultValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Activities.XamlIntegration.ActivityWithResultValueSerializer.CanConvertToString(Object,IValueSerializerContext)
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Windows.Markup.IValueSerializerContext
  parent: System.Windows.Markup
  isExternal: false
  name: IValueSerializerContext
  nameWithType: IValueSerializerContext
  fullName: System.Windows.Markup.IValueSerializerContext
- uid: System.Activities.XamlIntegration.ActivityWithResultValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Activities.XamlIntegration.ActivityWithResultValueSerializer
  isExternal: false
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: ActivityWithResultValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Activities.XamlIntegration.ActivityWithResultValueSerializer.ConvertToString(Object,IValueSerializerContext)
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Activities.XamlIntegration.ActivityWithResultValueSerializer.#ctor*
  parent: System.Activities.XamlIntegration.ActivityWithResultValueSerializer
  isExternal: false
  name: ActivityWithResultValueSerializer
  nameWithType: ActivityWithResultValueSerializer.ActivityWithResultValueSerializer
- uid: System.Activities.XamlIntegration.ActivityWithResultValueSerializer.CanConvertToString*
  parent: System.Activities.XamlIntegration.ActivityWithResultValueSerializer
  isExternal: false
  name: CanConvertToString
  nameWithType: ActivityWithResultValueSerializer.CanConvertToString
- uid: System.Activities.XamlIntegration.ActivityWithResultValueSerializer.ConvertToString*
  parent: System.Activities.XamlIntegration.ActivityWithResultValueSerializer
  isExternal: false
  name: ConvertToString
  nameWithType: ActivityWithResultValueSerializer.ConvertToString
