### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsProviderAttribute
  id: SettingsProviderAttribute
  children:
  - System.Configuration.SettingsProviderAttribute.#ctor(System.String)
  - System.Configuration.SettingsProviderAttribute.#ctor(System.Type)
  - System.Configuration.SettingsProviderAttribute.ProviderTypeName
  langs:
  - csharp
  name: SettingsProviderAttribute
  nameWithType: SettingsProviderAttribute
  fullName: System.Configuration.SettingsProviderAttribute
  type: Class
  summary: Specifies the settings provider used to provide storage for the current application settings class or property. This class cannot be inherited.
  remarks: "Each application settings class defines a group of application settings properties that represent information that persists between executions of the application. However, it is a settings provider—a class derived from <xref:System.Configuration.SettingsProvider>—that actually provides the storage mechanism.  \n  \n The SettingsProviderAttribute specifies the settings provider used to provide storage for application settings properties. This attribute can be applied to the entire application settings class or individual application settings properties. A SettingsProviderAttribute set at the property level will override the class-level attribute. If a settings provider is not explicitly specified, the default provider is used. For client applications, the default provider is <xref:System.Configuration.LocalFileSettingsProvider>.  \n  \n Setting providers cannot be determined at run time. Any run-time determination of storage methods must be coded into the settings provider class itself.  \n  \n> [!CAUTION]\n>  Using custom settings providers from arbitrary third parties is inherently unsafe because these providers have full read/write access to your application's configuration information. A settings provider should be thoroughly vetted before it is adopted for general use."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Property)]

      public sealed class SettingsProviderAttribute : Attribute
  inheritance:
  - System.Object
  - System.Attribute
  implements: []
  inheritedMembers:
  - System.Attribute.Equals(System.Object)
  - System.Attribute.GetCustomAttribute(System.Reflection.Assembly,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.Module,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.GetHashCode
  - System.Attribute.IsDefaultAttribute
  - System.Attribute.IsDefined(System.Reflection.Assembly,System.Type)
  - System.Attribute.IsDefined(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.IsDefined(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.Module,System.Type)
  - System.Attribute.IsDefined(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.IsDefined(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.Match(System.Object)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetIDsOfNames(System.Guid@,System.IntPtr,System.UInt32,System.UInt32,System.IntPtr)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetTypeInfo(System.UInt32,System.UInt32,System.IntPtr)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetTypeInfoCount(System.UInt32@)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#Invoke(System.UInt32,System.Guid@,System.UInt32,System.Int16,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr)
  - System.Attribute.TypeId
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  platform:
  - netframework-2.0
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
- uid: System.Configuration.SettingsProviderAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.SettingsProviderAttribute
  langs:
  - csharp
  name: SettingsProviderAttribute(String)
  nameWithType: SettingsProviderAttribute.SettingsProviderAttribute(String)
  fullName: System.Configuration.SettingsProviderAttribute.SettingsProviderAttribute(String)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: Initializes an instance of the <xref href="System.Configuration.SettingsProviderAttribute"></xref> class.
  remarks: "The type name is the name of the class, derived from <xref:System.Configuration.SettingsProvider>, that is being specified as the settings provider.  \n  \n> [!CAUTION]\n>  Using custom settings providers from arbitrary third parties is inherently unsafe because these providers have full read/write access to your application's configuration information. A settings provider should be thoroughly vetted before it is adopted for general use."
  syntax:
    content: public SettingsProviderAttribute (string providerTypeName);
    parameters:
    - id: providerTypeName
      type: System.String
      description: A <xref href="System.String"></xref> containing the name of the settings provider.
  overload: System.Configuration.SettingsProviderAttribute.#ctor*
  exceptions: []
  platform:
  - netframework-2.0
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
- uid: System.Configuration.SettingsProviderAttribute.#ctor(System.Type)
  id: '#ctor(System.Type)'
  parent: System.Configuration.SettingsProviderAttribute
  langs:
  - csharp
  name: SettingsProviderAttribute(Type)
  nameWithType: SettingsProviderAttribute.SettingsProviderAttribute(Type)
  fullName: System.Configuration.SettingsProviderAttribute.SettingsProviderAttribute(Type)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: Initializes a new instance of the <xref href="System.Configuration.SettingsProviderAttribute"></xref> class.
  syntax:
    content: public SettingsProviderAttribute (Type providerType);
    parameters:
    - id: providerType
      type: System.Type
      description: A <xref href="System.Type"></xref> containing the settings provider type.
  overload: System.Configuration.SettingsProviderAttribute.#ctor*
  exceptions: []
  platform:
  - netframework-2.0
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
- uid: System.Configuration.SettingsProviderAttribute.ProviderTypeName
  id: ProviderTypeName
  parent: System.Configuration.SettingsProviderAttribute
  langs:
  - csharp
  name: ProviderTypeName
  nameWithType: SettingsProviderAttribute.ProviderTypeName
  fullName: System.Configuration.SettingsProviderAttribute.ProviderTypeName
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: Gets the type name of the settings provider.
  remarks: The ProviderTypeName property is set in the <xref:System.Configuration.SettingsProviderAttribute.%23ctor%2A> for the class.
  syntax:
    content: public string ProviderTypeName { get; }
    return:
      type: System.String
      description: A <xref href="System.String"></xref> containing the name of the settings provider.
  overload: System.Configuration.SettingsProviderAttribute.ProviderTypeName*
  exceptions: []
  platform:
  - netframework-2.0
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.SettingsProviderAttribute.#ctor(System.String)
  parent: System.Configuration.SettingsProviderAttribute
  isExternal: false
  name: SettingsProviderAttribute(String)
  nameWithType: SettingsProviderAttribute.SettingsProviderAttribute(String)
  fullName: System.Configuration.SettingsProviderAttribute.SettingsProviderAttribute(String)
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.SettingsProviderAttribute.#ctor(System.Type)
  parent: System.Configuration.SettingsProviderAttribute
  isExternal: false
  name: SettingsProviderAttribute(Type)
  nameWithType: SettingsProviderAttribute.SettingsProviderAttribute(Type)
  fullName: System.Configuration.SettingsProviderAttribute.SettingsProviderAttribute(Type)
- uid: System.Type
  parent: System
  isExternal: false
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.SettingsProviderAttribute.ProviderTypeName
  parent: System.Configuration.SettingsProviderAttribute
  isExternal: false
  name: ProviderTypeName
  nameWithType: SettingsProviderAttribute.ProviderTypeName
  fullName: System.Configuration.SettingsProviderAttribute.ProviderTypeName
- uid: System.Configuration.SettingsProviderAttribute.#ctor*
  parent: System.Configuration.SettingsProviderAttribute
  isExternal: false
  name: SettingsProviderAttribute
  nameWithType: SettingsProviderAttribute.SettingsProviderAttribute
- uid: System.Configuration.SettingsProviderAttribute.ProviderTypeName*
  parent: System.Configuration.SettingsProviderAttribute
  isExternal: false
  name: ProviderTypeName
  nameWithType: SettingsProviderAttribute.ProviderTypeName
