### YamlMime:ManagedReference
items:
- uid: System.Activities.Expressions.EnvironmentLocationReference`1
  id: EnvironmentLocationReference`1
  children:
  - System.Activities.Expressions.EnvironmentLocationReference`1.CacheMetadata(System.Activities.CodeActivityMetadata)
  - System.Activities.Expressions.EnvironmentLocationReference`1.Execute(System.Activities.CodeActivityContext)
  - System.Activities.Expressions.EnvironmentLocationReference`1.LocationReference
  langs:
  - csharp
  name: EnvironmentLocationReference<T>
  nameWithType: EnvironmentLocationReference<T>
  fullName: System.Activities.Expressions.EnvironmentLocationReference<T>
  type: Class
  summary: Represents an environment location reference.
  syntax:
    content: 'public class EnvironmentLocationReference<T> : System.Activities.CodeActivity<System.Activities.Location<T>>'
    typeParameters:
    - id: T
      description: The data type of EnvironmentLocationReference(T).
  inheritance:
  - System.Object
  - System.Activities.Activity
  - System.Activities.ActivityWithResult
  - System.Activities.Activity`1
  - System.Activities.CodeActivity`1
  implements: []
  inheritedMembers:
  - System.Activities.Activity.CacheId
  - System.Activities.Activity.Constraints
  - System.Activities.Activity.DisplayName
  - System.Activities.Activity.Id
  - System.Activities.Activity.ShouldSerializeDisplayName
  - System.Activities.Activity.ToString
  - System.Activities.Activity`1.FromValue(`0)
  - System.Activities.Activity`1.FromVariable(System.Activities.Variable)
  - System.Activities.Activity`1.FromVariable(System.Activities.Variable{`0})
  - System.Activities.Activity`1.op_Implicit(`0)
  - System.Activities.Activity`1.op_Implicit(System.Activities.Variable)
  - System.Activities.Activity`1.op_Implicit(System.Activities.Variable{`0})
  - System.Activities.Activity`1.Result
  - System.Activities.ActivityWithResult.ResultType
  - System.Activities.CodeActivity`1.CacheMetadata(System.Activities.ActivityMetadata)
  - System.Activities.CodeActivity`1.Implementation
  - System.Activities.CodeActivity`1.ImplementationVersion
  - System.Activities.CodeActivity`1.OnCreateDynamicUpdateMap(System.Activities.DynamicUpdate.UpdateMapMetadata,System.Activities.Activity)
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Activities.Expressions\EnvironmentLocationReference`1.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Activities.Expressions/EnvironmentLocationReference`1.xml
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.Activities.Expressions.EnvironmentLocationReference`1.CacheMetadata(System.Activities.CodeActivityMetadata)
  id: CacheMetadata(System.Activities.CodeActivityMetadata)
  parent: System.Activities.Expressions.EnvironmentLocationReference`1
  langs:
  - csharp
  name: CacheMetadata(CodeActivityMetadata)
  nameWithType: EnvironmentLocationReference<T>.CacheMetadata(CodeActivityMetadata)
  fullName: System.Activities.Expressions.EnvironmentLocationReference<T>.CacheMetadata(CodeActivityMetadata)
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities.Expressions
  summary: Creates and validates a description of the activity’s arguments, variables, child activities, and activity delegates.
  syntax:
    content: protected override void CacheMetadata (System.Activities.CodeActivityMetadata metadata);
    parameters:
    - id: metadata
      type: System.Activities.CodeActivityMetadata
      description: The activity’s metadata that encapsulates the activity’s arguments, variables, child activities, and activity delegates.
  overload: System.Activities.Expressions.EnvironmentLocationReference`1.CacheMetadata*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Activities.Expressions\EnvironmentLocationReference`1.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Activities.Expressions/EnvironmentLocationReference`1.xml
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.Activities.Expressions.EnvironmentLocationReference`1.Execute(System.Activities.CodeActivityContext)
  id: Execute(System.Activities.CodeActivityContext)
  parent: System.Activities.Expressions.EnvironmentLocationReference`1
  langs:
  - csharp
  name: Execute(CodeActivityContext)
  nameWithType: EnvironmentLocationReference<T>.Execute(CodeActivityContext)
  fullName: System.Activities.Expressions.EnvironmentLocationReference<T>.Execute(CodeActivityContext)
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities.Expressions
  summary: Performs the execution of the activity.
  syntax:
    content: protected override sealed System.Activities.Location<T> Execute (System.Activities.CodeActivityContext context);
    parameters:
    - id: context
      type: System.Activities.CodeActivityContext
      description: The execution context under which the activity executes.
    return:
      type: System.Activities.Location`1
      description: The execution of the activity.
  overload: System.Activities.Expressions.EnvironmentLocationReference`1.Execute*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Activities.Expressions\EnvironmentLocationReference`1.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Activities.Expressions/EnvironmentLocationReference`1.xml
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.Activities.Expressions.EnvironmentLocationReference`1.LocationReference
  id: LocationReference
  parent: System.Activities.Expressions.EnvironmentLocationReference`1
  langs:
  - csharp
  name: LocationReference
  nameWithType: EnvironmentLocationReference<T>.LocationReference
  fullName: System.Activities.Expressions.EnvironmentLocationReference<T>.LocationReference
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.Expressions
  summary: Gets the location reference value.
  syntax:
    content: public virtual System.Activities.LocationReference LocationReference { get; }
    return:
      type: System.Activities.LocationReference
      description: The location reference value.
  overload: System.Activities.Expressions.EnvironmentLocationReference`1.LocationReference*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Activities.Expressions\EnvironmentLocationReference`1.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Activities.Expressions/EnvironmentLocationReference`1.xml
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
references:
- uid: System.Activities.CodeActivity`1
  isExternal: false
  name: System.Activities.CodeActivity<System.Activities.Location<T>>
- uid: System.Activities.Expressions.EnvironmentLocationReference`1.CacheMetadata(System.Activities.CodeActivityMetadata)
  parent: System.Activities.Expressions.EnvironmentLocationReference`1
  isExternal: false
  name: CacheMetadata(CodeActivityMetadata)
  nameWithType: EnvironmentLocationReference<T>.CacheMetadata(CodeActivityMetadata)
  fullName: System.Activities.Expressions.EnvironmentLocationReference<T>.CacheMetadata(CodeActivityMetadata)
- uid: System.Activities.CodeActivityMetadata
  parent: System.Activities
  isExternal: false
  name: CodeActivityMetadata
  nameWithType: CodeActivityMetadata
  fullName: System.Activities.CodeActivityMetadata
- uid: System.Activities.Expressions.EnvironmentLocationReference`1.Execute(System.Activities.CodeActivityContext)
  parent: System.Activities.Expressions.EnvironmentLocationReference`1
  isExternal: false
  name: Execute(CodeActivityContext)
  nameWithType: EnvironmentLocationReference<T>.Execute(CodeActivityContext)
  fullName: System.Activities.Expressions.EnvironmentLocationReference<T>.Execute(CodeActivityContext)
- uid: System.Activities.Location`1
  parent: System.Activities
  isExternal: false
  name: Location<T>
  nameWithType: Location<T>
  fullName: System.Activities.Location<T>
- uid: System.Activities.CodeActivityContext
  parent: System.Activities
  isExternal: false
  name: CodeActivityContext
  nameWithType: CodeActivityContext
  fullName: System.Activities.CodeActivityContext
- uid: System.Activities.Expressions.EnvironmentLocationReference`1.LocationReference
  parent: System.Activities.Expressions.EnvironmentLocationReference`1
  isExternal: false
  name: LocationReference
  nameWithType: EnvironmentLocationReference<T>.LocationReference
  fullName: System.Activities.Expressions.EnvironmentLocationReference<T>.LocationReference
- uid: System.Activities.LocationReference
  parent: System.Activities
  isExternal: false
  name: LocationReference
  nameWithType: LocationReference
  fullName: System.Activities.LocationReference
- uid: System.Activities.Expressions.EnvironmentLocationReference`1.CacheMetadata*
  parent: System.Activities.Expressions.EnvironmentLocationReference`1
  isExternal: false
  name: CacheMetadata
  nameWithType: EnvironmentLocationReference<T>.CacheMetadata
- uid: System.Activities.Expressions.EnvironmentLocationReference`1.Execute*
  parent: System.Activities.Expressions.EnvironmentLocationReference`1
  isExternal: false
  name: Execute
  nameWithType: EnvironmentLocationReference<T>.Execute
- uid: System.Activities.Expressions.EnvironmentLocationReference`1.LocationReference*
  parent: System.Activities.Expressions.EnvironmentLocationReference`1
  isExternal: false
  name: LocationReference
  nameWithType: EnvironmentLocationReference<T>.LocationReference
