### YamlMime:ManagedReference
items:
- uid: System.Diagnostics.Tracing.EventSourceSettings
  id: EventSourceSettings
  children:
  - System.Diagnostics.Tracing.EventSourceSettings.Default
  - System.Diagnostics.Tracing.EventSourceSettings.EtwManifestEventFormat
  - System.Diagnostics.Tracing.EventSourceSettings.EtwSelfDescribingEventFormat
  - System.Diagnostics.Tracing.EventSourceSettings.ThrowOnEventWriteErrors
  langs:
  - csharp
  name: EventSourceSettings
  nameWithType: EventSourceSettings
  fullName: System.Diagnostics.Tracing.EventSourceSettings
  type: Enum
  summary: Specifies configuration options for an event source.
  remarks: Only EtwManifestEventFormat or EtwSelfDescribingEventFormat should be specified, but not both.
  syntax:
    content: >-
      [System.Flags]

      public enum EventSourceSettings
  inheritance:
  - System.Object
  - System.ValueType
  - System.Enum
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Diagnostics.Tracing\EventSourceSettings.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Diagnostics.Tracing/EventSourceSettings.xml
  version:
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.Diagnostics.Tracing.EventSourceSettings.Default
  id: Default
  parent: System.Diagnostics.Tracing.EventSourceSettings
  langs:
  - csharp
  name: Default
  nameWithType: EventSourceSettings.Default
  fullName: System.Diagnostics.Tracing.EventSourceSettings.Default
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Diagnostics.Tracing
  summary: None of the special configuration options are enabled.
  syntax:
    content: Default
    return:
      type: System.Diagnostics.Tracing.EventSourceSettings
      description: To be added.
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Diagnostics.Tracing\EventSourceSettings.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Diagnostics.Tracing/EventSourceSettings.xml
  version:
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.Diagnostics.Tracing.EventSourceSettings.EtwManifestEventFormat
  id: EtwManifestEventFormat
  parent: System.Diagnostics.Tracing.EventSourceSettings
  langs:
  - csharp
  name: EtwManifestEventFormat
  nameWithType: EventSourceSettings.EtwManifestEventFormat
  fullName: System.Diagnostics.Tracing.EventSourceSettings.EtwManifestEventFormat
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Diagnostics.Tracing
  summary: The ETW listener should use a manifest-based format when raising events. Setting this option is a directive to the ETW listener should use manifest-based format when raising events. This is the default option when defining a type derived from <xref href="System.Diagnostics.Tracing.EventSource"></xref> using one of the protected <xref href="System.Diagnostics.Tracing.EventSource"></xref> constructors.
  syntax:
    content: EtwManifestEventFormat
    return:
      type: System.Diagnostics.Tracing.EventSourceSettings
      description: To be added.
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Diagnostics.Tracing\EventSourceSettings.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Diagnostics.Tracing/EventSourceSettings.xml
  version:
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.Diagnostics.Tracing.EventSourceSettings.EtwSelfDescribingEventFormat
  id: EtwSelfDescribingEventFormat
  parent: System.Diagnostics.Tracing.EventSourceSettings
  langs:
  - csharp
  name: EtwSelfDescribingEventFormat
  nameWithType: EventSourceSettings.EtwSelfDescribingEventFormat
  fullName: System.Diagnostics.Tracing.EventSourceSettings.EtwSelfDescribingEventFormat
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Diagnostics.Tracing
  summary: The ETW listener should use self-describing event format. This is the default option when creating a new instance of the <xref href="System.Diagnostics.Tracing.EventSource"></xref> using one of the public <xref href="System.Diagnostics.Tracing.EventSource"></xref> constructors.
  syntax:
    content: EtwSelfDescribingEventFormat
    return:
      type: System.Diagnostics.Tracing.EventSourceSettings
      description: To be added.
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Diagnostics.Tracing\EventSourceSettings.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Diagnostics.Tracing/EventSourceSettings.xml
  version:
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.Diagnostics.Tracing.EventSourceSettings.ThrowOnEventWriteErrors
  id: ThrowOnEventWriteErrors
  parent: System.Diagnostics.Tracing.EventSourceSettings
  langs:
  - csharp
  name: ThrowOnEventWriteErrors
  nameWithType: EventSourceSettings.ThrowOnEventWriteErrors
  fullName: System.Diagnostics.Tracing.EventSourceSettings.ThrowOnEventWriteErrors
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Diagnostics.Tracing
  summary: The event source throws an exception when an error occurs.
  syntax:
    content: ThrowOnEventWriteErrors
    return:
      type: System.Diagnostics.Tracing.EventSourceSettings
      description: To be added.
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Diagnostics.Tracing\EventSourceSettings.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Diagnostics.Tracing/EventSourceSettings.xml
  version:
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Diagnostics.Tracing.EventSourceSettings.Default
  parent: System.Diagnostics.Tracing.EventSourceSettings
  isExternal: false
  name: Default
  nameWithType: EventSourceSettings.Default
  fullName: System.Diagnostics.Tracing.EventSourceSettings.Default
- uid: System.Diagnostics.Tracing.EventSourceSettings
  parent: System.Diagnostics.Tracing
  isExternal: false
  name: EventSourceSettings
  nameWithType: EventSourceSettings
  fullName: System.Diagnostics.Tracing.EventSourceSettings
- uid: System.Diagnostics.Tracing.EventSourceSettings.EtwManifestEventFormat
  parent: System.Diagnostics.Tracing.EventSourceSettings
  isExternal: false
  name: EtwManifestEventFormat
  nameWithType: EventSourceSettings.EtwManifestEventFormat
  fullName: System.Diagnostics.Tracing.EventSourceSettings.EtwManifestEventFormat
- uid: System.Diagnostics.Tracing.EventSourceSettings.EtwSelfDescribingEventFormat
  parent: System.Diagnostics.Tracing.EventSourceSettings
  isExternal: false
  name: EtwSelfDescribingEventFormat
  nameWithType: EventSourceSettings.EtwSelfDescribingEventFormat
  fullName: System.Diagnostics.Tracing.EventSourceSettings.EtwSelfDescribingEventFormat
- uid: System.Diagnostics.Tracing.EventSourceSettings.ThrowOnEventWriteErrors
  parent: System.Diagnostics.Tracing.EventSourceSettings
  isExternal: false
  name: ThrowOnEventWriteErrors
  nameWithType: EventSourceSettings.ThrowOnEventWriteErrors
  fullName: System.Diagnostics.Tracing.EventSourceSettings.ThrowOnEventWriteErrors
