### YamlMime:ManagedReference
items:
- uid: System.Net.Mime.MediaTypeNames.Application
  id: MediaTypeNames.Application
  children:
  - System.Net.Mime.MediaTypeNames.Application.Octet
  - System.Net.Mime.MediaTypeNames.Application.Pdf
  - System.Net.Mime.MediaTypeNames.Application.Rtf
  - System.Net.Mime.MediaTypeNames.Application.Soap
  - System.Net.Mime.MediaTypeNames.Application.Zip
  langs:
  - csharp
  name: MediaTypeNames+Application
  nameWithType: MediaTypeNames+Application
  fullName: System.Net.Mime.MediaTypeNames+Application
  type: Class
  summary: Specifies the kind of application data in an e-mail message attachment.
  remarks: The MediaTypeNames.Application media type designates that the attachment data should be processed by an application, such as a Postscript processor, a spreadsheet, or a word processor. The data is usually something other than simple text, such as an image, or an audio or video file.
  syntax:
    content: public static class MediaTypeNames.Application
  inheritance:
  - System.Object
  implements: []
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Net.Mime\MediaTypeNames+Application.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Net.Mime/MediaTypeNames+Application.xml
  version:
  - netframework-3.0
  - netframework-3.5-client
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.Net.Mime.MediaTypeNames.Application.Octet
  id: Octet
  parent: System.Net.Mime.MediaTypeNames.Application
  langs:
  - csharp
  name: Octet
  nameWithType: MediaTypeNames+Application.Octet
  fullName: System.Net.Mime.MediaTypeNames+Application.Octet
  type: Field
  assemblies:
  - System
  namespace: System.Net.Mime
  summary: Specifies that the <xref href="System.Net.Mime.MediaTypeNames.Application"></xref> data is not interpreted.
  remarks: The Octet member designates that the attachment contains generic binary data.
  syntax:
    content: public const string Octet;
    return:
      type: System.String
      description: To be added.
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Net.Mime\MediaTypeNames+Application.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Net.Mime/MediaTypeNames+Application.xml
  version:
  - netframework-3.0
  - netframework-3.5-client
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.Net.Mime.MediaTypeNames.Application.Pdf
  id: Pdf
  parent: System.Net.Mime.MediaTypeNames.Application
  langs:
  - csharp
  name: Pdf
  nameWithType: MediaTypeNames+Application.Pdf
  fullName: System.Net.Mime.MediaTypeNames+Application.Pdf
  type: Field
  assemblies:
  - System
  namespace: System.Net.Mime
  summary: Specifies that the <xref href="System.Net.Mime.MediaTypeNames.Application"></xref> data is in Portable Document Format (PDF).
  syntax:
    content: public const string Pdf;
    return:
      type: System.String
      description: To be added.
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Net.Mime\MediaTypeNames+Application.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Net.Mime/MediaTypeNames+Application.xml
  version:
  - netframework-3.0
  - netframework-3.5-client
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.Net.Mime.MediaTypeNames.Application.Rtf
  id: Rtf
  parent: System.Net.Mime.MediaTypeNames.Application
  langs:
  - csharp
  name: Rtf
  nameWithType: MediaTypeNames+Application.Rtf
  fullName: System.Net.Mime.MediaTypeNames+Application.Rtf
  type: Field
  assemblies:
  - System
  namespace: System.Net.Mime
  summary: Specifies that the <xref href="System.Net.Mime.MediaTypeNames.Application"></xref> data is in Rich Text Format (RTF).
  syntax:
    content: public const string Rtf;
    return:
      type: System.String
      description: To be added.
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Net.Mime\MediaTypeNames+Application.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Net.Mime/MediaTypeNames+Application.xml
  version:
  - netframework-3.0
  - netframework-3.5-client
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.Net.Mime.MediaTypeNames.Application.Soap
  id: Soap
  parent: System.Net.Mime.MediaTypeNames.Application
  langs:
  - csharp
  name: Soap
  nameWithType: MediaTypeNames+Application.Soap
  fullName: System.Net.Mime.MediaTypeNames+Application.Soap
  type: Field
  assemblies:
  - System
  namespace: System.Net.Mime
  summary: Specifies that the <xref href="System.Net.Mime.MediaTypeNames.Application"></xref> data is a SOAP document.
  syntax:
    content: public const string Soap;
    return:
      type: System.String
      description: To be added.
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Net.Mime\MediaTypeNames+Application.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Net.Mime/MediaTypeNames+Application.xml
  version:
  - netframework-3.0
  - netframework-3.5-client
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.Net.Mime.MediaTypeNames.Application.Zip
  id: Zip
  parent: System.Net.Mime.MediaTypeNames.Application
  langs:
  - csharp
  name: Zip
  nameWithType: MediaTypeNames+Application.Zip
  fullName: System.Net.Mime.MediaTypeNames+Application.Zip
  type: Field
  assemblies:
  - System
  namespace: System.Net.Mime
  summary: Specifies that the <xref href="System.Net.Mime.MediaTypeNames.Application"></xref> data is compressed.
  syntax:
    content: public const string Zip;
    return:
      type: System.String
      description: To be added.
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Net.Mime\MediaTypeNames+Application.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Net.Mime/MediaTypeNames+Application.xml
  version:
  - netframework-3.0
  - netframework-3.5-client
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Net.Mime.MediaTypeNames.Application.Octet
  parent: System.Net.Mime.MediaTypeNames.Application
  isExternal: false
  name: Octet
  nameWithType: MediaTypeNames+Application.Octet
  fullName: System.Net.Mime.MediaTypeNames+Application.Octet
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Net.Mime.MediaTypeNames.Application.Pdf
  parent: System.Net.Mime.MediaTypeNames.Application
  isExternal: false
  name: Pdf
  nameWithType: MediaTypeNames+Application.Pdf
  fullName: System.Net.Mime.MediaTypeNames+Application.Pdf
- uid: System.Net.Mime.MediaTypeNames.Application.Rtf
  parent: System.Net.Mime.MediaTypeNames.Application
  isExternal: false
  name: Rtf
  nameWithType: MediaTypeNames+Application.Rtf
  fullName: System.Net.Mime.MediaTypeNames+Application.Rtf
- uid: System.Net.Mime.MediaTypeNames.Application.Soap
  parent: System.Net.Mime.MediaTypeNames.Application
  isExternal: false
  name: Soap
  nameWithType: MediaTypeNames+Application.Soap
  fullName: System.Net.Mime.MediaTypeNames+Application.Soap
- uid: System.Net.Mime.MediaTypeNames.Application.Zip
  parent: System.Net.Mime.MediaTypeNames.Application
  isExternal: false
  name: Zip
  nameWithType: MediaTypeNames+Application.Zip
  fullName: System.Net.Mime.MediaTypeNames+Application.Zip
