### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsPropertyWrongTypeException
  id: SettingsPropertyWrongTypeException
  children:
  - System.Configuration.SettingsPropertyWrongTypeException.#ctor
  - System.Configuration.SettingsPropertyWrongTypeException.#ctor(System.String)
  - System.Configuration.SettingsPropertyWrongTypeException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Configuration.SettingsPropertyWrongTypeException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: SettingsPropertyWrongTypeException
  nameWithType: SettingsPropertyWrongTypeException
  fullName: System.Configuration.SettingsPropertyWrongTypeException
  type: Class
  summary: Provides an exception that is thrown when an invalid type is used with a <xref href="System.Configuration.SettingsProperty"></xref> object.
  syntax:
    content: 'public class SettingsPropertyWrongTypeException : Exception'
  inheritance:
  - System.Object
  - System.Exception
  implements: []
  inheritedMembers:
  - System.Exception.Data
  - System.Exception.GetBaseException
  - System.Exception.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Exception.GetType
  - System.Exception.HelpLink
  - System.Exception.HResult
  - System.Exception.InnerException
  - System.Exception.Message
  - System.Exception.SerializeObjectState
  - System.Exception.Source
  - System.Exception.StackTrace
  - System.Exception.TargetSite
  - System.Exception.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  platform:
  - netframework-2.0
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
- uid: System.Configuration.SettingsPropertyWrongTypeException.#ctor
  id: '#ctor'
  parent: System.Configuration.SettingsPropertyWrongTypeException
  langs:
  - csharp
  name: SettingsPropertyWrongTypeException()
  nameWithType: SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException()
  fullName: System.Configuration.SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: Initializes a new instance of the <xref href="System.Configuration.SettingsPropertyWrongTypeException"></xref> class.
  syntax:
    content: public SettingsPropertyWrongTypeException ();
    parameters: []
  overload: System.Configuration.SettingsPropertyWrongTypeException.#ctor*
  exceptions: []
  platform:
  - netframework-2.0
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
- uid: System.Configuration.SettingsPropertyWrongTypeException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.SettingsPropertyWrongTypeException
  langs:
  - csharp
  name: SettingsPropertyWrongTypeException(String)
  nameWithType: SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException(String)
  fullName: System.Configuration.SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException(String)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: Initializes a new instance of the <xref href="System.Configuration.SettingsPropertyWrongTypeException"></xref> class based on the supplied parameter.
  syntax:
    content: public SettingsPropertyWrongTypeException (string message);
    parameters:
    - id: message
      type: System.String
      description: A string containing an exception message.
  overload: System.Configuration.SettingsPropertyWrongTypeException.#ctor*
  exceptions: []
  platform:
  - netframework-2.0
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
- uid: System.Configuration.SettingsPropertyWrongTypeException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Configuration.SettingsPropertyWrongTypeException
  langs:
  - csharp
  name: SettingsPropertyWrongTypeException(SerializationInfo,StreamingContext)
  nameWithType: SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException(SerializationInfo,StreamingContext)
  fullName: System.Configuration.SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: Initializes a new instance of the <xref href="System.Configuration.SettingsPropertyWrongTypeException"></xref> class based on the supplied parameters.
  syntax:
    content: protected SettingsPropertyWrongTypeException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: The <xref href="System.Runtime.Serialization.SerializationInfo"></xref> that holds the serialized object data about the exception being thrown.
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: The <xref href="System.Runtime.Serialization.StreamingContext"></xref> that contains contextual information about the source or destination of the serialized stream.
  overload: System.Configuration.SettingsPropertyWrongTypeException.#ctor*
  exceptions: []
  platform:
  - netframework-2.0
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
- uid: System.Configuration.SettingsPropertyWrongTypeException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Configuration.SettingsPropertyWrongTypeException
  langs:
  - csharp
  name: SettingsPropertyWrongTypeException(String,Exception)
  nameWithType: SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException(String,Exception)
  fullName: System.Configuration.SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException(String,Exception)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: Initializes a new instance of the <xref href="System.Configuration.SettingsPropertyWrongTypeException"></xref> class based on the supplied parameters.
  syntax:
    content: public SettingsPropertyWrongTypeException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: A string containing an exception message.
    - id: innerException
      type: System.Exception
      description: The exception that is the cause of the current exception.
  overload: System.Configuration.SettingsPropertyWrongTypeException.#ctor*
  exceptions: []
  platform:
  - netframework-2.0
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
references:
- uid: System.Exception
  isExternal: false
  name: System.Exception
- uid: System.Configuration.SettingsPropertyWrongTypeException.#ctor
  parent: System.Configuration.SettingsPropertyWrongTypeException
  isExternal: false
  name: SettingsPropertyWrongTypeException()
  nameWithType: SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException()
  fullName: System.Configuration.SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException()
- uid: System.Configuration.SettingsPropertyWrongTypeException.#ctor(System.String)
  parent: System.Configuration.SettingsPropertyWrongTypeException
  isExternal: false
  name: SettingsPropertyWrongTypeException(String)
  nameWithType: SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException(String)
  fullName: System.Configuration.SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException(String)
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.SettingsPropertyWrongTypeException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Configuration.SettingsPropertyWrongTypeException
  isExternal: false
  name: SettingsPropertyWrongTypeException(SerializationInfo,StreamingContext)
  nameWithType: SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException(SerializationInfo,StreamingContext)
  fullName: System.Configuration.SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: false
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Configuration.SettingsPropertyWrongTypeException.#ctor(System.String,System.Exception)
  parent: System.Configuration.SettingsPropertyWrongTypeException
  isExternal: false
  name: SettingsPropertyWrongTypeException(String,Exception)
  nameWithType: SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException(String,Exception)
  fullName: System.Configuration.SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException(String,Exception)
- uid: System.Configuration.SettingsPropertyWrongTypeException.#ctor*
  parent: System.Configuration.SettingsPropertyWrongTypeException
  isExternal: false
  name: SettingsPropertyWrongTypeException
  nameWithType: SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException
