### YamlMime:ManagedReference
items:
- uid: System.Windows.Media.Converters.TransformValueSerializer
  id: TransformValueSerializer
  children:
  - System.Windows.Media.Converters.TransformValueSerializer.#ctor
  - System.Windows.Media.Converters.TransformValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Media.Converters.TransformValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Media.Converters.TransformValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Media.Converters.TransformValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  langs:
  - csharp
  name: TransformValueSerializer
  nameWithType: TransformValueSerializer
  fullName: System.Windows.Media.Converters.TransformValueSerializer
  type: Class
  summary: Converts instances of <xref href="System.String"></xref> to and from instances of <xref href="System.Windows.Media.Transform"></xref>.
  remarks: This class is typically only utilized by the <xref:System.Windows.Markup.Primitives.MarkupWriter> for serialization purposes.
  example:
  - "<xref:System.Windows.Markup.Primitives.MarkupWriter>  \n  \n <xref:System.Windows.Media.Transform>"
  syntax:
    content: 'public class TransformValueSerializer : System.Windows.Markup.ValueSerializer'
  inheritance:
  - System.Windows.Markup.ValueSerializer
  implements: []
  inheritedMembers: []
  version:
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
- uid: System.Windows.Media.Converters.TransformValueSerializer.#ctor
  id: '#ctor'
  parent: System.Windows.Media.Converters.TransformValueSerializer
  langs:
  - csharp
  name: TransformValueSerializer()
  nameWithType: TransformValueSerializer.TransformValueSerializer()
  fullName: System.Windows.Media.Converters.TransformValueSerializer.TransformValueSerializer()
  type: Constructor
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Converters
  summary: Initializes a new instance of the <xref href="System.Windows.Media.Converters.TransformValueSerializer"></xref> class.
  syntax:
    content: public TransformValueSerializer ();
    parameters: []
  overload: System.Windows.Media.Converters.TransformValueSerializer.#ctor*
  exceptions: []
  version:
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
- uid: System.Windows.Media.Converters.TransformValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.TransformValueSerializer
  langs:
  - csharp
  name: CanConvertFromString(String,IValueSerializerContext)
  nameWithType: TransformValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.TransformValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Converters
  summary: Determines if conversion from a given <xref href="System.String"></xref> to an instance of <xref href="System.Windows.Media.Transform"></xref> is possible.
  remarks: This method always returns `true`.
  syntax:
    content: public override bool CanConvertFromString (string value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.String
      description: String to evaluate for conversion.
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: Context information used for conversion.
    return:
      type: System.Boolean
      description: '`true` if the value can be converted; otherwise, `false`.'
  overload: System.Windows.Media.Converters.TransformValueSerializer.CanConvertFromString*
  exceptions: []
  version:
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
- uid: System.Windows.Media.Converters.TransformValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.TransformValueSerializer
  langs:
  - csharp
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: TransformValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.TransformValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Converters
  summary: Determines if an instance of <xref href="System.Windows.Media.Transform"></xref> can be converted to a <xref href="System.String"></xref>.
  syntax:
    content: public override bool CanConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: Instance of <xref href="System.Windows.Media.Transform"></xref> to evaluate for conversion.
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: Context information used for conversion.
    return:
      type: System.Boolean
      description: '`true` if <code>value</code> can be converted into a <xref href="System.String"></xref>; otherwise, `false`.'
  overload: System.Windows.Media.Converters.TransformValueSerializer.CanConvertToString*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: Occurs when <code>value</code> is not a <xref href="System.Windows.Media.Transform"></xref>.
  version:
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
- uid: System.Windows.Media.Converters.TransformValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  id: ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.TransformValueSerializer
  langs:
  - csharp
  name: ConvertFromString(String,IValueSerializerContext)
  nameWithType: TransformValueSerializer.ConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.TransformValueSerializer.ConvertFromString(String,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Converters
  summary: Converts a <xref href="System.String"></xref> into a <xref href="System.Windows.Media.Transform"></xref>.
  syntax:
    content: public override object ConvertFromString (string value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.String
      description: <xref href="System.String"></xref> value to convert into a <xref href="System.Windows.Media.Transform"></xref>.
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: Context information used for conversion.
    return:
      type: System.Object
      description: A new instance of <xref href="System.Windows.Media.Transform"></xref> based on the supplied <code>value</code>.
  overload: System.Windows.Media.Converters.TransformValueSerializer.ConvertFromString*
  exceptions: []
  version:
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
- uid: System.Windows.Media.Converters.TransformValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.TransformValueSerializer
  langs:
  - csharp
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: TransformValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.TransformValueSerializer.ConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Converters
  summary: Converts an instance of <xref href="System.Windows.Media.Transform"></xref> to a <xref href="System.String"></xref>.
  syntax:
    content: public override string ConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: Instance of <xref href="System.Windows.Media.Transform"></xref> to evaluate for conversion.
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: Context information used for conversion.
    return:
      type: System.String
      description: A <xref href="System.String"></xref> representation of the supplied <xref href="System.Windows.Media.Transform"></xref> object.
  overload: System.Windows.Media.Converters.TransformValueSerializer.ConvertToString*
  exceptions: []
  version:
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
references:
- uid: System.Windows.Markup.ValueSerializer
  isExternal: false
  name: System.Windows.Markup.ValueSerializer
- uid: System.ArgumentException
  parent: System
  isExternal: false
  name: ArgumentException
  nameWithType: ArgumentException
  fullName: System.ArgumentException
- uid: System.Windows.Media.Converters.TransformValueSerializer.#ctor
  parent: System.Windows.Media.Converters.TransformValueSerializer
  isExternal: false
  name: TransformValueSerializer()
  nameWithType: TransformValueSerializer.TransformValueSerializer()
  fullName: System.Windows.Media.Converters.TransformValueSerializer.TransformValueSerializer()
- uid: System.Windows.Media.Converters.TransformValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.TransformValueSerializer
  isExternal: false
  name: CanConvertFromString(String,IValueSerializerContext)
  nameWithType: TransformValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.TransformValueSerializer.CanConvertFromString(String,IValueSerializerContext)
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Windows.Markup.IValueSerializerContext
  parent: System.Windows.Markup
  isExternal: true
  name: IValueSerializerContext
  nameWithType: IValueSerializerContext
  fullName: System.Windows.Markup.IValueSerializerContext
- uid: System.Windows.Media.Converters.TransformValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.TransformValueSerializer
  isExternal: false
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: TransformValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.TransformValueSerializer.CanConvertToString(Object,IValueSerializerContext)
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Windows.Media.Converters.TransformValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.TransformValueSerializer
  isExternal: false
  name: ConvertFromString(String,IValueSerializerContext)
  nameWithType: TransformValueSerializer.ConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.TransformValueSerializer.ConvertFromString(String,IValueSerializerContext)
- uid: System.Windows.Media.Converters.TransformValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.TransformValueSerializer
  isExternal: false
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: TransformValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.TransformValueSerializer.ConvertToString(Object,IValueSerializerContext)
- uid: System.Windows.Media.Converters.TransformValueSerializer.#ctor*
  parent: System.Windows.Media.Converters.TransformValueSerializer
  isExternal: false
  name: TransformValueSerializer
  nameWithType: TransformValueSerializer.TransformValueSerializer
- uid: System.Windows.Media.Converters.TransformValueSerializer.CanConvertFromString*
  parent: System.Windows.Media.Converters.TransformValueSerializer
  isExternal: false
  name: CanConvertFromString
  nameWithType: TransformValueSerializer.CanConvertFromString
- uid: System.Windows.Media.Converters.TransformValueSerializer.CanConvertToString*
  parent: System.Windows.Media.Converters.TransformValueSerializer
  isExternal: false
  name: CanConvertToString
  nameWithType: TransformValueSerializer.CanConvertToString
- uid: System.Windows.Media.Converters.TransformValueSerializer.ConvertFromString*
  parent: System.Windows.Media.Converters.TransformValueSerializer
  isExternal: false
  name: ConvertFromString
  nameWithType: TransformValueSerializer.ConvertFromString
- uid: System.Windows.Media.Converters.TransformValueSerializer.ConvertToString*
  parent: System.Windows.Media.Converters.TransformValueSerializer
  isExternal: false
  name: ConvertToString
  nameWithType: TransformValueSerializer.ConvertToString
