### YamlMime:ManagedReference
items:
- uid: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer
  id: Vector3DCollectionValueSerializer
  children:
  - System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.#ctor
  - System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  langs:
  - csharp
  name: Vector3DCollectionValueSerializer
  nameWithType: Vector3DCollectionValueSerializer
  fullName: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer
  type: Class
  summary: Converts instances of <xref href="System.String"></xref> to and from instances of <xref href="System.Windows.Media.Media3D.Vector3DCollection"></xref>.
  remarks: This class is only intended to be used by the <xref:System.Windows.Markup.Primitives.MarkupWriter> for serialization purposes.
  syntax:
    content: 'public class Vector3DCollectionValueSerializer : System.Windows.Markup.ValueSerializer'
  inheritance:
  - System.Object
  - System.Windows.Markup.ValueSerializer
  implements: []
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.Windows.Markup.ValueSerializer.GetConvertFromException(System.Object)
  - System.Windows.Markup.ValueSerializer.GetConvertToException(System.Object,System.Type)
  - System.Windows.Markup.ValueSerializer.GetSerializerFor(System.ComponentModel.PropertyDescriptor)
  - System.Windows.Markup.ValueSerializer.GetSerializerFor(System.ComponentModel.PropertyDescriptor,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Markup.ValueSerializer.GetSerializerFor(System.Type)
  - System.Windows.Markup.ValueSerializer.GetSerializerFor(System.Type,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Markup.ValueSerializer.TypeReferences(System.Object,System.Windows.Markup.IValueSerializerContext)
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Windows.Media.Media3D.Converters\Vector3DCollectionValueSerializer.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Windows.Media.Media3D.Converters/Vector3DCollectionValueSerializer.xml
  version:
  - netframework-3.0
  - netframework-3.5-client
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.#ctor
  id: '#ctor'
  parent: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer
  langs:
  - csharp
  name: Vector3DCollectionValueSerializer()
  nameWithType: Vector3DCollectionValueSerializer.Vector3DCollectionValueSerializer()
  fullName: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.Vector3DCollectionValueSerializer()
  type: Constructor
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Media3D.Converters
  summary: Initializes a new instance of the <xref href="System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer"></xref> class.
  syntax:
    content: public Vector3DCollectionValueSerializer ();
    parameters: []
  overload: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.#ctor*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Windows.Media.Media3D.Converters\Vector3DCollectionValueSerializer.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Windows.Media.Media3D.Converters/Vector3DCollectionValueSerializer.xml
  version:
  - netframework-3.0
  - netframework-3.5-client
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer
  langs:
  - csharp
  name: CanConvertFromString(String,IValueSerializerContext)
  nameWithType: Vector3DCollectionValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Media3D.Converters
  summary: Determines if conversion from a given <xref href="System.String"></xref> to an instance of <xref href="System.Windows.Media.Media3D.Vector3DCollection"></xref> is possible.
  remarks: This method always returns `true`.
  syntax:
    content: public override bool CanConvertFromString (string value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.String
      description: String to evaluate for conversion.
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: Context information used for conversion.
    return:
      type: System.Boolean
      description: '`true` if the value can be converted; otherwise, `false`.'
  overload: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.CanConvertFromString*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Windows.Media.Media3D.Converters\Vector3DCollectionValueSerializer.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Windows.Media.Media3D.Converters/Vector3DCollectionValueSerializer.xml
  version:
  - netframework-3.0
  - netframework-3.5-client
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer
  langs:
  - csharp
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: Vector3DCollectionValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Media3D.Converters
  summary: Determines if an instance of <xref href="System.Windows.Media.Media3D.Vector3DCollection"></xref> can be converted to a <xref href="System.String"></xref>.
  syntax:
    content: public override bool CanConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: Instance of <xref href="System.Windows.Media.Media3D.Vector3DCollection"></xref> to evaluate for conversion.
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: Context information used for conversion.
    return:
      type: System.Boolean
      description: '`true` if <code>value</code> can be converted into a <xref href="System.String"></xref>; otherwise, `false`.'
  overload: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.CanConvertToString*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: Occurs when <code>value</code> is not a <xref href="System.Windows.Media.Media3D.Vector3DCollection"></xref>.
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Windows.Media.Media3D.Converters\Vector3DCollectionValueSerializer.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Windows.Media.Media3D.Converters/Vector3DCollectionValueSerializer.xml
  version:
  - netframework-3.0
  - netframework-3.5-client
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  id: ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer
  langs:
  - csharp
  name: ConvertFromString(String,IValueSerializerContext)
  nameWithType: Vector3DCollectionValueSerializer.ConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.ConvertFromString(String,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Media3D.Converters
  summary: Converts a <xref href="System.String"></xref> into a <xref href="System.Windows.Media.Media3D.Vector3DCollection"></xref>.
  syntax:
    content: public override object ConvertFromString (string value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.String
      description: <xref href="System.String"></xref> value to convert into a <xref href="System.Windows.Media.Media3D.Vector3DCollection"></xref>.
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: Context information used for conversion.
    return:
      type: System.Object
      description: A new instance of <xref href="System.Windows.Media.Media3D.Vector3DCollection"></xref> based on the supplied <code>value</code>.
  overload: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.ConvertFromString*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Windows.Media.Media3D.Converters\Vector3DCollectionValueSerializer.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Windows.Media.Media3D.Converters/Vector3DCollectionValueSerializer.xml
  version:
  - netframework-3.0
  - netframework-3.5-client
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer
  langs:
  - csharp
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: Vector3DCollectionValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.ConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Media3D.Converters
  summary: Converts an instance of <xref href="System.Windows.Media.Media3D.Vector3DCollection"></xref> to a <xref href="System.String"></xref>.
  syntax:
    content: public override string ConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: Instance of <xref href="System.Windows.Media.Media3D.Vector3DCollection"></xref> to evaluate for conversion.
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: Context information used for conversion.
    return:
      type: System.String
      description: A <xref href="System.String"></xref> representation of the supplied <xref href="System.Windows.Media.Media3D.Vector3DCollection"></xref> object.
  overload: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.ConvertToString*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Windows.Media.Media3D.Converters\Vector3DCollectionValueSerializer.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Windows.Media.Media3D.Converters/Vector3DCollectionValueSerializer.xml
  version:
  - netframework-3.0
  - netframework-3.5-client
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
references:
- uid: System.Windows.Markup.ValueSerializer
  isExternal: false
  name: System.Windows.Markup.ValueSerializer
- uid: System.ArgumentException
  parent: System
  isExternal: false
  name: ArgumentException
  nameWithType: ArgumentException
  fullName: System.ArgumentException
- uid: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.#ctor
  parent: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer
  isExternal: false
  name: Vector3DCollectionValueSerializer()
  nameWithType: Vector3DCollectionValueSerializer.Vector3DCollectionValueSerializer()
  fullName: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.Vector3DCollectionValueSerializer()
- uid: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer
  isExternal: false
  name: CanConvertFromString(String,IValueSerializerContext)
  nameWithType: Vector3DCollectionValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.CanConvertFromString(String,IValueSerializerContext)
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Windows.Markup.IValueSerializerContext
  parent: System.Windows.Markup
  isExternal: false
  name: IValueSerializerContext
  nameWithType: IValueSerializerContext
  fullName: System.Windows.Markup.IValueSerializerContext
- uid: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer
  isExternal: false
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: Vector3DCollectionValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.CanConvertToString(Object,IValueSerializerContext)
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer
  isExternal: false
  name: ConvertFromString(String,IValueSerializerContext)
  nameWithType: Vector3DCollectionValueSerializer.ConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.ConvertFromString(String,IValueSerializerContext)
- uid: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer
  isExternal: false
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: Vector3DCollectionValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.ConvertToString(Object,IValueSerializerContext)
- uid: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.#ctor*
  parent: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer
  isExternal: false
  name: Vector3DCollectionValueSerializer
  nameWithType: Vector3DCollectionValueSerializer.Vector3DCollectionValueSerializer
- uid: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.CanConvertFromString*
  parent: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer
  isExternal: false
  name: CanConvertFromString
  nameWithType: Vector3DCollectionValueSerializer.CanConvertFromString
- uid: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.CanConvertToString*
  parent: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer
  isExternal: false
  name: CanConvertToString
  nameWithType: Vector3DCollectionValueSerializer.CanConvertToString
- uid: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.ConvertFromString*
  parent: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer
  isExternal: false
  name: ConvertFromString
  nameWithType: Vector3DCollectionValueSerializer.ConvertFromString
- uid: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.ConvertToString*
  parent: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer
  isExternal: false
  name: ConvertToString
  nameWithType: Vector3DCollectionValueSerializer.ConvertToString
