### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsDescriptionAttribute
  id: SettingsDescriptionAttribute
  children:
  - System.Configuration.SettingsDescriptionAttribute.#ctor(System.String)
  - System.Configuration.SettingsDescriptionAttribute.Description
  langs:
  - csharp
  name: SettingsDescriptionAttribute
  nameWithType: SettingsDescriptionAttribute
  fullName: System.Configuration.SettingsDescriptionAttribute
  type: Class
  summary: Provides a string that describes an individual configuration property. This class cannot be inherited.
  remarks: "The SettingsDescriptionAttribute is intended to assist both design time tools and administrative run time tools in identifying and describing the associated configuration property.  \n  \n This attribute is optional and can only be applied at the individual configuration property level."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class SettingsDescriptionAttribute : Attribute
  inheritance:
  - System.Object
  - System.Attribute
  implements: []
  inheritedMembers:
  - System.Attribute.Equals(System.Object)
  - System.Attribute.GetCustomAttribute(System.Reflection.Assembly,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.Module,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.GetHashCode
  - System.Attribute.IsDefaultAttribute
  - System.Attribute.IsDefined(System.Reflection.Assembly,System.Type)
  - System.Attribute.IsDefined(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.IsDefined(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.Module,System.Type)
  - System.Attribute.IsDefined(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.IsDefined(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.Match(System.Object)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetIDsOfNames(System.Guid@,System.IntPtr,System.UInt32,System.UInt32,System.IntPtr)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetTypeInfo(System.UInt32,System.UInt32,System.IntPtr)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetTypeInfoCount(System.UInt32@)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#Invoke(System.UInt32,System.Guid@,System.UInt32,System.Int16,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr)
  - System.Attribute.TypeId
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  platform:
  - netframework-2.0
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
- uid: System.Configuration.SettingsDescriptionAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.SettingsDescriptionAttribute
  langs:
  - csharp
  name: SettingsDescriptionAttribute(String)
  nameWithType: SettingsDescriptionAttribute.SettingsDescriptionAttribute(String)
  fullName: System.Configuration.SettingsDescriptionAttribute.SettingsDescriptionAttribute(String)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: Initializes an instance of the <xref href="System.Configuration.SettingsDescriptionAttribute"></xref> class.
  remarks: "Although the description has a theoretical maximum length of the <xref:System.String> class, whose length is represented by a <xref:System.Int32>, the following two practical considerations will limit the size of the `description` parameter:  \n  \n-   Large text descriptions are difficult to display in a user interface (UI) and difficult for the user to read.  \n  \n-   Settings providers may enforce overall usage quotas and are required to enforce user configuration quotas."
  syntax:
    content: public SettingsDescriptionAttribute (string description);
    parameters:
    - id: description
      type: System.String
      description: The <xref href="System.String"></xref> used as descriptive text.
  overload: System.Configuration.SettingsDescriptionAttribute.#ctor*
  exceptions: []
  platform:
  - netframework-2.0
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
- uid: System.Configuration.SettingsDescriptionAttribute.Description
  id: Description
  parent: System.Configuration.SettingsDescriptionAttribute
  langs:
  - csharp
  name: Description
  nameWithType: SettingsDescriptionAttribute.Description
  fullName: System.Configuration.SettingsDescriptionAttribute.Description
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: Gets the descriptive text for the associated configuration property.
  remarks: The Description property is set by the <xref:System.Configuration.SettingsDescriptionAttribute.%23ctor%2A> constructor.
  syntax:
    content: public string Description { get; }
    return:
      type: System.String
      description: A <xref href="System.String"></xref> containing the descriptive text for the associated configuration property.
  overload: System.Configuration.SettingsDescriptionAttribute.Description*
  exceptions: []
  platform:
  - netframework-2.0
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.SettingsDescriptionAttribute.#ctor(System.String)
  parent: System.Configuration.SettingsDescriptionAttribute
  isExternal: false
  name: SettingsDescriptionAttribute(String)
  nameWithType: SettingsDescriptionAttribute.SettingsDescriptionAttribute(String)
  fullName: System.Configuration.SettingsDescriptionAttribute.SettingsDescriptionAttribute(String)
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.SettingsDescriptionAttribute.Description
  parent: System.Configuration.SettingsDescriptionAttribute
  isExternal: false
  name: Description
  nameWithType: SettingsDescriptionAttribute.Description
  fullName: System.Configuration.SettingsDescriptionAttribute.Description
- uid: System.Configuration.SettingsDescriptionAttribute.#ctor*
  parent: System.Configuration.SettingsDescriptionAttribute
  isExternal: false
  name: SettingsDescriptionAttribute
  nameWithType: SettingsDescriptionAttribute.SettingsDescriptionAttribute
- uid: System.Configuration.SettingsDescriptionAttribute.Description*
  parent: System.Configuration.SettingsDescriptionAttribute
  isExternal: false
  name: Description
  nameWithType: SettingsDescriptionAttribute.Description
