### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsLoadedEventArgs
  id: SettingsLoadedEventArgs
  children:
  - System.Configuration.SettingsLoadedEventArgs.#ctor(System.Configuration.SettingsProvider)
  - System.Configuration.SettingsLoadedEventArgs.Provider
  langs:
  - csharp
  name: SettingsLoadedEventArgs
  nameWithType: SettingsLoadedEventArgs
  fullName: System.Configuration.SettingsLoadedEventArgs
  type: Class
  summary: Provides data for the <xref href="System.Configuration.ApplicationSettingsBase.SettingsLoaded"></xref> event.
  remarks: The SettingsLoadedEventArgs class provides data for the <xref:System.Configuration.ApplicationSettingsBase.SettingsLoaded> event, which occurs when settings are retrieved from a provider.
  syntax:
    content: 'public class SettingsLoadedEventArgs : EventArgs'
  inheritance:
  - System.Object
  - System.EventArgs
  implements: []
  inheritedMembers:
  - System.EventArgs.Empty
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Configuration\SettingsLoadedEventArgs.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Configuration/SettingsLoadedEventArgs.xml
  version:
  - netframework-3.0
  - netframework-3.5-client
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.Configuration.SettingsLoadedEventArgs.#ctor(System.Configuration.SettingsProvider)
  id: '#ctor(System.Configuration.SettingsProvider)'
  parent: System.Configuration.SettingsLoadedEventArgs
  langs:
  - csharp
  name: SettingsLoadedEventArgs(SettingsProvider)
  nameWithType: SettingsLoadedEventArgs.SettingsLoadedEventArgs(SettingsProvider)
  fullName: System.Configuration.SettingsLoadedEventArgs.SettingsLoadedEventArgs(SettingsProvider)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: Initializes a new instance of the <xref href="System.Configuration.SettingsLoadedEventArgs"></xref> class.
  syntax:
    content: public SettingsLoadedEventArgs (System.Configuration.SettingsProvider provider);
    parameters:
    - id: provider
      type: System.Configuration.SettingsProvider
      description: A <xref href="System.Configuration.SettingsProvider"></xref> object from which settings are loaded.
  overload: System.Configuration.SettingsLoadedEventArgs.#ctor*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Configuration\SettingsLoadedEventArgs.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Configuration/SettingsLoadedEventArgs.xml
  version:
  - netframework-3.0
  - netframework-3.5-client
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.Configuration.SettingsLoadedEventArgs.Provider
  id: Provider
  parent: System.Configuration.SettingsLoadedEventArgs
  langs:
  - csharp
  name: Provider
  nameWithType: SettingsLoadedEventArgs.Provider
  fullName: System.Configuration.SettingsLoadedEventArgs.Provider
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: Gets the settings provider used to store configuration settings.
  syntax:
    content: public System.Configuration.SettingsProvider Provider { get; }
    return:
      type: System.Configuration.SettingsProvider
      description: A settings provider.
  overload: System.Configuration.SettingsLoadedEventArgs.Provider*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Configuration\SettingsLoadedEventArgs.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Configuration/SettingsLoadedEventArgs.xml
  version:
  - netframework-3.0
  - netframework-3.5-client
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
references:
- uid: System.EventArgs
  isExternal: false
  name: System.EventArgs
- uid: System.Configuration.SettingsLoadedEventArgs.#ctor(System.Configuration.SettingsProvider)
  parent: System.Configuration.SettingsLoadedEventArgs
  isExternal: false
  name: SettingsLoadedEventArgs(SettingsProvider)
  nameWithType: SettingsLoadedEventArgs.SettingsLoadedEventArgs(SettingsProvider)
  fullName: System.Configuration.SettingsLoadedEventArgs.SettingsLoadedEventArgs(SettingsProvider)
- uid: System.Configuration.SettingsProvider
  parent: System.Configuration
  isExternal: false
  name: SettingsProvider
  nameWithType: SettingsProvider
  fullName: System.Configuration.SettingsProvider
- uid: System.Configuration.SettingsLoadedEventArgs.Provider
  parent: System.Configuration.SettingsLoadedEventArgs
  isExternal: false
  name: Provider
  nameWithType: SettingsLoadedEventArgs.Provider
  fullName: System.Configuration.SettingsLoadedEventArgs.Provider
- uid: System.Configuration.SettingsLoadedEventArgs.#ctor*
  parent: System.Configuration.SettingsLoadedEventArgs
  isExternal: false
  name: SettingsLoadedEventArgs
  nameWithType: SettingsLoadedEventArgs.SettingsLoadedEventArgs
- uid: System.Configuration.SettingsLoadedEventArgs.Provider*
  parent: System.Configuration.SettingsLoadedEventArgs
  isExternal: false
  name: Provider
  nameWithType: SettingsLoadedEventArgs.Provider
