### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.RegexWorker
  id: RegexWorker
  children:
  - System.Web.Configuration.RegexWorker.#ctor(System.Web.HttpBrowserCapabilities)
  - System.Web.Configuration.RegexWorker.Item(System.String)
  - System.Web.Configuration.RegexWorker.ProcessRegex(System.String,System.String)
  langs:
  - csharp
  name: RegexWorker
  nameWithType: RegexWorker
  fullName: System.Web.Configuration.RegexWorker
  type: Class
  summary: Used internally at run time by <xref href="System.Web.Configuration.BrowserCapabilitiesFactory"></xref> and <xref href="System.Web.Configuration.BrowserCapabilitiesCodeGenerator"></xref> to parse request data and identify the browser.
  syntax:
    content: public class RegexWorker
  inheritance:
  - System.Object
  implements: []
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-2.0
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
- uid: System.Web.Configuration.RegexWorker.#ctor(System.Web.HttpBrowserCapabilities)
  id: '#ctor(System.Web.HttpBrowserCapabilities)'
  parent: System.Web.Configuration.RegexWorker
  langs:
  - csharp
  name: RegexWorker(HttpBrowserCapabilities)
  nameWithType: RegexWorker.RegexWorker(HttpBrowserCapabilities)
  fullName: System.Web.Configuration.RegexWorker.RegexWorker(HttpBrowserCapabilities)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Creates a new instance of <xref href="System.Web.Configuration.RegexWorker"></xref>.
  syntax:
    content: public RegexWorker (System.Web.HttpBrowserCapabilities browserCaps);
    parameters:
    - id: browserCaps
      type: System.Web.HttpBrowserCapabilities
      description: The <xref href="System.Web.Configuration.HttpCapabilitiesBase"></xref> object to be configured.
  overload: System.Web.Configuration.RegexWorker.#ctor*
  exceptions: []
  version:
  - netframework-2.0
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
- uid: System.Web.Configuration.RegexWorker.Item(System.String)
  id: Item(System.String)
  parent: System.Web.Configuration.RegexWorker
  langs:
  - csharp
  name: Item(String)
  nameWithType: RegexWorker.Item(String)
  fullName: System.Web.Configuration.RegexWorker.Item(String)
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Accessor to this class.
  syntax:
    content: public string this[string key] { get; }
    parameters:
    - id: key
      type: System.String
      description: The specified key.
    return:
      type: System.String
      description: The internal value associated with the specified<code>key</code>.
  overload: System.Web.Configuration.RegexWorker.Item*
  exceptions: []
  version:
  - netframework-2.0
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
- uid: System.Web.Configuration.RegexWorker.ProcessRegex(System.String,System.String)
  id: ProcessRegex(System.String,System.String)
  parent: System.Web.Configuration.RegexWorker
  langs:
  - csharp
  name: ProcessRegex(String,String)
  nameWithType: RegexWorker.ProcessRegex(String,String)
  fullName: System.Web.Configuration.RegexWorker.ProcessRegex(String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Used internally at run time to determine whether the specified request-header value matches any of the capabilities of an internal collection of browsers.
  syntax:
    content: public bool ProcessRegex (string target, string regexExpression);
    parameters:
    - id: target
      type: System.String
      description: The capabilities value from an internal collection of browsers.
    - id: regexExpression
      type: System.String
      description: The specified request-header value.
    return:
      type: System.Boolean
      description: '`true` if the specified request-header value matches any of the capabilities of an internal collection of browsers; otherwise, `false`. The default is `false`.'
  overload: System.Web.Configuration.RegexWorker.ProcessRegex*
  exceptions: []
  version:
  - netframework-2.0
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.Configuration.RegexWorker.#ctor(System.Web.HttpBrowserCapabilities)
  parent: System.Web.Configuration.RegexWorker
  isExternal: false
  name: RegexWorker(HttpBrowserCapabilities)
  nameWithType: RegexWorker.RegexWorker(HttpBrowserCapabilities)
  fullName: System.Web.Configuration.RegexWorker.RegexWorker(HttpBrowserCapabilities)
- uid: System.Web.HttpBrowserCapabilities
  parent: System.Web
  isExternal: false
  name: HttpBrowserCapabilities
  nameWithType: HttpBrowserCapabilities
  fullName: System.Web.HttpBrowserCapabilities
- uid: System.Web.Configuration.RegexWorker.Item(System.String)
  parent: System.Web.Configuration.RegexWorker
  isExternal: false
  name: Item(String)
  nameWithType: RegexWorker.Item(String)
  fullName: System.Web.Configuration.RegexWorker.Item(String)
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.RegexWorker.ProcessRegex(System.String,System.String)
  parent: System.Web.Configuration.RegexWorker
  isExternal: false
  name: ProcessRegex(String,String)
  nameWithType: RegexWorker.ProcessRegex(String,String)
  fullName: System.Web.Configuration.RegexWorker.ProcessRegex(String,String)
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Configuration.RegexWorker.#ctor*
  parent: System.Web.Configuration.RegexWorker
  isExternal: false
  name: RegexWorker
  nameWithType: RegexWorker.RegexWorker
- uid: System.Web.Configuration.RegexWorker.Item*
  parent: System.Web.Configuration.RegexWorker
  isExternal: false
  name: Item
  nameWithType: RegexWorker.Item
- uid: System.Web.Configuration.RegexWorker.ProcessRegex*
  parent: System.Web.Configuration.RegexWorker
  isExternal: false
  name: ProcessRegex
  nameWithType: RegexWorker.ProcessRegex
