### YamlMime:ManagedReference
items:
- uid: System.Xaml.XamlSchemaContextSettings
  id: XamlSchemaContextSettings
  children:
  - System.Xaml.XamlSchemaContextSettings.#ctor
  - System.Xaml.XamlSchemaContextSettings.#ctor(System.Xaml.XamlSchemaContextSettings)
  - System.Xaml.XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces
  - System.Xaml.XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity
  langs:
  - csharp
  name: XamlSchemaContextSettings
  nameWithType: XamlSchemaContextSettings
  fullName: System.Xaml.XamlSchemaContextSettings
  type: Class
  summary: Provides optional settings for a <xref href="System.Xaml.XamlSchemaContext"></xref>.
  syntax:
    content: public class XamlSchemaContextSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Xaml\XamlSchemaContextSettings.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Xaml/XamlSchemaContextSettings.xml
  version:
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.Xaml.XamlSchemaContextSettings.#ctor
  id: '#ctor'
  parent: System.Xaml.XamlSchemaContextSettings
  langs:
  - csharp
  name: XamlSchemaContextSettings()
  nameWithType: XamlSchemaContextSettings.XamlSchemaContextSettings()
  fullName: System.Xaml.XamlSchemaContextSettings.XamlSchemaContextSettings()
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: Initializes a new instance of the <xref href="System.Xaml.XamlSchemaContextSettings"></xref> class.
  syntax:
    content: public XamlSchemaContextSettings ();
    parameters: []
  overload: System.Xaml.XamlSchemaContextSettings.#ctor*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Xaml\XamlSchemaContextSettings.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Xaml/XamlSchemaContextSettings.xml
  version:
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.Xaml.XamlSchemaContextSettings.#ctor(System.Xaml.XamlSchemaContextSettings)
  id: '#ctor(System.Xaml.XamlSchemaContextSettings)'
  parent: System.Xaml.XamlSchemaContextSettings
  langs:
  - csharp
  name: XamlSchemaContextSettings(XamlSchemaContextSettings)
  nameWithType: XamlSchemaContextSettings.XamlSchemaContextSettings(XamlSchemaContextSettings)
  fullName: System.Xaml.XamlSchemaContextSettings.XamlSchemaContextSettings(XamlSchemaContextSettings)
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: Initializes a new instance of the <xref href="System.Xaml.XamlSchemaContextSettings"></xref> class by copying the values of an existing <xref href="System.Xaml.XamlSchemaContextSettings"></xref> instance.
  syntax:
    content: public XamlSchemaContextSettings (System.Xaml.XamlSchemaContextSettings settings);
    parameters:
    - id: settings
      type: System.Xaml.XamlSchemaContextSettings
      description: An existing <xref href="System.Xaml.XamlSchemaContextSettings"></xref>.
  overload: System.Xaml.XamlSchemaContextSettings.#ctor*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Xaml\XamlSchemaContextSettings.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Xaml/XamlSchemaContextSettings.xml
  version:
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.Xaml.XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces
  id: FullyQualifyAssemblyNamesInClrNamespaces
  parent: System.Xaml.XamlSchemaContextSettings
  langs:
  - csharp
  name: FullyQualifyAssemblyNamesInClrNamespaces
  nameWithType: XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces
  fullName: System.Xaml.XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: Gets or sets a value that specifies whether a XAML schema and its context use fully qualified assembly names in the values that are returned by the lookup API.
  remarks: The value of this property influences the strings that are returned by <xref:System.Xaml.XamlSchemaContext.GetAllXamlNamespaces%2A> in the constructed schema context. If <xref:System.Xaml.XamlSchemaContext.FullyQualifyAssemblyNamesInClrNamespaces%2A> is `true`, the assembly part of the string reports the equivalent of <xref:System.Reflection.Assembly.FullName%2A?displayProperty=fullName>.
  syntax:
    content: public bool FullyQualifyAssemblyNamesInClrNamespaces { get; set; }
    return:
      type: System.Boolean
      description: '`true` if a XAML schema and its context use fully qualified assembly names in the values that are returned by the lookup APIs; otherwise, `false`.'
  overload: System.Xaml.XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Xaml\XamlSchemaContextSettings.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Xaml/XamlSchemaContextSettings.xml
  version:
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.Xaml.XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity
  id: SupportMarkupExtensionsWithDuplicateArity
  parent: System.Xaml.XamlSchemaContextSettings
  langs:
  - csharp
  name: SupportMarkupExtensionsWithDuplicateArity
  nameWithType: XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity
  fullName: System.Xaml.XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: Gets or sets a value that specifies whether a XAML schema context allows for markup extensions that have two constructors with the same arity (number of input parameters).
  remarks: From a <xref:System.Xaml.XamlSchemaContext>, you cannot read the settings directly. Instead, you receive values from specific read-only properties, such as <xref:System.Xaml.XamlSchemaContext.SupportMarkupExtensionsWithDuplicateArity%2A>, which report the settings-based values.
  syntax:
    content: public bool SupportMarkupExtensionsWithDuplicateArity { get; set; }
    return:
      type: System.Boolean
      description: '`true` if the schema context allows for markup extensions that have duplicate arity; otherwise, `false`.'
  overload: System.Xaml.XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Xaml\XamlSchemaContextSettings.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Xaml/XamlSchemaContextSettings.xml
  version:
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Xaml.XamlSchemaContextSettings.#ctor
  parent: System.Xaml.XamlSchemaContextSettings
  isExternal: false
  name: XamlSchemaContextSettings()
  nameWithType: XamlSchemaContextSettings.XamlSchemaContextSettings()
  fullName: System.Xaml.XamlSchemaContextSettings.XamlSchemaContextSettings()
- uid: System.Xaml.XamlSchemaContextSettings.#ctor(System.Xaml.XamlSchemaContextSettings)
  parent: System.Xaml.XamlSchemaContextSettings
  isExternal: false
  name: XamlSchemaContextSettings(XamlSchemaContextSettings)
  nameWithType: XamlSchemaContextSettings.XamlSchemaContextSettings(XamlSchemaContextSettings)
  fullName: System.Xaml.XamlSchemaContextSettings.XamlSchemaContextSettings(XamlSchemaContextSettings)
- uid: System.Xaml.XamlSchemaContextSettings
  parent: System.Xaml
  isExternal: false
  name: XamlSchemaContextSettings
  nameWithType: XamlSchemaContextSettings
  fullName: System.Xaml.XamlSchemaContextSettings
- uid: System.Xaml.XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces
  parent: System.Xaml.XamlSchemaContextSettings
  isExternal: false
  name: FullyQualifyAssemblyNamesInClrNamespaces
  nameWithType: XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces
  fullName: System.Xaml.XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Xaml.XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity
  parent: System.Xaml.XamlSchemaContextSettings
  isExternal: false
  name: SupportMarkupExtensionsWithDuplicateArity
  nameWithType: XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity
  fullName: System.Xaml.XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity
- uid: System.Xaml.XamlSchemaContextSettings.#ctor*
  parent: System.Xaml.XamlSchemaContextSettings
  isExternal: false
  name: XamlSchemaContextSettings
  nameWithType: XamlSchemaContextSettings.XamlSchemaContextSettings
- uid: System.Xaml.XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces*
  parent: System.Xaml.XamlSchemaContextSettings
  isExternal: false
  name: FullyQualifyAssemblyNamesInClrNamespaces
  nameWithType: XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces
- uid: System.Xaml.XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity*
  parent: System.Xaml.XamlSchemaContextSettings
  isExternal: false
  name: SupportMarkupExtensionsWithDuplicateArity
  nameWithType: XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity
