### YamlMime:ManagedReference
items:
- uid: System.Windows.Media.Converters.CacheModeValueSerializer
  id: CacheModeValueSerializer
  children:
  - System.Windows.Media.Converters.CacheModeValueSerializer.#ctor
  - System.Windows.Media.Converters.CacheModeValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Media.Converters.CacheModeValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Media.Converters.CacheModeValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Media.Converters.CacheModeValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  langs:
  - csharp
  name: CacheModeValueSerializer
  nameWithType: CacheModeValueSerializer
  fullName: System.Windows.Media.Converters.CacheModeValueSerializer
  type: Class
  summary: Converts instances of <xref href="System.String"></xref> to and from instances of <xref href="System.Windows.Media.CacheMode"></xref>.
  remarks: This class is typically only used by the <xref:System.Windows.Markup.Primitives.MarkupWriter> for serialization purposes.
  syntax:
    content: 'public class CacheModeValueSerializer : System.Windows.Markup.ValueSerializer'
  inheritance:
  - System.Object
  - System.Windows.Markup.ValueSerializer
  implements: []
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.Windows.Markup.ValueSerializer.GetConvertFromException(System.Object)
  - System.Windows.Markup.ValueSerializer.GetConvertToException(System.Object,System.Type)
  - System.Windows.Markup.ValueSerializer.GetSerializerFor(System.ComponentModel.PropertyDescriptor)
  - System.Windows.Markup.ValueSerializer.GetSerializerFor(System.ComponentModel.PropertyDescriptor,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Markup.ValueSerializer.GetSerializerFor(System.Type)
  - System.Windows.Markup.ValueSerializer.GetSerializerFor(System.Type,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Markup.ValueSerializer.TypeReferences(System.Object,System.Windows.Markup.IValueSerializerContext)
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Windows.Media.Converters\CacheModeValueSerializer.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Windows.Media.Converters/CacheModeValueSerializer.xml
  version:
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.Windows.Media.Converters.CacheModeValueSerializer.#ctor
  id: '#ctor'
  parent: System.Windows.Media.Converters.CacheModeValueSerializer
  langs:
  - csharp
  name: CacheModeValueSerializer()
  nameWithType: CacheModeValueSerializer.CacheModeValueSerializer()
  fullName: System.Windows.Media.Converters.CacheModeValueSerializer.CacheModeValueSerializer()
  type: Constructor
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Converters
  summary: Initializes a new instance of the <xref href="System.Windows.Media.Converters.CacheModeValueSerializer"></xref> class.
  syntax:
    content: public CacheModeValueSerializer ();
    parameters: []
  overload: System.Windows.Media.Converters.CacheModeValueSerializer.#ctor*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Windows.Media.Converters\CacheModeValueSerializer.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Windows.Media.Converters/CacheModeValueSerializer.xml
  version:
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.Windows.Media.Converters.CacheModeValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.CacheModeValueSerializer
  langs:
  - csharp
  name: CanConvertFromString(String,IValueSerializerContext)
  nameWithType: CacheModeValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.CacheModeValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Converters
  summary: Determines whether the specified <xref href="System.String"></xref> can be converted to an instance of <xref href="System.Windows.Media.CacheMode"></xref>.
  remarks: This method always returns `true`.
  syntax:
    content: public override bool CanConvertFromString (string value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.String
      description: A <xref href="System.String"></xref> to evaluate for conversion.
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: Context information that is used for conversion.
    return:
      type: System.Boolean
      description: '`true` if <code>value</code> can be converted; otherwise, `false`.'
  overload: System.Windows.Media.Converters.CacheModeValueSerializer.CanConvertFromString*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Windows.Media.Converters\CacheModeValueSerializer.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Windows.Media.Converters/CacheModeValueSerializer.xml
  version:
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.Windows.Media.Converters.CacheModeValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.CacheModeValueSerializer
  langs:
  - csharp
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: CacheModeValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.CacheModeValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Converters
  summary: Determines whether the specified instance of <xref href="System.Windows.Media.CacheMode"></xref> can be converted to a <xref href="System.String"></xref>.
  syntax:
    content: public override bool CanConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: An instance of <xref href="System.Windows.Media.CacheMode"></xref> to evaluate for conversion.
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: Context information that is used for conversion.
    return:
      type: System.Boolean
      description: '`true` if <code>value</code> can be converted into a <xref href="System.String"></xref>; otherwise, `false`.'
  overload: System.Windows.Media.Converters.CacheModeValueSerializer.CanConvertToString*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Windows.Media.Converters\CacheModeValueSerializer.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Windows.Media.Converters/CacheModeValueSerializer.xml
  version:
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.Windows.Media.Converters.CacheModeValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  id: ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.CacheModeValueSerializer
  langs:
  - csharp
  name: ConvertFromString(String,IValueSerializerContext)
  nameWithType: CacheModeValueSerializer.ConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.CacheModeValueSerializer.ConvertFromString(String,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Converters
  summary: Converts a <xref href="System.String"></xref> into a <xref href="System.Windows.Media.CacheMode"></xref>.
  syntax:
    content: public override object ConvertFromString (string value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.String
      description: A <xref href="System.String"></xref> value to convert into a <xref href="System.Windows.Media.CacheMode"></xref>.
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: Context information that is used for conversion.
    return:
      type: System.Object
      description: A new instance of <xref href="System.Windows.Media.CacheMode"></xref> based on the specified <code>value</code>.
  overload: System.Windows.Media.Converters.CacheModeValueSerializer.ConvertFromString*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Windows.Media.Converters\CacheModeValueSerializer.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Windows.Media.Converters/CacheModeValueSerializer.xml
  version:
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.Windows.Media.Converters.CacheModeValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.CacheModeValueSerializer
  langs:
  - csharp
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: CacheModeValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.CacheModeValueSerializer.ConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Converters
  summary: Converts an instance of <xref href="System.Windows.Media.CacheMode"></xref> to a <xref href="System.String"></xref>.
  syntax:
    content: public override string ConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: An instance of <xref href="System.Windows.Media.CacheMode"></xref> to evaluate for conversion.
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: Context information that is used for conversion.
    return:
      type: System.String
      description: A <xref href="System.String"></xref> representation of the specified <xref href="System.Windows.Media.CacheMode"></xref> object.
  overload: System.Windows.Media.Converters.CacheModeValueSerializer.ConvertToString*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Windows.Media.Converters\CacheModeValueSerializer.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Windows.Media.Converters/CacheModeValueSerializer.xml
  version:
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
references:
- uid: System.Windows.Markup.ValueSerializer
  isExternal: false
  name: System.Windows.Markup.ValueSerializer
- uid: System.Windows.Media.Converters.CacheModeValueSerializer.#ctor
  parent: System.Windows.Media.Converters.CacheModeValueSerializer
  isExternal: false
  name: CacheModeValueSerializer()
  nameWithType: CacheModeValueSerializer.CacheModeValueSerializer()
  fullName: System.Windows.Media.Converters.CacheModeValueSerializer.CacheModeValueSerializer()
- uid: System.Windows.Media.Converters.CacheModeValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.CacheModeValueSerializer
  isExternal: false
  name: CanConvertFromString(String,IValueSerializerContext)
  nameWithType: CacheModeValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.CacheModeValueSerializer.CanConvertFromString(String,IValueSerializerContext)
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Windows.Markup.IValueSerializerContext
  parent: System.Windows.Markup
  isExternal: false
  name: IValueSerializerContext
  nameWithType: IValueSerializerContext
  fullName: System.Windows.Markup.IValueSerializerContext
- uid: System.Windows.Media.Converters.CacheModeValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.CacheModeValueSerializer
  isExternal: false
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: CacheModeValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.CacheModeValueSerializer.CanConvertToString(Object,IValueSerializerContext)
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Windows.Media.Converters.CacheModeValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.CacheModeValueSerializer
  isExternal: false
  name: ConvertFromString(String,IValueSerializerContext)
  nameWithType: CacheModeValueSerializer.ConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.CacheModeValueSerializer.ConvertFromString(String,IValueSerializerContext)
- uid: System.Windows.Media.Converters.CacheModeValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.CacheModeValueSerializer
  isExternal: false
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: CacheModeValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.CacheModeValueSerializer.ConvertToString(Object,IValueSerializerContext)
- uid: System.Windows.Media.Converters.CacheModeValueSerializer.#ctor*
  parent: System.Windows.Media.Converters.CacheModeValueSerializer
  isExternal: false
  name: CacheModeValueSerializer
  nameWithType: CacheModeValueSerializer.CacheModeValueSerializer
- uid: System.Windows.Media.Converters.CacheModeValueSerializer.CanConvertFromString*
  parent: System.Windows.Media.Converters.CacheModeValueSerializer
  isExternal: false
  name: CanConvertFromString
  nameWithType: CacheModeValueSerializer.CanConvertFromString
- uid: System.Windows.Media.Converters.CacheModeValueSerializer.CanConvertToString*
  parent: System.Windows.Media.Converters.CacheModeValueSerializer
  isExternal: false
  name: CanConvertToString
  nameWithType: CacheModeValueSerializer.CanConvertToString
- uid: System.Windows.Media.Converters.CacheModeValueSerializer.ConvertFromString*
  parent: System.Windows.Media.Converters.CacheModeValueSerializer
  isExternal: false
  name: ConvertFromString
  nameWithType: CacheModeValueSerializer.ConvertFromString
- uid: System.Windows.Media.Converters.CacheModeValueSerializer.ConvertToString*
  parent: System.Windows.Media.Converters.CacheModeValueSerializer
  isExternal: false
  name: ConvertToString
  nameWithType: CacheModeValueSerializer.ConvertToString
