### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.MexBindingBindingCollectionElement`2
  id: MexBindingBindingCollectionElement`2
  children:
  - System.ServiceModel.Configuration.MexBindingBindingCollectionElement`2.#ctor
  - System.ServiceModel.Configuration.MexBindingBindingCollectionElement`2.TryAdd(System.String,System.ServiceModel.Channels.Binding,System.Configuration.Configuration)
  langs:
  - csharp
  name: MexBindingBindingCollectionElement<TStandardBinding,TBindingConfiguration>
  nameWithType: MexBindingBindingCollectionElement<TStandardBinding,TBindingConfiguration>
  fullName: System.ServiceModel.Configuration.MexBindingBindingCollectionElement<TStandardBinding,TBindingConfiguration>
  type: Class
  summary: Represents a collection of MEX binding configuration elements.
  syntax:
    content: 'public abstract class MexBindingBindingCollectionElement<TStandardBinding,TBindingConfiguration> : System.ServiceModel.Configuration.StandardBindingCollectionElement<TStandardBinding,TBindingConfiguration> where TStandardBinding : Binding where TBindingConfiguration : StandardBindingElementnew()'
    typeParameters:
    - id: TStandardBinding
      description: A standard binding element.
    - id: TBindingConfiguration
      description: A binding configuration element.
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.BindingCollectionElement
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.ServiceModel.Configuration.BindingCollectionElement.BindingName
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.Bindings
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.BindingType
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.ConfiguredBindings
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.ContainsKey(System.String)
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.GetDefault
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.Properties
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.ServiceModel.Configuration\MexBindingBindingCollectionElement`2.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.ServiceModel.Configuration/MexBindingBindingCollectionElement`2.xml
  version:
  - netframework-3.0
  - netframework-3.5-client
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.ServiceModel.Configuration.MexBindingBindingCollectionElement`2.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.MexBindingBindingCollectionElement`2
  langs:
  - csharp
  name: MexBindingBindingCollectionElement<TStandardBinding,TBindingConfiguration>()
  nameWithType: MexBindingBindingCollectionElement<TStandardBinding,TBindingConfiguration>.MexBindingBindingCollectionElement<TStandardBinding,TBindingConfiguration>()
  fullName: System.ServiceModel.Configuration.MexBindingBindingCollectionElement<TStandardBinding,TBindingConfiguration>.MexBindingBindingCollectionElement<TStandardBinding,TBindingConfiguration>()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="stem.ServiceModel.Configuration.MexBindingBindingCollectionElement%602"></xref> class.
  syntax:
    content: protected MexBindingBindingCollectionElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.MexBindingBindingCollectionElement`2.#ctor*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.ServiceModel.Configuration\MexBindingBindingCollectionElement`2.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.ServiceModel.Configuration/MexBindingBindingCollectionElement`2.xml
  version:
  - netframework-3.0
  - netframework-3.5-client
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.ServiceModel.Configuration.MexBindingBindingCollectionElement`2.TryAdd(System.String,System.ServiceModel.Channels.Binding,System.Configuration.Configuration)
  id: TryAdd(System.String,System.ServiceModel.Channels.Binding,System.Configuration.Configuration)
  parent: System.ServiceModel.Configuration.MexBindingBindingCollectionElement`2
  langs:
  - csharp
  name: TryAdd(String,Binding,Configuration)
  nameWithType: MexBindingBindingCollectionElement<TStandardBinding,TBindingConfiguration>.TryAdd(String,Binding,Configuration)
  fullName: System.ServiceModel.Configuration.MexBindingBindingCollectionElement<TStandardBinding,TBindingConfiguration>.TryAdd(String,Binding,Configuration)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Adds the specified binding to the collection.
  syntax:
    content: protected override bool TryAdd (string name, System.ServiceModel.Channels.Binding binding, System.Configuration.Configuration config);
    parameters:
    - id: name
      type: System.String
      description: The name of the binding to be added.
    - id: binding
      type: System.ServiceModel.Channels.Binding
      description: A <xref href="System.ServiceModel.Channels.Binding"></xref> object that represents the binding to be added.
    - id: config
      type: System.Configuration.Configuration
      description: The configuration settings for this binding.
    return:
      type: System.Boolean
      description: '`true` if the binding can be added to this collection; otherwise, `false`.'
  overload: System.ServiceModel.Configuration.MexBindingBindingCollectionElement`2.TryAdd*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.ServiceModel.Configuration\MexBindingBindingCollectionElement`2.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.ServiceModel.Configuration/MexBindingBindingCollectionElement`2.xml
  version:
  - netframework-3.0
  - netframework-3.5-client
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
references:
- uid: System.ServiceModel.Configuration.StandardBindingCollectionElement`2
  isExternal: false
  name: System.ServiceModel.Configuration.StandardBindingCollectionElement<TStandardBinding,TBindingConfiguration>
- uid: System.ServiceModel.Configuration.MexBindingBindingCollectionElement`2.#ctor
  parent: System.ServiceModel.Configuration.MexBindingBindingCollectionElement`2
  isExternal: false
  name: MexBindingBindingCollectionElement<TStandardBinding,TBindingConfiguration>()
  nameWithType: MexBindingBindingCollectionElement<TStandardBinding,TBindingConfiguration>.MexBindingBindingCollectionElement<TStandardBinding,TBindingConfiguration>()
  fullName: System.ServiceModel.Configuration.MexBindingBindingCollectionElement<TStandardBinding,TBindingConfiguration>.MexBindingBindingCollectionElement<TStandardBinding,TBindingConfiguration>()
- uid: System.ServiceModel.Configuration.MexBindingBindingCollectionElement`2.TryAdd(System.String,System.ServiceModel.Channels.Binding,System.Configuration.Configuration)
  parent: System.ServiceModel.Configuration.MexBindingBindingCollectionElement`2
  isExternal: false
  name: TryAdd(String,Binding,Configuration)
  nameWithType: MexBindingBindingCollectionElement<TStandardBinding,TBindingConfiguration>.TryAdd(String,Binding,Configuration)
  fullName: System.ServiceModel.Configuration.MexBindingBindingCollectionElement<TStandardBinding,TBindingConfiguration>.TryAdd(String,Binding,Configuration)
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Channels.Binding
  parent: System.ServiceModel.Channels
  isExternal: false
  name: Binding
  nameWithType: Binding
  fullName: System.ServiceModel.Channels.Binding
- uid: System.Configuration.Configuration
  parent: System.Configuration
  isExternal: false
  name: Configuration
  nameWithType: Configuration
  fullName: System.Configuration.Configuration
- uid: System.ServiceModel.Configuration.MexBindingBindingCollectionElement`2.#ctor*
  parent: System.ServiceModel.Configuration.MexBindingBindingCollectionElement`2
  isExternal: false
  name: MexBindingBindingCollectionElement<TStandardBinding,TBindingConfiguration>
  nameWithType: MexBindingBindingCollectionElement<TStandardBinding,TBindingConfiguration>.MexBindingBindingCollectionElement<TStandardBinding,TBindingConfiguration>
- uid: System.ServiceModel.Configuration.MexBindingBindingCollectionElement`2.TryAdd*
  parent: System.ServiceModel.Configuration.MexBindingBindingCollectionElement`2
  isExternal: false
  name: TryAdd
  nameWithType: MexBindingBindingCollectionElement<TStandardBinding,TBindingConfiguration>.TryAdd
