### YamlMime:ManagedReference
items:
- uid: System.Reflection.AssemblyConfigurationAttribute
  id: AssemblyConfigurationAttribute
  children:
  - System.Reflection.AssemblyConfigurationAttribute.#ctor(System.String)
  - System.Reflection.AssemblyConfigurationAttribute.Configuration
  langs:
  - csharp
  name: AssemblyConfigurationAttribute
  nameWithType: AssemblyConfigurationAttribute
  fullName: System.Reflection.AssemblyConfigurationAttribute
  type: Class
  summary: Specifies the build configuration, such as retail or debug, for an assembly.
  remarks: In integrated build environments such as Microsoft Visual Studio, build configuration information is usually determined by the development environment settings for the project.
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Assembly, Inherited=false)]

      [System.Runtime.InteropServices.ComVisible(true)]

      public sealed class AssemblyConfigurationAttribute : Attribute
  inheritance:
  - System.Object
  - System.Attribute
  implements: []
  inheritedMembers:
  - System.Attribute.Equals(System.Object)
  - System.Attribute.GetCustomAttribute(System.Reflection.Assembly,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.Module,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.GetHashCode
  - System.Attribute.IsDefaultAttribute
  - System.Attribute.IsDefined(System.Reflection.Assembly,System.Type)
  - System.Attribute.IsDefined(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.IsDefined(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.Module,System.Type)
  - System.Attribute.IsDefined(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.IsDefined(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.Match(System.Object)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetIDsOfNames(System.Guid@,System.IntPtr,System.UInt32,System.UInt32,System.IntPtr)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetTypeInfo(System.UInt32,System.UInt32,System.IntPtr)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetTypeInfoCount(System.UInt32@)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#Invoke(System.UInt32,System.Guid@,System.UInt32,System.Int16,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr)
  - System.Attribute.TypeId
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Reflection\AssemblyConfigurationAttribute.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Reflection/AssemblyConfigurationAttribute.xml
  version:
  - netframework-3.0
  - netframework-3.5-client
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.Reflection.AssemblyConfigurationAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Reflection.AssemblyConfigurationAttribute
  langs:
  - csharp
  name: AssemblyConfigurationAttribute(String)
  nameWithType: AssemblyConfigurationAttribute.AssemblyConfigurationAttribute(String)
  fullName: System.Reflection.AssemblyConfigurationAttribute.AssemblyConfigurationAttribute(String)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Reflection
  summary: Initializes a new instance of the <xref href="System.Reflection.AssemblyConfigurationAttribute"></xref> class.
  syntax:
    content: public AssemblyConfigurationAttribute (string configuration);
    parameters:
    - id: configuration
      type: System.String
      description: The assembly configuration.
  overload: System.Reflection.AssemblyConfigurationAttribute.#ctor*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Reflection\AssemblyConfigurationAttribute.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Reflection/AssemblyConfigurationAttribute.xml
  version:
  - netframework-3.0
  - netframework-3.5-client
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.Reflection.AssemblyConfigurationAttribute.Configuration
  id: Configuration
  parent: System.Reflection.AssemblyConfigurationAttribute
  langs:
  - csharp
  name: Configuration
  nameWithType: AssemblyConfigurationAttribute.Configuration
  fullName: System.Reflection.AssemblyConfigurationAttribute.Configuration
  type: Property
  assemblies:
  - mscorlib
  namespace: System.Reflection
  summary: Gets assembly configuration information.
  syntax:
    content: public string Configuration { get; }
    return:
      type: System.String
      description: A string containing the assembly configuration information.
  overload: System.Reflection.AssemblyConfigurationAttribute.Configuration*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Reflection\AssemblyConfigurationAttribute.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Reflection/AssemblyConfigurationAttribute.xml
  version:
  - netframework-3.0
  - netframework-3.5-client
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Reflection.AssemblyConfigurationAttribute.#ctor(System.String)
  parent: System.Reflection.AssemblyConfigurationAttribute
  isExternal: false
  name: AssemblyConfigurationAttribute(String)
  nameWithType: AssemblyConfigurationAttribute.AssemblyConfigurationAttribute(String)
  fullName: System.Reflection.AssemblyConfigurationAttribute.AssemblyConfigurationAttribute(String)
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Reflection.AssemblyConfigurationAttribute.Configuration
  parent: System.Reflection.AssemblyConfigurationAttribute
  isExternal: false
  name: Configuration
  nameWithType: AssemblyConfigurationAttribute.Configuration
  fullName: System.Reflection.AssemblyConfigurationAttribute.Configuration
- uid: System.Reflection.AssemblyConfigurationAttribute.#ctor*
  parent: System.Reflection.AssemblyConfigurationAttribute
  isExternal: false
  name: AssemblyConfigurationAttribute
  nameWithType: AssemblyConfigurationAttribute.AssemblyConfigurationAttribute
- uid: System.Reflection.AssemblyConfigurationAttribute.Configuration*
  parent: System.Reflection.AssemblyConfigurationAttribute
  isExternal: false
  name: Configuration
  nameWithType: AssemblyConfigurationAttribute.Configuration
