### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.HttpDigestClientElement
  id: HttpDigestClientElement
  children:
  - System.ServiceModel.Configuration.HttpDigestClientElement.#ctor
  - System.ServiceModel.Configuration.HttpDigestClientElement.Copy(System.ServiceModel.Configuration.HttpDigestClientElement)
  - System.ServiceModel.Configuration.HttpDigestClientElement.ImpersonationLevel
  - System.ServiceModel.Configuration.HttpDigestClientElement.Properties
  langs:
  - csharp
  name: HttpDigestClientElement
  nameWithType: HttpDigestClientElement
  fullName: System.ServiceModel.Configuration.HttpDigestClientElement
  type: Class
  summary: Represents the current HTTP digest credential in the `clientCredential` element. This class cannot be inherited.
  syntax:
    content: 'public sealed class HttpDigestClientElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-30
  - netframework-35
  - netframework-40
- uid: System.ServiceModel.Configuration.HttpDigestClientElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.HttpDigestClientElement
  langs:
  - csharp
  name: HttpDigestClientElement()
  nameWithType: HttpDigestClientElement.HttpDigestClientElement()
  fullName: System.ServiceModel.Configuration.HttpDigestClientElement.HttpDigestClientElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.HttpDigestClientElement"></xref> class.
  syntax:
    content: public HttpDigestClientElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.HttpDigestClientElement.#ctor*
  exceptions: []
  version:
  - netframework-30
  - netframework-35
  - netframework-40
- uid: System.ServiceModel.Configuration.HttpDigestClientElement.Copy(System.ServiceModel.Configuration.HttpDigestClientElement)
  id: Copy(System.ServiceModel.Configuration.HttpDigestClientElement)
  parent: System.ServiceModel.Configuration.HttpDigestClientElement
  langs:
  - csharp
  name: Copy(HttpDigestClientElement)
  nameWithType: HttpDigestClientElement.Copy(HttpDigestClientElement)
  fullName: System.ServiceModel.Configuration.HttpDigestClientElement.Copy(HttpDigestClientElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Copies the content of the specified configuration element to this configuration element.
  syntax:
    content: public void Copy (System.ServiceModel.Configuration.HttpDigestClientElement from);
    parameters:
    - id: from
      type: System.ServiceModel.Configuration.HttpDigestClientElement
      description: The configuration element to be copied.
  overload: System.ServiceModel.Configuration.HttpDigestClientElement.Copy*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: <code>from</code> is `null` or empty.
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: The configuration file is read-only.
  version:
  - netframework-30
  - netframework-35
  - netframework-40
- uid: System.ServiceModel.Configuration.HttpDigestClientElement.ImpersonationLevel
  id: ImpersonationLevel
  parent: System.ServiceModel.Configuration.HttpDigestClientElement
  langs:
  - csharp
  name: ImpersonationLevel
  nameWithType: HttpDigestClientElement.ImpersonationLevel
  fullName: System.ServiceModel.Configuration.HttpDigestClientElement.ImpersonationLevel
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets or sets the impersonation preference that the client uses to communicate to the server.
  remarks: The impersonation mode that the client chooses is not enforced on the server.
  syntax:
    content: public System.Security.Principal.TokenImpersonationLevel ImpersonationLevel { get; set; }
    return:
      type: System.Security.Principal.TokenImpersonationLevel
      description: A valid <xref href="System.Security.Principal.TokenImpersonationLevel"></xref> value. The default is <xref href="System.Security.Principal.TokenImpersonationLevel"></xref>.
  overload: System.ServiceModel.Configuration.HttpDigestClientElement.ImpersonationLevel*
  exceptions: []
  version:
  - netframework-30
  - netframework-35
  - netframework-40
- uid: System.ServiceModel.Configuration.HttpDigestClientElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.HttpDigestClientElement
  langs:
  - csharp
  name: Properties
  nameWithType: HttpDigestClientElement.Properties
  fullName: System.ServiceModel.Configuration.HttpDigestClientElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.ServiceModel.Configuration.HttpDigestClientElement.Properties*
  exceptions: []
  version:
  - netframework-30
  - netframework-35
  - netframework-40
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ArgumentNullException
  parent: System
  isExternal: false
  name: ArgumentNullException
  nameWithType: ArgumentNullException
  fullName: System.ArgumentNullException
- uid: System.Configuration.ConfigurationErrorsException
  parent: System.Configuration
  isExternal: false
  name: ConfigurationErrorsException
  nameWithType: ConfigurationErrorsException
  fullName: System.Configuration.ConfigurationErrorsException
- uid: System.ServiceModel.Configuration.HttpDigestClientElement.#ctor
  parent: System.ServiceModel.Configuration.HttpDigestClientElement
  isExternal: false
  name: HttpDigestClientElement()
  nameWithType: HttpDigestClientElement.HttpDigestClientElement()
  fullName: System.ServiceModel.Configuration.HttpDigestClientElement.HttpDigestClientElement()
- uid: System.ServiceModel.Configuration.HttpDigestClientElement.Copy(System.ServiceModel.Configuration.HttpDigestClientElement)
  parent: System.ServiceModel.Configuration.HttpDigestClientElement
  isExternal: false
  name: Copy(HttpDigestClientElement)
  nameWithType: HttpDigestClientElement.Copy(HttpDigestClientElement)
  fullName: System.ServiceModel.Configuration.HttpDigestClientElement.Copy(HttpDigestClientElement)
- uid: System.ServiceModel.Configuration.HttpDigestClientElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: HttpDigestClientElement
  nameWithType: HttpDigestClientElement
  fullName: System.ServiceModel.Configuration.HttpDigestClientElement
- uid: System.ServiceModel.Configuration.HttpDigestClientElement.ImpersonationLevel
  parent: System.ServiceModel.Configuration.HttpDigestClientElement
  isExternal: false
  name: ImpersonationLevel
  nameWithType: HttpDigestClientElement.ImpersonationLevel
  fullName: System.ServiceModel.Configuration.HttpDigestClientElement.ImpersonationLevel
- uid: System.Security.Principal.TokenImpersonationLevel
  parent: System.Security.Principal
  isExternal: false
  name: TokenImpersonationLevel
  nameWithType: TokenImpersonationLevel
  fullName: System.Security.Principal.TokenImpersonationLevel
- uid: System.ServiceModel.Configuration.HttpDigestClientElement.Properties
  parent: System.ServiceModel.Configuration.HttpDigestClientElement
  isExternal: false
  name: Properties
  nameWithType: HttpDigestClientElement.Properties
  fullName: System.ServiceModel.Configuration.HttpDigestClientElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.HttpDigestClientElement.#ctor*
  parent: System.ServiceModel.Configuration.HttpDigestClientElement
  isExternal: false
  name: HttpDigestClientElement
  nameWithType: HttpDigestClientElement.HttpDigestClientElement
- uid: System.ServiceModel.Configuration.HttpDigestClientElement.Copy*
  parent: System.ServiceModel.Configuration.HttpDigestClientElement
  isExternal: false
  name: Copy
  nameWithType: HttpDigestClientElement.Copy
- uid: System.ServiceModel.Configuration.HttpDigestClientElement.ImpersonationLevel*
  parent: System.ServiceModel.Configuration.HttpDigestClientElement
  isExternal: false
  name: ImpersonationLevel
  nameWithType: HttpDigestClientElement.ImpersonationLevel
- uid: System.ServiceModel.Configuration.HttpDigestClientElement.Properties*
  parent: System.ServiceModel.Configuration.HttpDigestClientElement
  isExternal: false
  name: Properties
  nameWithType: HttpDigestClientElement.Properties
