### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.BindingElementExtensionElement
  id: BindingElementExtensionElement
  children:
  - System.ServiceModel.Configuration.BindingElementExtensionElement.#ctor
  - System.ServiceModel.Configuration.BindingElementExtensionElement.ApplyConfiguration(System.ServiceModel.Channels.BindingElement)
  - System.ServiceModel.Configuration.BindingElementExtensionElement.BindingElementType
  - System.ServiceModel.Configuration.BindingElementExtensionElement.CreateBindingElement
  - System.ServiceModel.Configuration.BindingElementExtensionElement.InitializeFrom(System.ServiceModel.Channels.BindingElement)
  langs:
  - csharp
  name: BindingElementExtensionElement
  nameWithType: BindingElementExtensionElement
  fullName: System.ServiceModel.Configuration.BindingElementExtensionElement
  type: Class
  summary: Enables the use of a custom <xref href="System.ServiceModel.Channels.BindingElement"></xref> implementation from a machine or application configuration file.
  remarks: "You should derive from the BindingElementExtensionElement class to use a custom <xref:System.ServiceModel.Channels.BindingElement> implementation from a machine or application configuration file.  \n  \n Once a BindingElementExtensionElement instance has been created, a custom binding element is returned. You can use this in an application configuration file by using the <`add`> element and setting the type attribute to the BindingElementExtensionElement class, and the name attribute to the custom binding element."
  syntax:
    content: 'public abstract class BindingElementExtensionElement : System.ServiceModel.Configuration.ServiceModelExtensionElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelExtensionElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.ConfigurationElementName
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.IsModified
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.Reset(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.ServiceModel.Configuration\BindingElementExtensionElement.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.ServiceModel.Configuration/BindingElementExtensionElement.xml
  version:
  - netframework-3.0
  - netframework-3.5-client
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.ServiceModel.Configuration.BindingElementExtensionElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.BindingElementExtensionElement
  langs:
  - csharp
  name: BindingElementExtensionElement()
  nameWithType: BindingElementExtensionElement.BindingElementExtensionElement()
  fullName: System.ServiceModel.Configuration.BindingElementExtensionElement.BindingElementExtensionElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.BindingElementExtensionElement"></xref> class.
  syntax:
    content: protected BindingElementExtensionElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.BindingElementExtensionElement.#ctor*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.ServiceModel.Configuration\BindingElementExtensionElement.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.ServiceModel.Configuration/BindingElementExtensionElement.xml
  version:
  - netframework-3.0
  - netframework-3.5-client
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.ServiceModel.Configuration.BindingElementExtensionElement.ApplyConfiguration(System.ServiceModel.Channels.BindingElement)
  id: ApplyConfiguration(System.ServiceModel.Channels.BindingElement)
  parent: System.ServiceModel.Configuration.BindingElementExtensionElement
  langs:
  - csharp
  name: ApplyConfiguration(BindingElement)
  nameWithType: BindingElementExtensionElement.ApplyConfiguration(BindingElement)
  fullName: System.ServiceModel.Configuration.BindingElementExtensionElement.ApplyConfiguration(BindingElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Applies the content of a specified binding element to this binding configuration element.
  syntax:
    content: public virtual void ApplyConfiguration (System.ServiceModel.Channels.BindingElement bindingElement);
    parameters:
    - id: bindingElement
      type: System.ServiceModel.Channels.BindingElement
      description: A binding element.
  overload: System.ServiceModel.Configuration.BindingElementExtensionElement.ApplyConfiguration*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: <code>bindingElement</code> is `null`.
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.ServiceModel.Configuration\BindingElementExtensionElement.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.ServiceModel.Configuration/BindingElementExtensionElement.xml
  version:
  - netframework-3.0
  - netframework-3.5-client
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.ServiceModel.Configuration.BindingElementExtensionElement.BindingElementType
  id: BindingElementType
  parent: System.ServiceModel.Configuration.BindingElementExtensionElement
  langs:
  - csharp
  name: BindingElementType
  nameWithType: BindingElementExtensionElement.BindingElementType
  fullName: System.ServiceModel.Configuration.BindingElementExtensionElement.BindingElementType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: When overridden in a derived class, gets the <xref href="System.Type"></xref> object that represents the custom binding element.
  remarks: Override and implement the BindingElementType property to return the type of the custom binding element this <xref:System.ServiceModel.Configuration.BindingElementExtensionElement> associates with the configuration system.
  syntax:
    content: public abstract Type BindingElementType { get; }
    return:
      type: System.Type
      description: A <xref href="System.Type"></xref> object that represents the custom binding type.
  overload: System.ServiceModel.Configuration.BindingElementExtensionElement.BindingElementType*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.ServiceModel.Configuration\BindingElementExtensionElement.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.ServiceModel.Configuration/BindingElementExtensionElement.xml
  version:
  - netframework-3.0
  - netframework-3.5-client
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.ServiceModel.Configuration.BindingElementExtensionElement.CreateBindingElement
  id: CreateBindingElement
  parent: System.ServiceModel.Configuration.BindingElementExtensionElement
  langs:
  - csharp
  name: CreateBindingElement()
  nameWithType: BindingElementExtensionElement.CreateBindingElement()
  fullName: System.ServiceModel.Configuration.BindingElementExtensionElement.CreateBindingElement()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: When overridden in a derived class, returns a custom binding element object.
  syntax:
    content: protected abstract System.ServiceModel.Channels.BindingElement CreateBindingElement ();
    parameters: []
    return:
      type: System.ServiceModel.Channels.BindingElement
      description: A custom <xref href="System.ServiceModel.Channels.BindingElement"></xref> object.
  overload: System.ServiceModel.Configuration.BindingElementExtensionElement.CreateBindingElement*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.ServiceModel.Configuration\BindingElementExtensionElement.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.ServiceModel.Configuration/BindingElementExtensionElement.xml
  version:
  - netframework-3.0
  - netframework-3.5-client
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.ServiceModel.Configuration.BindingElementExtensionElement.InitializeFrom(System.ServiceModel.Channels.BindingElement)
  id: InitializeFrom(System.ServiceModel.Channels.BindingElement)
  parent: System.ServiceModel.Configuration.BindingElementExtensionElement
  langs:
  - csharp
  name: InitializeFrom(BindingElement)
  nameWithType: BindingElementExtensionElement.InitializeFrom(BindingElement)
  fullName: System.ServiceModel.Configuration.BindingElementExtensionElement.InitializeFrom(BindingElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes this binding configuration section with the content of the specified binding element.
  syntax:
    content: protected virtual void InitializeFrom (System.ServiceModel.Channels.BindingElement bindingElement);
    parameters:
    - id: bindingElement
      type: System.ServiceModel.Channels.BindingElement
      description: A binding element.
  overload: System.ServiceModel.Configuration.BindingElementExtensionElement.InitializeFrom*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.ServiceModel.Configuration\BindingElementExtensionElement.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.ServiceModel.Configuration/BindingElementExtensionElement.xml
  version:
  - netframework-3.0
  - netframework-3.5-client
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
references:
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelExtensionElement
- uid: System.ArgumentNullException
  parent: System
  isExternal: false
  name: ArgumentNullException
  nameWithType: ArgumentNullException
  fullName: System.ArgumentNullException
- uid: System.ServiceModel.Configuration.BindingElementExtensionElement.#ctor
  parent: System.ServiceModel.Configuration.BindingElementExtensionElement
  isExternal: false
  name: BindingElementExtensionElement()
  nameWithType: BindingElementExtensionElement.BindingElementExtensionElement()
  fullName: System.ServiceModel.Configuration.BindingElementExtensionElement.BindingElementExtensionElement()
- uid: System.ServiceModel.Configuration.BindingElementExtensionElement.ApplyConfiguration(System.ServiceModel.Channels.BindingElement)
  parent: System.ServiceModel.Configuration.BindingElementExtensionElement
  isExternal: false
  name: ApplyConfiguration(BindingElement)
  nameWithType: BindingElementExtensionElement.ApplyConfiguration(BindingElement)
  fullName: System.ServiceModel.Configuration.BindingElementExtensionElement.ApplyConfiguration(BindingElement)
- uid: System.ServiceModel.Channels.BindingElement
  parent: System.ServiceModel.Channels
  isExternal: false
  name: BindingElement
  nameWithType: BindingElement
  fullName: System.ServiceModel.Channels.BindingElement
- uid: System.ServiceModel.Configuration.BindingElementExtensionElement.BindingElementType
  parent: System.ServiceModel.Configuration.BindingElementExtensionElement
  isExternal: false
  name: BindingElementType
  nameWithType: BindingElementExtensionElement.BindingElementType
  fullName: System.ServiceModel.Configuration.BindingElementExtensionElement.BindingElementType
- uid: System.Type
  parent: System
  isExternal: false
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ServiceModel.Configuration.BindingElementExtensionElement.CreateBindingElement
  parent: System.ServiceModel.Configuration.BindingElementExtensionElement
  isExternal: false
  name: CreateBindingElement()
  nameWithType: BindingElementExtensionElement.CreateBindingElement()
  fullName: System.ServiceModel.Configuration.BindingElementExtensionElement.CreateBindingElement()
- uid: System.ServiceModel.Configuration.BindingElementExtensionElement.InitializeFrom(System.ServiceModel.Channels.BindingElement)
  parent: System.ServiceModel.Configuration.BindingElementExtensionElement
  isExternal: false
  name: InitializeFrom(BindingElement)
  nameWithType: BindingElementExtensionElement.InitializeFrom(BindingElement)
  fullName: System.ServiceModel.Configuration.BindingElementExtensionElement.InitializeFrom(BindingElement)
- uid: System.ServiceModel.Configuration.BindingElementExtensionElement.#ctor*
  parent: System.ServiceModel.Configuration.BindingElementExtensionElement
  isExternal: false
  name: BindingElementExtensionElement
  nameWithType: BindingElementExtensionElement.BindingElementExtensionElement
- uid: System.ServiceModel.Configuration.BindingElementExtensionElement.ApplyConfiguration*
  parent: System.ServiceModel.Configuration.BindingElementExtensionElement
  isExternal: false
  name: ApplyConfiguration
  nameWithType: BindingElementExtensionElement.ApplyConfiguration
- uid: System.ServiceModel.Configuration.BindingElementExtensionElement.BindingElementType*
  parent: System.ServiceModel.Configuration.BindingElementExtensionElement
  isExternal: false
  name: BindingElementType
  nameWithType: BindingElementExtensionElement.BindingElementType
- uid: System.ServiceModel.Configuration.BindingElementExtensionElement.CreateBindingElement*
  parent: System.ServiceModel.Configuration.BindingElementExtensionElement
  isExternal: false
  name: CreateBindingElement
  nameWithType: BindingElementExtensionElement.CreateBindingElement
- uid: System.ServiceModel.Configuration.BindingElementExtensionElement.InitializeFrom*
  parent: System.ServiceModel.Configuration.BindingElementExtensionElement
  isExternal: false
  name: InitializeFrom
  nameWithType: BindingElementExtensionElement.InitializeFrom
