### YamlMime:ManagedReference
items:
- uid: System.Windows.Markup.DateTimeValueSerializer
  id: DateTimeValueSerializer
  children:
  - System.Windows.Markup.DateTimeValueSerializer.#ctor
  - System.Windows.Markup.DateTimeValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Markup.DateTimeValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Markup.DateTimeValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Markup.DateTimeValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  langs:
  - csharp
  name: DateTimeValueSerializer
  nameWithType: DateTimeValueSerializer
  fullName: System.Windows.Markup.DateTimeValueSerializer
  type: Class
  summary: Converts instances of <xref href="System.String"></xref> to and from instances of <xref href="System.DateTime"></xref>.
  remarks: "<xref:System.Windows.Markup.ValueSerializer> is used rather than <xref:System.ComponentModel.TypeConverter> for cases where type conversion requires additional state. DateTimeValueSerializer is not attributed to a type with <xref:System.Windows.Markup.ValueSerializerAttribute>. This is because <xref:System.DateTime> is in mscorlib, and mscorlib cannot take dependencies on attribute classes that it does not define itself. Instead, usage of DateTimeValueSerializer is special-cased into XAML processor behavior in .NET Framework XAML Services behavior.  \n  \n In previous versions of the .NET Framework, this class existed in the WPF-specific assembly WindowsBase. In [!INCLUDE[net_v40_long](~/add/includes/net-v40-long-md.md)], DateTimeValueSerializer is in the System.Xaml assembly. See [Types Migrated from WPF to System.Xaml](../Topic/Types%20Migrated%20from%20WPF%20to%20System.Xaml.md).  \n  \n<a name=\"xamlTextUsage_DateTimeValueSerializer\"></a>   \n## XAML Text Usage"
  syntax:
    content: >-
      [System.Runtime.CompilerServices.TypeForwardedFrom("WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35")]

      public class DateTimeValueSerializer : System.Windows.Markup.ValueSerializer
  inheritance:
  - System.Object
  - System.Windows.Markup.ValueSerializer
  implements: []
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.Windows.Markup.ValueSerializer.GetConvertFromException(System.Object)
  - System.Windows.Markup.ValueSerializer.GetConvertToException(System.Object,System.Type)
  - System.Windows.Markup.ValueSerializer.GetSerializerFor(System.ComponentModel.PropertyDescriptor)
  - System.Windows.Markup.ValueSerializer.GetSerializerFor(System.ComponentModel.PropertyDescriptor,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Markup.ValueSerializer.GetSerializerFor(System.Type)
  - System.Windows.Markup.ValueSerializer.GetSerializerFor(System.Type,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Markup.ValueSerializer.TypeReferences(System.Object,System.Windows.Markup.IValueSerializerContext)
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Windows.Markup\DateTimeValueSerializer.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Windows.Markup/DateTimeValueSerializer.xml
  version:
  - netframework-3.0
  - netframework-3.5-client
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.Windows.Markup.DateTimeValueSerializer.#ctor
  id: '#ctor'
  parent: System.Windows.Markup.DateTimeValueSerializer
  langs:
  - csharp
  name: DateTimeValueSerializer()
  nameWithType: DateTimeValueSerializer.DateTimeValueSerializer()
  fullName: System.Windows.Markup.DateTimeValueSerializer.DateTimeValueSerializer()
  type: Constructor
  assemblies:
  - WindowsBase
  - System.Xaml
  namespace: System.Windows.Markup
  summary: Initializes a new instance of the <xref href="System.Windows.Markup.DateTimeValueSerializer"></xref> class.
  syntax:
    content: public DateTimeValueSerializer ();
    parameters: []
  overload: System.Windows.Markup.DateTimeValueSerializer.#ctor*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Windows.Markup\DateTimeValueSerializer.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Windows.Markup/DateTimeValueSerializer.xml
  version:
  - netframework-3.0
  - netframework-3.5-client
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.Windows.Markup.DateTimeValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Markup.DateTimeValueSerializer
  langs:
  - csharp
  name: CanConvertFromString(String,IValueSerializerContext)
  nameWithType: DateTimeValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Markup.DateTimeValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  type: Method
  assemblies:
  - WindowsBase
  - System.Xaml
  namespace: System.Windows.Markup
  summary: Determines if the specified <xref href="System.String"></xref> can be convert to an instance of <xref href="System.DateTime"></xref>.
  remarks: This implementation always returns `true`.
  syntax:
    content: public override bool CanConvertFromString (string value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.String
      description: The string to evaluate for conversion.
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: Context information that is used for conversion.
    return:
      type: System.Boolean
      description: '`true` if the value can be converted; otherwise, `false`.'
  overload: System.Windows.Markup.DateTimeValueSerializer.CanConvertFromString*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Windows.Markup\DateTimeValueSerializer.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Windows.Markup/DateTimeValueSerializer.xml
  version:
  - netframework-3.0
  - netframework-3.5-client
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.Windows.Markup.DateTimeValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Markup.DateTimeValueSerializer
  langs:
  - csharp
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: DateTimeValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Markup.DateTimeValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - WindowsBase
  - System.Xaml
  namespace: System.Windows.Markup
  summary: Determines if the specified object can be converted to a <xref href="System.String"></xref>.
  remarks: This implementation returns `true` only if the passed `value` is of type <xref:System.DateTime>.
  syntax:
    content: public override bool CanConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: The object to evaluate for conversion.
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: Context information that is used for conversion.
    return:
      type: System.Boolean
      description: '`true` if <code>value</code> can be converted into a <xref href="System.String"></xref>; otherwise, `false`.'
  overload: System.Windows.Markup.DateTimeValueSerializer.CanConvertToString*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Windows.Markup\DateTimeValueSerializer.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Windows.Markup/DateTimeValueSerializer.xml
  version:
  - netframework-3.0
  - netframework-3.5-client
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.Windows.Markup.DateTimeValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  id: ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Markup.DateTimeValueSerializer
  langs:
  - csharp
  name: ConvertFromString(String,IValueSerializerContext)
  nameWithType: DateTimeValueSerializer.ConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Markup.DateTimeValueSerializer.ConvertFromString(String,IValueSerializerContext)
  type: Method
  assemblies:
  - WindowsBase
  - System.Xaml
  namespace: System.Windows.Markup
  summary: Converts a <xref href="System.String"></xref> into a <xref href="System.DateTime"></xref>.
  remarks: "An empty string returns <xref:System.DateTime.MinValue?displayProperty=fullName>.  \n  \n The current implementation uses <xref:System.DateTime.Parse%2A> internally, and also uses the following <xref:System.Globalization.DateTimeStyles>: `DateTimeStyles.RoundtripKind | DateTimeStyles.NoCurrentDateDefault | DateTimeStyles.AllowLeadingWhite | DateTimeStyles.AllowTrailingWhite`."
  syntax:
    content: public override object ConvertFromString (string value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.String
      description: The string to convert into a <xref href="System.DateTime"></xref>.
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: Context information that is used for conversion.
    return:
      type: System.Object
      description: A new instance of <xref href="System.DateTime"></xref> based on the supplied <code>value</code>.
  overload: System.Windows.Markup.DateTimeValueSerializer.ConvertFromString*
  exceptions:
  - type: System.NotSupportedException
    commentId: T:System.NotSupportedException
    description: <code>value</code> is `null`.
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Windows.Markup\DateTimeValueSerializer.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Windows.Markup/DateTimeValueSerializer.xml
  version:
  - netframework-3.0
  - netframework-3.5-client
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.Windows.Markup.DateTimeValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Markup.DateTimeValueSerializer
  langs:
  - csharp
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: DateTimeValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Markup.DateTimeValueSerializer.ConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - WindowsBase
  - System.Xaml
  namespace: System.Windows.Markup
  summary: Converts an instance of <xref href="System.DateTime"></xref> to a <xref href="System.String"></xref>.
  remarks: "`context` is not used by this implementation.  \n  \n String representations for dates as found in XAML value processing are based on the `en-US` culture. This is because XAML processing for culture-sensitive information is split conceptually between compile-time and run-time phases and must use a known string representation throughout. For more information, see [WPF Globalization and Localization Overview](../Topic/WPF%20Globalization%20and%20Localization%20Overview.md).  \n  \n The current implementation uses a format string that is adjusted depending on whether aspects of the supplied <xref:System.DateTime> have values. For example, if there is no value in <xref:System.TimeSpan.TotalSeconds%2A>, the format string is in the form `yyyy-MM-dd` rather than writing out full-verbosity zero values for the time component."
  syntax:
    content: public override string ConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: The object to convert into a string.
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: Context information that is used for conversion.
    return:
      type: System.String
      description: A string representation of the specified <xref href="System.DateTime"></xref>.
  overload: System.Windows.Markup.DateTimeValueSerializer.ConvertToString*
  exceptions:
  - type: System.NotSupportedException
    commentId: T:System.NotSupportedException
    description: <code>value</code> is not a <xref href="System.DateTime"></xref> or is `null`.
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Windows.Markup\DateTimeValueSerializer.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Windows.Markup/DateTimeValueSerializer.xml
  version:
  - netframework-3.0
  - netframework-3.5-client
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
references:
- uid: System.Windows.Markup.ValueSerializer
  isExternal: false
  name: System.Windows.Markup.ValueSerializer
- uid: System.NotSupportedException
  parent: System
  isExternal: false
  name: NotSupportedException
  nameWithType: NotSupportedException
  fullName: System.NotSupportedException
- uid: System.Windows.Markup.DateTimeValueSerializer.#ctor
  parent: System.Windows.Markup.DateTimeValueSerializer
  isExternal: false
  name: DateTimeValueSerializer()
  nameWithType: DateTimeValueSerializer.DateTimeValueSerializer()
  fullName: System.Windows.Markup.DateTimeValueSerializer.DateTimeValueSerializer()
- uid: System.Windows.Markup.DateTimeValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Markup.DateTimeValueSerializer
  isExternal: false
  name: CanConvertFromString(String,IValueSerializerContext)
  nameWithType: DateTimeValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Markup.DateTimeValueSerializer.CanConvertFromString(String,IValueSerializerContext)
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Windows.Markup.IValueSerializerContext
  parent: System.Windows.Markup
  isExternal: false
  name: IValueSerializerContext
  nameWithType: IValueSerializerContext
  fullName: System.Windows.Markup.IValueSerializerContext
- uid: System.Windows.Markup.DateTimeValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Markup.DateTimeValueSerializer
  isExternal: false
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: DateTimeValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Markup.DateTimeValueSerializer.CanConvertToString(Object,IValueSerializerContext)
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Windows.Markup.DateTimeValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Markup.DateTimeValueSerializer
  isExternal: false
  name: ConvertFromString(String,IValueSerializerContext)
  nameWithType: DateTimeValueSerializer.ConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Markup.DateTimeValueSerializer.ConvertFromString(String,IValueSerializerContext)
- uid: System.Windows.Markup.DateTimeValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Markup.DateTimeValueSerializer
  isExternal: false
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: DateTimeValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Markup.DateTimeValueSerializer.ConvertToString(Object,IValueSerializerContext)
- uid: System.Windows.Markup.DateTimeValueSerializer.#ctor*
  parent: System.Windows.Markup.DateTimeValueSerializer
  isExternal: false
  name: DateTimeValueSerializer
  nameWithType: DateTimeValueSerializer.DateTimeValueSerializer
- uid: System.Windows.Markup.DateTimeValueSerializer.CanConvertFromString*
  parent: System.Windows.Markup.DateTimeValueSerializer
  isExternal: false
  name: CanConvertFromString
  nameWithType: DateTimeValueSerializer.CanConvertFromString
- uid: System.Windows.Markup.DateTimeValueSerializer.CanConvertToString*
  parent: System.Windows.Markup.DateTimeValueSerializer
  isExternal: false
  name: CanConvertToString
  nameWithType: DateTimeValueSerializer.CanConvertToString
- uid: System.Windows.Markup.DateTimeValueSerializer.ConvertFromString*
  parent: System.Windows.Markup.DateTimeValueSerializer
  isExternal: false
  name: ConvertFromString
  nameWithType: DateTimeValueSerializer.ConvertFromString
- uid: System.Windows.Markup.DateTimeValueSerializer.ConvertToString*
  parent: System.Windows.Markup.DateTimeValueSerializer
  isExternal: false
  name: ConvertToString
  nameWithType: DateTimeValueSerializer.ConvertToString
