### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.CompatibleFramework
  id: CompatibleFramework
  children:
  - System.Deployment.Application.CompatibleFramework.Profile
  - System.Deployment.Application.CompatibleFramework.SupportedRuntime
  - System.Deployment.Application.CompatibleFramework.TargetVersion
  langs:
  - csharp
  name: CompatibleFramework
  nameWithType: CompatibleFramework
  fullName: System.Deployment.Application.CompatibleFramework
  type: Class
  summary: Represents a version of the .NET Framework where an application can install and run.
  syntax:
    content: public class CompatibleFramework
  inheritance:
  - System.Object
  implements: []
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Deployment.Application\CompatibleFramework.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Deployment.Application/CompatibleFramework.xml
  version:
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.Deployment.Application.CompatibleFramework.Profile
  id: Profile
  parent: System.Deployment.Application.CompatibleFramework
  langs:
  - csharp
  name: Profile
  nameWithType: CompatibleFramework.Profile
  fullName: System.Deployment.Application.CompatibleFramework.Profile
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: Specifies the profile of the .NET Framework version where an application can install and run.
  remarks: If the .NET Framework version is [!INCLUDE[net_client_v40_long](~/add/includes/net-client-v40-long-md.md)], the Profile property returns "Client". If the .NET Framework version is [!INCLUDE[net_v40_long](~/add/includes/net-v40-long-md.md)], the Profile property returns "Full".
  syntax:
    content: public string Profile { get; }
    return:
      type: System.String
      description: A string that represents the profile.
  overload: System.Deployment.Application.CompatibleFramework.Profile*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Deployment.Application\CompatibleFramework.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Deployment.Application/CompatibleFramework.xml
  version:
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.Deployment.Application.CompatibleFramework.SupportedRuntime
  id: SupportedRuntime
  parent: System.Deployment.Application.CompatibleFramework
  langs:
  - csharp
  name: SupportedRuntime
  nameWithType: CompatibleFramework.SupportedRuntime
  fullName: System.Deployment.Application.CompatibleFramework.SupportedRuntime
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: Specifies the runtime version number of the .NET Framework where an application can install and run.
  remarks: New versions of the .NET Framework may operate on previously-released versions of the runtime.
  syntax:
    content: public string SupportedRuntime { get; }
    return:
      type: System.String
      description: A string that represents the runtime version.
  overload: System.Deployment.Application.CompatibleFramework.SupportedRuntime*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Deployment.Application\CompatibleFramework.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Deployment.Application/CompatibleFramework.xml
  version:
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.Deployment.Application.CompatibleFramework.TargetVersion
  id: TargetVersion
  parent: System.Deployment.Application.CompatibleFramework
  langs:
  - csharp
  name: TargetVersion
  nameWithType: CompatibleFramework.TargetVersion
  fullName: System.Deployment.Application.CompatibleFramework.TargetVersion
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: Specifies the version of the .NET Framework where an application can install and run.
  syntax:
    content: public string TargetVersion { get; }
    return:
      type: System.String
      description: A string that represents the version.
  overload: System.Deployment.Application.CompatibleFramework.TargetVersion*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Deployment.Application\CompatibleFramework.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Deployment.Application/CompatibleFramework.xml
  version:
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Deployment.Application.CompatibleFramework.Profile
  parent: System.Deployment.Application.CompatibleFramework
  isExternal: false
  name: Profile
  nameWithType: CompatibleFramework.Profile
  fullName: System.Deployment.Application.CompatibleFramework.Profile
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.CompatibleFramework.SupportedRuntime
  parent: System.Deployment.Application.CompatibleFramework
  isExternal: false
  name: SupportedRuntime
  nameWithType: CompatibleFramework.SupportedRuntime
  fullName: System.Deployment.Application.CompatibleFramework.SupportedRuntime
- uid: System.Deployment.Application.CompatibleFramework.TargetVersion
  parent: System.Deployment.Application.CompatibleFramework
  isExternal: false
  name: TargetVersion
  nameWithType: CompatibleFramework.TargetVersion
  fullName: System.Deployment.Application.CompatibleFramework.TargetVersion
- uid: System.Deployment.Application.CompatibleFramework.Profile*
  parent: System.Deployment.Application.CompatibleFramework
  isExternal: false
  name: Profile
  nameWithType: CompatibleFramework.Profile
- uid: System.Deployment.Application.CompatibleFramework.SupportedRuntime*
  parent: System.Deployment.Application.CompatibleFramework
  isExternal: false
  name: SupportedRuntime
  nameWithType: CompatibleFramework.SupportedRuntime
- uid: System.Deployment.Application.CompatibleFramework.TargetVersion*
  parent: System.Deployment.Application.CompatibleFramework
  isExternal: false
  name: TargetVersion
  nameWithType: CompatibleFramework.TargetVersion
