### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.ServiceMetadataEndpointCollectionElement
  id: ServiceMetadataEndpointCollectionElement
  children:
  - System.ServiceModel.Configuration.ServiceMetadataEndpointCollectionElement.#ctor
  langs:
  - csharp
  name: ServiceMetadataEndpointCollectionElement
  nameWithType: ServiceMetadataEndpointCollectionElement
  fullName: System.ServiceModel.Configuration.ServiceMetadataEndpointCollectionElement
  type: Class
  summary: Represents a collection element in a service configuration file that contains <xref href="System.ServiceModel.Description.ServiceMetadataEndpoint"></xref> objects.
  syntax:
    content: 'public class ServiceMetadataEndpointCollectionElement : System.ServiceModel.Configuration.StandardEndpointCollectionElement<System.ServiceModel.Description.ServiceMetadataEndpoint,System.ServiceModel.Configuration.ServiceMetadataEndpointElement>'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.EndpointCollectionElement
  - System.ServiceModel.Configuration.StandardEndpointCollectionElement`2
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.ServiceModel.Configuration.EndpointCollectionElement.EndpointName
  - System.ServiceModel.Configuration.StandardEndpointCollectionElement`2.ConfiguredEndpoints
  - System.ServiceModel.Configuration.StandardEndpointCollectionElement`2.ContainsKey(System.String)
  - System.ServiceModel.Configuration.StandardEndpointCollectionElement`2.Endpoints
  - System.ServiceModel.Configuration.StandardEndpointCollectionElement`2.EndpointType
  - System.ServiceModel.Configuration.StandardEndpointCollectionElement`2.GetDefaultStandardEndpointElement
  - System.ServiceModel.Configuration.StandardEndpointCollectionElement`2.Properties
  - System.ServiceModel.Configuration.StandardEndpointCollectionElement`2.TryAdd(System.String,System.ServiceModel.Description.ServiceEndpoint,System.Configuration.Configuration)
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.ServiceModel.Configuration\ServiceMetadataEndpointCollectionElement.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.ServiceModel.Configuration/ServiceMetadataEndpointCollectionElement.xml
  version:
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.ServiceModel.Configuration.ServiceMetadataEndpointCollectionElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.ServiceMetadataEndpointCollectionElement
  langs:
  - csharp
  name: ServiceMetadataEndpointCollectionElement()
  nameWithType: ServiceMetadataEndpointCollectionElement.ServiceMetadataEndpointCollectionElement()
  fullName: System.ServiceModel.Configuration.ServiceMetadataEndpointCollectionElement.ServiceMetadataEndpointCollectionElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Creates a new instance of the<xref href="System.ServiceModel.Configuration.ServiceMetadataEndpointCollectionElement"></xref> class.
  syntax:
    content: public ServiceMetadataEndpointCollectionElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.ServiceMetadataEndpointCollectionElement.#ctor*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.ServiceModel.Configuration\ServiceMetadataEndpointCollectionElement.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.ServiceModel.Configuration/ServiceMetadataEndpointCollectionElement.xml
  version:
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
references:
- uid: System.ServiceModel.Configuration.StandardEndpointCollectionElement`2
  isExternal: false
  name: System.ServiceModel.Configuration.StandardEndpointCollectionElement<System.ServiceModel.Description.ServiceMetadataEndpoint,System.ServiceModel.Configuration.ServiceMetadataEndpointElement>
- uid: System.ServiceModel.Configuration.ServiceMetadataEndpointCollectionElement.#ctor
  parent: System.ServiceModel.Configuration.ServiceMetadataEndpointCollectionElement
  isExternal: false
  name: ServiceMetadataEndpointCollectionElement()
  nameWithType: ServiceMetadataEndpointCollectionElement.ServiceMetadataEndpointCollectionElement()
  fullName: System.ServiceModel.Configuration.ServiceMetadataEndpointCollectionElement.ServiceMetadataEndpointCollectionElement()
- uid: System.ServiceModel.Configuration.ServiceMetadataEndpointCollectionElement.#ctor*
  parent: System.ServiceModel.Configuration.ServiceMetadataEndpointCollectionElement
  isExternal: false
  name: ServiceMetadataEndpointCollectionElement
  nameWithType: ServiceMetadataEndpointCollectionElement.ServiceMetadataEndpointCollectionElement
