### YamlMime:ManagedReference
items:
- uid: System.Configuration.StringValidatorAttribute
  id: StringValidatorAttribute
  children:
  - System.Configuration.StringValidatorAttribute.#ctor
  - System.Configuration.StringValidatorAttribute.InvalidCharacters
  - System.Configuration.StringValidatorAttribute.MaxLength
  - System.Configuration.StringValidatorAttribute.MinLength
  - System.Configuration.StringValidatorAttribute.ValidatorInstance
  langs:
  - csharp
  name: StringValidatorAttribute
  nameWithType: StringValidatorAttribute
  fullName: System.Configuration.StringValidatorAttribute
  type: Class
  summary: Declaratively instructs the .NET Framework to perform string validation on a configuration property. This class cannot be inherited.
  remarks: "You use the StringValidatorAttribute to decorate a configuration property. This is to instruct the .NET Framework to validate the property using the <xref:System.Configuration.StringValidator> and pass to it the value of the decorating parameters.  \n  \n You can apply StringValidatorAttribute objects to property types only."
  example:
  - "The following example shows how to decorate the properties of a custom <xref:System.Configuration.ConfigurationSection> object using the StringValidatorAttribute object.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#2](~/add/codesnippet/visualbasic/t-system.configuration.s_1_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#2](~/add/codesnippet/csharp/t-system.configuration.s_1_1.cs)]"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class StringValidatorAttribute : System.Configuration.ConfigurationValidatorAttribute
  inheritance:
  - System.Object
  - System.Attribute
  - System.Configuration.ConfigurationValidatorAttribute
  implements: []
  inheritedMembers:
  - System.Attribute.Equals(System.Object)
  - System.Attribute.GetCustomAttribute(System.Reflection.Assembly,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.Module,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.GetHashCode
  - System.Attribute.IsDefaultAttribute
  - System.Attribute.IsDefined(System.Reflection.Assembly,System.Type)
  - System.Attribute.IsDefined(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.IsDefined(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.Module,System.Type)
  - System.Attribute.IsDefined(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.IsDefined(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.Match(System.Object)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetIDsOfNames(System.Guid@,System.IntPtr,System.UInt32,System.UInt32,System.IntPtr)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetTypeInfo(System.UInt32,System.UInt32,System.IntPtr)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetTypeInfoCount(System.UInt32@)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#Invoke(System.UInt32,System.Guid@,System.UInt32,System.Int16,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr)
  - System.Attribute.TypeId
  - System.Configuration.ConfigurationValidatorAttribute.ValidatorType
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  platform:
  - netframework-2.0
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
- uid: System.Configuration.StringValidatorAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.StringValidatorAttribute
  langs:
  - csharp
  name: StringValidatorAttribute()
  nameWithType: StringValidatorAttribute.StringValidatorAttribute()
  fullName: System.Configuration.StringValidatorAttribute.StringValidatorAttribute()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Initializes a new instance of the <xref href="System.Configuration.StringValidatorAttribute"></xref> class.
  remarks: You use this constructor in the attributed model to ensure that the value assigned to the configuration-element property is of a string type.
  example:
  - "The following example shows how to use the StringValidatorAttribute constructor.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#3](~/add/codesnippet/visualbasic/m-system.configuration.s_2_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#3](~/add/codesnippet/csharp/m-system.configuration.s_2_1.cs)]"
  syntax:
    content: public StringValidatorAttribute ();
    parameters: []
  overload: System.Configuration.StringValidatorAttribute.#ctor*
  exceptions: []
  platform:
  - netframework-2.0
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
- uid: System.Configuration.StringValidatorAttribute.InvalidCharacters
  id: InvalidCharacters
  parent: System.Configuration.StringValidatorAttribute
  langs:
  - csharp
  name: InvalidCharacters
  nameWithType: StringValidatorAttribute.InvalidCharacters
  fullName: System.Configuration.StringValidatorAttribute.InvalidCharacters
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Gets or sets the invalid characters for the property.
  remarks: ''
  example:
  - "The following example shows how to use the InvalidCharacters property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#2](~/add/codesnippet/visualbasic/p-system.configuration.s_15_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#2](~/add/codesnippet/csharp/p-system.configuration.s_15_1.cs)]"
  syntax:
    content: public string InvalidCharacters { get; set; }
    return:
      type: System.String
      description: The string that contains the set of characters that are not allowed for the property.
  overload: System.Configuration.StringValidatorAttribute.InvalidCharacters*
  exceptions: []
  platform:
  - netframework-2.0
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
- uid: System.Configuration.StringValidatorAttribute.MaxLength
  id: MaxLength
  parent: System.Configuration.StringValidatorAttribute
  langs:
  - csharp
  name: MaxLength
  nameWithType: StringValidatorAttribute.MaxLength
  fullName: System.Configuration.StringValidatorAttribute.MaxLength
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Gets or sets the maximum length allowed for the string to assign to the property.
  remarks: ''
  example:
  - "The following example shows how to use the MaxLength property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#2](~/add/codesnippet/visualbasic/p-system.configuration.s_8_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#2](~/add/codesnippet/csharp/p-system.configuration.s_8_1.cs)]"
  syntax:
    content: public int MaxLength { get; set; }
    return:
      type: System.Int32
      description: An integer that indicates the maximum allowed length for the string to assign to the property.
  overload: System.Configuration.StringValidatorAttribute.MaxLength*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: The selected value is less than <xref:System.Configuration.StringValidatorAttribute.MinLength*>.
  platform:
  - netframework-2.0
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
- uid: System.Configuration.StringValidatorAttribute.MinLength
  id: MinLength
  parent: System.Configuration.StringValidatorAttribute
  langs:
  - csharp
  name: MinLength
  nameWithType: StringValidatorAttribute.MinLength
  fullName: System.Configuration.StringValidatorAttribute.MinLength
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Gets or sets the minimum allowed value for the string to assign to the property.
  remarks: ''
  example:
  - "The following example shows how to use the MinLength property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#2](~/add/codesnippet/visualbasic/p-system.configuration.s_12_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#2](~/add/codesnippet/csharp/p-system.configuration.s_12_1.cs)]"
  syntax:
    content: public int MinLength { get; set; }
    return:
      type: System.Int32
      description: An integer that indicates the allowed minimum length for the string to assign to the property.
  overload: System.Configuration.StringValidatorAttribute.MinLength*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: The selected value is greater than <xref:System.Configuration.StringValidatorAttribute.MaxLength*>.
  platform:
  - netframework-2.0
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
- uid: System.Configuration.StringValidatorAttribute.ValidatorInstance
  id: ValidatorInstance
  parent: System.Configuration.StringValidatorAttribute
  langs:
  - csharp
  name: ValidatorInstance
  nameWithType: StringValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.StringValidatorAttribute.ValidatorInstance
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Gets an instance of the <xref href="System.Configuration.StringValidator"></xref> class.
  remarks: You use the ValidatorInstance property to perform string validation by calling its <xref:System.Configuration.StringValidator.Validate%2A> method.
  example:
  - "The following example shows how to use the ValidatorInstance property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#14](~/add/codesnippet/visualbasic/p-system.configuration.s_4_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#14](~/add/codesnippet/csharp/p-system.configuration.s_4_1.cs)]"
  syntax:
    content: public override System.Configuration.ConfigurationValidatorBase ValidatorInstance { get; }
    return:
      type: System.Configuration.ConfigurationValidatorBase
      description: A current <xref href="System.Configuration.StringValidator"></xref> settings in a <xref href="System.Configuration.ConfigurationValidatorBase"></xref> validator instance.
  overload: System.Configuration.StringValidatorAttribute.ValidatorInstance*
  exceptions: []
  platform:
  - netframework-2.0
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
references:
- uid: System.Configuration.ConfigurationValidatorAttribute
  isExternal: false
  name: System.Configuration.ConfigurationValidatorAttribute
- uid: System.ArgumentOutOfRangeException
  parent: System
  isExternal: false
  name: ArgumentOutOfRangeException
  nameWithType: ArgumentOutOfRangeException
  fullName: System.ArgumentOutOfRangeException
- uid: System.Configuration.StringValidatorAttribute.#ctor
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: StringValidatorAttribute()
  nameWithType: StringValidatorAttribute.StringValidatorAttribute()
  fullName: System.Configuration.StringValidatorAttribute.StringValidatorAttribute()
- uid: System.Configuration.StringValidatorAttribute.InvalidCharacters
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: InvalidCharacters
  nameWithType: StringValidatorAttribute.InvalidCharacters
  fullName: System.Configuration.StringValidatorAttribute.InvalidCharacters
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.StringValidatorAttribute.MaxLength
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: MaxLength
  nameWithType: StringValidatorAttribute.MaxLength
  fullName: System.Configuration.StringValidatorAttribute.MaxLength
- uid: System.Int32
  parent: System
  isExternal: false
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Configuration.StringValidatorAttribute.MinLength
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: MinLength
  nameWithType: StringValidatorAttribute.MinLength
  fullName: System.Configuration.StringValidatorAttribute.MinLength
- uid: System.Configuration.StringValidatorAttribute.ValidatorInstance
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: StringValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.StringValidatorAttribute.ValidatorInstance
- uid: System.Configuration.ConfigurationValidatorBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.StringValidatorAttribute.#ctor*
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: StringValidatorAttribute
  nameWithType: StringValidatorAttribute.StringValidatorAttribute
- uid: System.Configuration.StringValidatorAttribute.InvalidCharacters*
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: InvalidCharacters
  nameWithType: StringValidatorAttribute.InvalidCharacters
- uid: System.Configuration.StringValidatorAttribute.MaxLength*
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: MaxLength
  nameWithType: StringValidatorAttribute.MaxLength
- uid: System.Configuration.StringValidatorAttribute.MinLength*
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: MinLength
  nameWithType: StringValidatorAttribute.MinLength
- uid: System.Configuration.StringValidatorAttribute.ValidatorInstance*
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: StringValidatorAttribute.ValidatorInstance
