### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.DelegatingHandlerElement
  id: DelegatingHandlerElement
  children:
  - System.ServiceModel.Configuration.DelegatingHandlerElement.#ctor
  - System.ServiceModel.Configuration.DelegatingHandlerElement.Properties
  - System.ServiceModel.Configuration.DelegatingHandlerElement.Type
  langs:
  - csharp
  name: DelegatingHandlerElement
  nameWithType: DelegatingHandlerElement
  fullName: System.ServiceModel.Configuration.DelegatingHandlerElement
  type: Class
  summary: Represents a delegating handler element.
  syntax:
    content: 'public sealed class DelegatingHandlerElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.ServiceModel.Configuration\DelegatingHandlerElement.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.ServiceModel.Configuration/DelegatingHandlerElement.xml
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.ServiceModel.Configuration.DelegatingHandlerElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.DelegatingHandlerElement
  langs:
  - csharp
  name: DelegatingHandlerElement()
  nameWithType: DelegatingHandlerElement.DelegatingHandlerElement()
  fullName: System.ServiceModel.Configuration.DelegatingHandlerElement.DelegatingHandlerElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.DelegatingHandlerElement"></xref> class.
  syntax:
    content: public DelegatingHandlerElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.DelegatingHandlerElement.#ctor*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.ServiceModel.Configuration\DelegatingHandlerElement.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.ServiceModel.Configuration/DelegatingHandlerElement.xml
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.ServiceModel.Configuration.DelegatingHandlerElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.DelegatingHandlerElement
  langs:
  - csharp
  name: Properties
  nameWithType: DelegatingHandlerElement.Properties
  fullName: System.ServiceModel.Configuration.DelegatingHandlerElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.ServiceModel.Configuration.DelegatingHandlerElement.Properties*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.ServiceModel.Configuration\DelegatingHandlerElement.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.ServiceModel.Configuration/DelegatingHandlerElement.xml
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.ServiceModel.Configuration.DelegatingHandlerElement.Type
  id: Type
  parent: System.ServiceModel.Configuration.DelegatingHandlerElement
  langs:
  - csharp
  name: Type
  nameWithType: DelegatingHandlerElement.Type
  fullName: System.ServiceModel.Configuration.DelegatingHandlerElement.Type
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets or sets the type of the handler element.
  syntax:
    content: public string Type { get; set; }
    return:
      type: System.String
      description: To be added.
  overload: System.ServiceModel.Configuration.DelegatingHandlerElement.Type*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.ServiceModel.Configuration\DelegatingHandlerElement.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.ServiceModel.Configuration/DelegatingHandlerElement.xml
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.DelegatingHandlerElement.#ctor
  parent: System.ServiceModel.Configuration.DelegatingHandlerElement
  isExternal: false
  name: DelegatingHandlerElement()
  nameWithType: DelegatingHandlerElement.DelegatingHandlerElement()
  fullName: System.ServiceModel.Configuration.DelegatingHandlerElement.DelegatingHandlerElement()
- uid: System.ServiceModel.Configuration.DelegatingHandlerElement.Properties
  parent: System.ServiceModel.Configuration.DelegatingHandlerElement
  isExternal: false
  name: Properties
  nameWithType: DelegatingHandlerElement.Properties
  fullName: System.ServiceModel.Configuration.DelegatingHandlerElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.DelegatingHandlerElement.Type
  parent: System.ServiceModel.Configuration.DelegatingHandlerElement
  isExternal: false
  name: Type
  nameWithType: DelegatingHandlerElement.Type
  fullName: System.ServiceModel.Configuration.DelegatingHandlerElement.Type
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.DelegatingHandlerElement.#ctor*
  parent: System.ServiceModel.Configuration.DelegatingHandlerElement
  isExternal: false
  name: DelegatingHandlerElement
  nameWithType: DelegatingHandlerElement.DelegatingHandlerElement
- uid: System.ServiceModel.Configuration.DelegatingHandlerElement.Properties*
  parent: System.ServiceModel.Configuration.DelegatingHandlerElement
  isExternal: false
  name: Properties
  nameWithType: DelegatingHandlerElement.Properties
- uid: System.ServiceModel.Configuration.DelegatingHandlerElement.Type*
  parent: System.ServiceModel.Configuration.DelegatingHandlerElement
  isExternal: false
  name: Type
  nameWithType: DelegatingHandlerElement.Type
