### YamlMime:ManagedReference
items:
- uid: System.Activities.WorkflowApplicationIdleEventArgs
  id: WorkflowApplicationIdleEventArgs
  children:
  - System.Activities.WorkflowApplicationIdleEventArgs.Bookmarks
  langs:
  - csharp
  name: WorkflowApplicationIdleEventArgs
  nameWithType: WorkflowApplicationIdleEventArgs
  fullName: System.Activities.WorkflowApplicationIdleEventArgs
  type: Class
  summary: Holds information about the workflow instance that has become idle.
  remarks: ''
  example:
  - "The following code example inspects the WorkflowApplicationIdleEventArgs passed into the <xref:System.Activities.WorkflowApplication.Idle%2A> handler of a <xref:System.Activities.WorkflowApplication> instance. In this example the workflow going idle has one <xref:System.Activities.Bookmark> with a name of `EnterGuess`, owned by an activity named `ReadInt`. This code example is based off of [How to: Run a Workflow](../Topic/How%20to:%20Run%20a%20Workflow.md), which is part of the [Getting Started Tutorial &#91;.NET Framework 4.5&#93;](../Topic/Getting%20Started%20Tutorial2.md). If the <xref:System.Activities.WorkflowApplication.Idle%2A> handler in that step is modified to contain the code from this example, the following output is displayed.  \n  \n```Output  \nBookmarkName: EnterGuess - OwnerDisplayName: ReadInt  \n```  \n  \n [!code-cs[CFX_WorkflowApplicationExample#2](~/add/codesnippet/csharp/t-system.activities.work_3_1.cs)]"
  syntax:
    content: 'public class WorkflowApplicationIdleEventArgs : System.Activities.WorkflowApplicationEventArgs'
  inheritance:
  - System.Object
  - System.EventArgs
  - System.Activities.WorkflowApplicationEventArgs
  implements: []
  inheritedMembers:
  - System.Activities.WorkflowApplicationEventArgs.GetInstanceExtensions``1
  - System.Activities.WorkflowApplicationEventArgs.InstanceId
  - System.EventArgs.Empty
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Activities\WorkflowApplicationIdleEventArgs.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Activities/WorkflowApplicationIdleEventArgs.xml
  version:
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.Activities.WorkflowApplicationIdleEventArgs.Bookmarks
  id: Bookmarks
  parent: System.Activities.WorkflowApplicationIdleEventArgs
  langs:
  - csharp
  name: Bookmarks
  nameWithType: WorkflowApplicationIdleEventArgs.Bookmarks
  fullName: System.Activities.WorkflowApplicationIdleEventArgs.Bookmarks
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: Gets the read-only collection of bookmarks for the workflow instance.
  remarks: ''
  example:
  - "The following code example inspects the <xref:System.Activities.WorkflowApplicationIdleEventArgs> passed into the <xref:System.Activities.WorkflowApplication.Idle%2A> handler of a <xref:System.Activities.WorkflowApplication> instance. In this example the workflow going idle has one <xref:System.Activities.Bookmark> with a name of `EnterGuess`, owned by an activity named `ReadInt`. This code example is based off of [How to: Run a Workflow](../Topic/How%20to:%20Run%20a%20Workflow.md), which is part of the [Getting Started Tutorial &#91;.NET Framework 4.5&#93;](../Topic/Getting%20Started%20Tutorial2.md). If the <xref:System.Activities.WorkflowApplication.Idle%2A> handler in that step is modified to contain the code from this example, the following output is displayed.  \n  \n```Output  \nBookmarkName: EnterGuess - OwnerDisplayName: ReadInt  \n```  \n  \n [!code-cs[CFX_WorkflowApplicationExample#2](~/add/codesnippet/csharp/p-system.activities.work_1_1.cs)]"
  syntax:
    content: public System.Collections.ObjectModel.ReadOnlyCollection<System.Activities.Hosting.BookmarkInfo> Bookmarks { get; }
    return:
      type: System.Collections.ObjectModel.ReadOnlyCollection{System.Activities.Hosting.BookmarkInfo}
      description: A read-only collection of bookmarks.
  overload: System.Activities.WorkflowApplicationIdleEventArgs.Bookmarks*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Activities\WorkflowApplicationIdleEventArgs.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Activities/WorkflowApplicationIdleEventArgs.xml
  version:
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
references:
- uid: System.Activities.WorkflowApplicationEventArgs
  isExternal: false
  name: System.Activities.WorkflowApplicationEventArgs
- uid: System.Activities.WorkflowApplicationIdleEventArgs.Bookmarks
  parent: System.Activities.WorkflowApplicationIdleEventArgs
  isExternal: false
  name: Bookmarks
  nameWithType: WorkflowApplicationIdleEventArgs.Bookmarks
  fullName: System.Activities.WorkflowApplicationIdleEventArgs.Bookmarks
- uid: System.Collections.ObjectModel.ReadOnlyCollection{System.Activities.Hosting.BookmarkInfo}
  parent: System.Collections.ObjectModel
  isExternal: false
  name: ReadOnlyCollection<BookmarkInfo>
  nameWithType: ReadOnlyCollection<BookmarkInfo>
  fullName: System.Collections.ObjectModel.ReadOnlyCollection<System.Activities.Hosting.BookmarkInfo>
  spec.csharp:
  - uid: System.Collections.ObjectModel.ReadOnlyCollection`1
    name: ReadOnlyCollection
    nameWithType: ReadOnlyCollection
    fullName: ReadOnlyCollection<System.Activities.Hosting.BookmarkInfo>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Activities.Hosting.BookmarkInfo
    name: BookmarkInfo
    nameWithType: BookmarkInfo
    fullName: BookmarkInfo
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.Activities.WorkflowApplicationIdleEventArgs.Bookmarks*
  parent: System.Activities.WorkflowApplicationIdleEventArgs
  isExternal: false
  name: Bookmarks
  nameWithType: WorkflowApplicationIdleEventArgs.Bookmarks
