### YamlMime:ManagedReference
items:
- uid: System.Security.Permissions.EnvironmentPermissionAttribute
  id: EnvironmentPermissionAttribute
  children:
  - System.Security.Permissions.EnvironmentPermissionAttribute.#ctor(System.Security.Permissions.SecurityAction)
  - System.Security.Permissions.EnvironmentPermissionAttribute.All
  - System.Security.Permissions.EnvironmentPermissionAttribute.CreatePermission
  - System.Security.Permissions.EnvironmentPermissionAttribute.Read
  - System.Security.Permissions.EnvironmentPermissionAttribute.Write
  langs:
  - csharp
  name: EnvironmentPermissionAttribute
  nameWithType: EnvironmentPermissionAttribute
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute
  type: Class
  summary: Allows security actions for <xref href="System.Security.Permissions.EnvironmentPermission"></xref> to be applied to code using declarative security. This class cannot be inherited.
  remarks: "The scope of the declaration that is allowed depends on the <xref:System.Security.Permissions.SecurityAction> that is used.  \n  \n The security information declared by a security attribute is stored in the metadata of the attribute target and is accessed by the system at run time. Security attributes are used only for declarative security. For imperative security, use the corresponding permission class.  \n  \n Environment variable names are case-insensitive. Multiple environment variable names are specified by separating the names using <xref:System.IO.Path.PathSeparator>."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Assembly | System.AttributeTargets.Class | System.AttributeTargets.Struct | System.AttributeTargets.Constructor | System.AttributeTargets.Method, AllowMultiple=true, Inherited=false)]

      [System.Runtime.InteropServices.ComVisible(true)]

      public sealed class EnvironmentPermissionAttribute : System.Security.Permissions.CodeAccessSecurityAttribute
  inheritance:
  - System.Object
  - System.Attribute
  - System.Security.Permissions.SecurityAttribute
  - System.Security.Permissions.CodeAccessSecurityAttribute
  implements: []
  inheritedMembers:
  - System.Attribute.Equals(System.Object)
  - System.Attribute.GetCustomAttribute(System.Reflection.Assembly,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.Module,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.GetHashCode
  - System.Attribute.IsDefaultAttribute
  - System.Attribute.IsDefined(System.Reflection.Assembly,System.Type)
  - System.Attribute.IsDefined(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.IsDefined(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.Module,System.Type)
  - System.Attribute.IsDefined(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.IsDefined(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.Match(System.Object)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetIDsOfNames(System.Guid@,System.IntPtr,System.UInt32,System.UInt32,System.IntPtr)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetTypeInfo(System.UInt32,System.UInt32,System.IntPtr)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetTypeInfoCount(System.UInt32@)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#Invoke(System.UInt32,System.Guid@,System.UInt32,System.Int16,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr)
  - System.Attribute.TypeId
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.Security.Permissions.SecurityAttribute.Action
  - System.Security.Permissions.SecurityAttribute.Unrestricted
  platform:
  - netframework-2.0
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.#ctor(System.Security.Permissions.SecurityAction)
  id: '#ctor(System.Security.Permissions.SecurityAction)'
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  langs:
  - csharp
  name: EnvironmentPermissionAttribute(SecurityAction)
  nameWithType: EnvironmentPermissionAttribute.EnvironmentPermissionAttribute(SecurityAction)
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.EnvironmentPermissionAttribute(SecurityAction)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  summary: Initializes a new instance of the <xref href="System.Security.Permissions.EnvironmentPermissionAttribute"></xref> class with the specified <xref href="System.Security.Permissions.SecurityAction"></xref>.
  syntax:
    content: public EnvironmentPermissionAttribute (System.Security.Permissions.SecurityAction action);
    parameters:
    - id: action
      type: System.Security.Permissions.SecurityAction
      description: One of the <xref href="System.Security.Permissions.SecurityAction"></xref> values.
  overload: System.Security.Permissions.EnvironmentPermissionAttribute.#ctor*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: The <code>action</code> parameter is not a valid value of <xref href="System.Security.Permissions.SecurityAction"></xref>.
  platform:
  - netframework-2.0
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.All
  id: All
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  langs:
  - csharp
  name: All
  nameWithType: EnvironmentPermissionAttribute.All
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.All
  type: Property
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  summary: Sets full access for the environment variables specified by the string value.
  remarks: Environment variable names are case-insensitive. Multiple environment variable names are specified by separating the names using <xref:System.IO.Path.PathSeparator>.
  syntax:
    content: public string All { get; set; }
    return:
      type: System.String
      description: A list of environment variables for full access.
  overload: System.Security.Permissions.EnvironmentPermissionAttribute.All*
  exceptions:
  - type: System.NotSupportedException
    commentId: T:System.NotSupportedException
    description: The get method is not supported for this property.
  platform:
  - netframework-2.0
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.CreatePermission
  id: CreatePermission
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  langs:
  - csharp
  name: CreatePermission()
  nameWithType: EnvironmentPermissionAttribute.CreatePermission()
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.CreatePermission()
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  summary: Creates and returns a new <xref href="System.Security.Permissions.EnvironmentPermission"></xref>.
  remarks: "This method should only be called by the security system, never by application code.  \n  \n At compile time, attributes convert security declarations to a serialized form in metadata. Declarative security data in metadata is created from the permission that this method returns that corresponds to this attribute."
  syntax:
    content: public override System.Security.IPermission CreatePermission ();
    parameters: []
    return:
      type: System.Security.IPermission
      description: An <xref href="System.Security.Permissions.EnvironmentPermission"></xref> that corresponds to this attribute.
  overload: System.Security.Permissions.EnvironmentPermissionAttribute.CreatePermission*
  exceptions: []
  platform:
  - netframework-2.0
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.Read
  id: Read
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  langs:
  - csharp
  name: Read
  nameWithType: EnvironmentPermissionAttribute.Read
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.Read
  type: Property
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  summary: Gets or sets read access for the environment variables specified by the string value.
  remarks: Environment variable names are case-insensitive. Multiple environment variable names are specified by separating the names using <xref:System.IO.Path.PathSeparator>.
  syntax:
    content: public string Read { get; set; }
    return:
      type: System.String
      description: A list of environment variables for read access.
  overload: System.Security.Permissions.EnvironmentPermissionAttribute.Read*
  exceptions: []
  platform:
  - netframework-2.0
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.Write
  id: Write
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  langs:
  - csharp
  name: Write
  nameWithType: EnvironmentPermissionAttribute.Write
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.Write
  type: Property
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  summary: Gets or sets write access for the environment variables specified by the string value.
  remarks: Environment variable names are case-insensitive. Multiple environment variable names are specified by separating the names using <xref:System.IO.Path.PathSeparator>.
  syntax:
    content: public string Write { get; set; }
    return:
      type: System.String
      description: A list of environment variables for write access.
  overload: System.Security.Permissions.EnvironmentPermissionAttribute.Write*
  exceptions: []
  platform:
  - netframework-2.0
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
references:
- uid: System.Security.Permissions.CodeAccessSecurityAttribute
  isExternal: false
  name: System.Security.Permissions.CodeAccessSecurityAttribute
- uid: System.ArgumentException
  parent: System
  isExternal: false
  name: ArgumentException
  nameWithType: ArgumentException
  fullName: System.ArgumentException
- uid: System.NotSupportedException
  parent: System
  isExternal: false
  name: NotSupportedException
  nameWithType: NotSupportedException
  fullName: System.NotSupportedException
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.#ctor(System.Security.Permissions.SecurityAction)
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  isExternal: false
  name: EnvironmentPermissionAttribute(SecurityAction)
  nameWithType: EnvironmentPermissionAttribute.EnvironmentPermissionAttribute(SecurityAction)
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.EnvironmentPermissionAttribute(SecurityAction)
- uid: System.Security.Permissions.SecurityAction
  parent: System.Security.Permissions
  isExternal: false
  name: SecurityAction
  nameWithType: SecurityAction
  fullName: System.Security.Permissions.SecurityAction
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.All
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  isExternal: false
  name: All
  nameWithType: EnvironmentPermissionAttribute.All
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.All
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.CreatePermission
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  isExternal: false
  name: CreatePermission()
  nameWithType: EnvironmentPermissionAttribute.CreatePermission()
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.CreatePermission()
- uid: System.Security.IPermission
  parent: System.Security
  isExternal: false
  name: IPermission
  nameWithType: IPermission
  fullName: System.Security.IPermission
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.Read
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  isExternal: false
  name: Read
  nameWithType: EnvironmentPermissionAttribute.Read
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.Read
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.Write
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  isExternal: false
  name: Write
  nameWithType: EnvironmentPermissionAttribute.Write
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.Write
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.#ctor*
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  isExternal: false
  name: EnvironmentPermissionAttribute
  nameWithType: EnvironmentPermissionAttribute.EnvironmentPermissionAttribute
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.All*
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  isExternal: false
  name: All
  nameWithType: EnvironmentPermissionAttribute.All
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.CreatePermission*
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  isExternal: false
  name: CreatePermission
  nameWithType: EnvironmentPermissionAttribute.CreatePermission
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.Read*
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  isExternal: false
  name: Read
  nameWithType: EnvironmentPermissionAttribute.Read
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.Write*
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  isExternal: false
  name: Write
  nameWithType: EnvironmentPermissionAttribute.Write
