### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  id: PeerCustomResolverSettings
  children:
  - System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.#ctor
  - System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Address
  - System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding
  - System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.IsBindingSpecified
  - System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Resolver
  langs:
  - csharp
  name: PeerCustomResolverSettings
  nameWithType: PeerCustomResolverSettings
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  type: Class
  summary: Contains the specific settings for an instance of a custom peer resolver service.
  remarks: This type defines the basic settings for a custom peer resolver service, including the endpoint address of the peer hosting the service and any specific binding settings. These settings are typically provided to the <xref:System.ServiceModel.PeerResolvers.PeerResolverSettings.Custom%2A> property.
  syntax:
    content: public class PeerCustomResolverSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.ServiceModel.PeerResolvers\PeerCustomResolverSettings.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.ServiceModel.PeerResolvers/PeerCustomResolverSettings.xml
  version:
  - netframework-3.0
  - netframework-3.5-client
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.#ctor
  id: '#ctor'
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  langs:
  - csharp
  name: PeerCustomResolverSettings()
  nameWithType: PeerCustomResolverSettings.PeerCustomResolverSettings()
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.PeerCustomResolverSettings()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: Initializes a new instance of the <xref href="System.ServiceModel.PeerResolvers.PeerCustomResolverSettings"></xref> class.
  syntax:
    content: public PeerCustomResolverSettings ();
    parameters: []
  overload: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.#ctor*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.ServiceModel.PeerResolvers\PeerCustomResolverSettings.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.ServiceModel.PeerResolvers/PeerCustomResolverSettings.xml
  version:
  - netframework-3.0
  - netframework-3.5-client
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Address
  id: Address
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  langs:
  - csharp
  name: Address
  nameWithType: PeerCustomResolverSettings.Address
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Address
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: Gets or sets the endpoint address of the peer node hosting the custom peer resolver service.
  syntax:
    content: public System.ServiceModel.EndpointAddress Address { get; set; }
    return:
      type: System.ServiceModel.EndpointAddress
      description: <xref href="System.ServiceModel.EndpointAddress"></xref> that contains the endpoint address of the peer node running the custom peer resolver service.
  overload: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Address*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.ServiceModel.PeerResolvers\PeerCustomResolverSettings.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.ServiceModel.PeerResolvers/PeerCustomResolverSettings.xml
  version:
  - netframework-3.0
  - netframework-3.5-client
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding
  id: Binding
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  langs:
  - csharp
  name: Binding
  nameWithType: PeerCustomResolverSettings.Binding
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: Gets or sets the channel binding used by the custom peer resolver service.
  remarks: This binding element provides the specification for building a channel factory on the client and a channel listener on the service. This channel factory is used to produce channels for the custom peer resolver service.
  syntax:
    content: public System.ServiceModel.Channels.Binding Binding { get; set; }
    return:
      type: System.ServiceModel.Channels.Binding
      description: <xref href="System.ServiceModel.Channels.Binding"></xref> that contains the binding settings for this service.
  overload: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.ServiceModel.PeerResolvers\PeerCustomResolverSettings.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.ServiceModel.PeerResolvers/PeerCustomResolverSettings.xml
  version:
  - netframework-3.0
  - netframework-3.5-client
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.IsBindingSpecified
  id: IsBindingSpecified
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  langs:
  - csharp
  name: IsBindingSpecified
  nameWithType: PeerCustomResolverSettings.IsBindingSpecified
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.IsBindingSpecified
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: Gets whether the <xref href="stem.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding%2A"></xref> property is set.
  syntax:
    content: public bool IsBindingSpecified { get; }
    return:
      type: System.Boolean
      description: True if the <xref href="stem.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding%2A"></xref> property is set; false if it is not.
  overload: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.IsBindingSpecified*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.ServiceModel.PeerResolvers\PeerCustomResolverSettings.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.ServiceModel.PeerResolvers/PeerCustomResolverSettings.xml
  version:
  - netframework-3.0
  - netframework-3.5-client
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Resolver
  id: Resolver
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  langs:
  - csharp
  name: Resolver
  nameWithType: PeerCustomResolverSettings.Resolver
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Resolver
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: Gets or sets the custom peer resolver instance for this service.
  syntax:
    content: public System.ServiceModel.PeerResolver Resolver { get; set; }
    return:
      type: System.ServiceModel.PeerResolver
      description: <xref href="System.ServiceModel.PeerResolver"></xref> instance used by the service.
  overload: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Resolver*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.ServiceModel.PeerResolvers\PeerCustomResolverSettings.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.ServiceModel.PeerResolvers/PeerCustomResolverSettings.xml
  version:
  - netframework-3.0
  - netframework-3.5-client
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.#ctor
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: PeerCustomResolverSettings()
  nameWithType: PeerCustomResolverSettings.PeerCustomResolverSettings()
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.PeerCustomResolverSettings()
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Address
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: Address
  nameWithType: PeerCustomResolverSettings.Address
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Address
- uid: System.ServiceModel.EndpointAddress
  parent: System.ServiceModel
  isExternal: false
  name: EndpointAddress
  nameWithType: EndpointAddress
  fullName: System.ServiceModel.EndpointAddress
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: Binding
  nameWithType: PeerCustomResolverSettings.Binding
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding
- uid: System.ServiceModel.Channels.Binding
  parent: System.ServiceModel.Channels
  isExternal: false
  name: Binding
  nameWithType: Binding
  fullName: System.ServiceModel.Channels.Binding
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.IsBindingSpecified
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: IsBindingSpecified
  nameWithType: PeerCustomResolverSettings.IsBindingSpecified
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.IsBindingSpecified
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Resolver
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: Resolver
  nameWithType: PeerCustomResolverSettings.Resolver
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Resolver
- uid: System.ServiceModel.PeerResolver
  parent: System.ServiceModel
  isExternal: false
  name: PeerResolver
  nameWithType: PeerResolver
  fullName: System.ServiceModel.PeerResolver
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.#ctor*
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: PeerCustomResolverSettings
  nameWithType: PeerCustomResolverSettings.PeerCustomResolverSettings
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Address*
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: Address
  nameWithType: PeerCustomResolverSettings.Address
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding*
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: Binding
  nameWithType: PeerCustomResolverSettings.Binding
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.IsBindingSpecified*
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: IsBindingSpecified
  nameWithType: PeerCustomResolverSettings.IsBindingSpecified
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Resolver*
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: Resolver
  nameWithType: PeerCustomResolverSettings.Resolver
