### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsGroupNameAttribute
  id: SettingsGroupNameAttribute
  children:
  - System.Configuration.SettingsGroupNameAttribute.#ctor(System.String)
  - System.Configuration.SettingsGroupNameAttribute.GroupName
  langs:
  - csharp
  name: SettingsGroupNameAttribute
  nameWithType: SettingsGroupNameAttribute
  fullName: System.Configuration.SettingsGroupNameAttribute
  type: Class
  summary: Specifies a name for application settings property group. This class cannot be inherited.
  remarks: "A application settings class, derived from <xref:System.Configuration.ApplicationSettingsBase>, defines one or more properties that belong to the same application settings property group. By default, the group is assigned the name of the settings class. However, SettingsGroupNameAttribute can be used to explicitly specify a name for the property group. This name can be helpful in organizing large sets of properties, for assistance in design-time programming tools and run-time administrative tools, and so on. The associated settings provider may even use this name to organize settings in the data store.  \n  \n The SettingsGroupNameAttribute can only be applied at the class level."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Class)]

      public sealed class SettingsGroupNameAttribute : Attribute
  inheritance:
  - System.Object
  - System.Attribute
  implements: []
  inheritedMembers:
  - System.Attribute.Equals(System.Object)
  - System.Attribute.GetCustomAttribute(System.Reflection.Assembly,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.Module,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.GetHashCode
  - System.Attribute.IsDefaultAttribute
  - System.Attribute.IsDefined(System.Reflection.Assembly,System.Type)
  - System.Attribute.IsDefined(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.IsDefined(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.Module,System.Type)
  - System.Attribute.IsDefined(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.IsDefined(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.Match(System.Object)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetIDsOfNames(System.Guid@,System.IntPtr,System.UInt32,System.UInt32,System.IntPtr)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetTypeInfo(System.UInt32,System.UInt32,System.IntPtr)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetTypeInfoCount(System.UInt32@)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#Invoke(System.UInt32,System.Guid@,System.UInt32,System.Int16,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr)
  - System.Attribute.TypeId
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  platform:
  - netframework-2.0
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
- uid: System.Configuration.SettingsGroupNameAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.SettingsGroupNameAttribute
  langs:
  - csharp
  name: SettingsGroupNameAttribute(String)
  nameWithType: SettingsGroupNameAttribute.SettingsGroupNameAttribute(String)
  fullName: System.Configuration.SettingsGroupNameAttribute.SettingsGroupNameAttribute(String)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: Initializes a new instance of the <xref href="System.Configuration.SettingsGroupNameAttribute"></xref> class.
  remarks: "Although the theoretical maximum length of the `groupName` parameter is constrained by the upper bounds of an <xref:System.Int32>, practical limits, determined by usability and quota limitations imposed by the settings provider, will be much smaller.  \n  \n> [!NOTE]\n>  The settings group name does not need to be unique."
  syntax:
    content: public SettingsGroupNameAttribute (string groupName);
    parameters:
    - id: groupName
      type: System.String
      description: A <xref href="System.String"></xref> containing the name of the application settings property group.
  overload: System.Configuration.SettingsGroupNameAttribute.#ctor*
  exceptions: []
  platform:
  - netframework-2.0
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
- uid: System.Configuration.SettingsGroupNameAttribute.GroupName
  id: GroupName
  parent: System.Configuration.SettingsGroupNameAttribute
  langs:
  - csharp
  name: GroupName
  nameWithType: SettingsGroupNameAttribute.GroupName
  fullName: System.Configuration.SettingsGroupNameAttribute.GroupName
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: Gets the name of the application settings property group.
  remarks: The GroupName property value is set by the <xref:System.Configuration.SettingsGroupNameAttribute.%23ctor%2A> constructor.
  syntax:
    content: public string GroupName { get; }
    return:
      type: System.String
      description: A <xref href="System.String"></xref> containing the name of the application settings property group.
  overload: System.Configuration.SettingsGroupNameAttribute.GroupName*
  exceptions: []
  platform:
  - netframework-2.0
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.SettingsGroupNameAttribute.#ctor(System.String)
  parent: System.Configuration.SettingsGroupNameAttribute
  isExternal: false
  name: SettingsGroupNameAttribute(String)
  nameWithType: SettingsGroupNameAttribute.SettingsGroupNameAttribute(String)
  fullName: System.Configuration.SettingsGroupNameAttribute.SettingsGroupNameAttribute(String)
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.SettingsGroupNameAttribute.GroupName
  parent: System.Configuration.SettingsGroupNameAttribute
  isExternal: false
  name: GroupName
  nameWithType: SettingsGroupNameAttribute.GroupName
  fullName: System.Configuration.SettingsGroupNameAttribute.GroupName
- uid: System.Configuration.SettingsGroupNameAttribute.#ctor*
  parent: System.Configuration.SettingsGroupNameAttribute
  isExternal: false
  name: SettingsGroupNameAttribute
  nameWithType: SettingsGroupNameAttribute.SettingsGroupNameAttribute
- uid: System.Configuration.SettingsGroupNameAttribute.GroupName*
  parent: System.Configuration.SettingsGroupNameAttribute
  isExternal: false
  name: GroupName
  nameWithType: SettingsGroupNameAttribute.GroupName
