### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.HostSettings
  id: HostSettings
  children:
  - System.ServiceModel.Activities.HostSettings.#ctor
  - System.ServiceModel.Activities.HostSettings.IncludeExceptionDetailInFaults
  - System.ServiceModel.Activities.HostSettings.ScopeName
  - System.ServiceModel.Activities.HostSettings.UseNoPersistHandle
  langs:
  - csharp
  name: HostSettings
  nameWithType: HostSettings
  fullName: System.ServiceModel.Activities.HostSettings
  type: Class
  summary: Represents settings that define operational characteristics of a host.
  syntax:
    content: public sealed class HostSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.ServiceModel.Activities\HostSettings.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.ServiceModel.Activities/HostSettings.xml
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.ServiceModel.Activities.HostSettings.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.HostSettings
  langs:
  - csharp
  name: HostSettings()
  nameWithType: HostSettings.HostSettings()
  fullName: System.ServiceModel.Activities.HostSettings.HostSettings()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Activities.HostSettings"></xref> class.
  syntax:
    content: public HostSettings ();
    parameters: []
  overload: System.ServiceModel.Activities.HostSettings.#ctor*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.ServiceModel.Activities\HostSettings.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.ServiceModel.Activities/HostSettings.xml
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.ServiceModel.Activities.HostSettings.IncludeExceptionDetailInFaults
  id: IncludeExceptionDetailInFaults
  parent: System.ServiceModel.Activities.HostSettings
  langs:
  - csharp
  name: IncludeExceptionDetailInFaults
  nameWithType: HostSettings.IncludeExceptionDetailInFaults
  fullName: System.ServiceModel.Activities.HostSettings.IncludeExceptionDetailInFaults
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities
  summary: Gets or sets whether exception details are included in faults.
  syntax:
    content: public bool IncludeExceptionDetailInFaults { get; set; }
    return:
      type: System.Boolean
      description: '`true` if exception details are included in faults; otherwise, `false`.'
  overload: System.ServiceModel.Activities.HostSettings.IncludeExceptionDetailInFaults*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.ServiceModel.Activities\HostSettings.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.ServiceModel.Activities/HostSettings.xml
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.ServiceModel.Activities.HostSettings.ScopeName
  id: ScopeName
  parent: System.ServiceModel.Activities.HostSettings
  langs:
  - csharp
  name: ScopeName
  nameWithType: HostSettings.ScopeName
  fullName: System.ServiceModel.Activities.HostSettings.ScopeName
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities
  summary: Gets or sets the name of scope.
  syntax:
    content: public System.Xml.Linq.XName ScopeName { get; set; }
    return:
      type: System.Xml.Linq.XName
      description: The name of scope.
  overload: System.ServiceModel.Activities.HostSettings.ScopeName*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.ServiceModel.Activities\HostSettings.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.ServiceModel.Activities/HostSettings.xml
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.ServiceModel.Activities.HostSettings.UseNoPersistHandle
  id: UseNoPersistHandle
  parent: System.ServiceModel.Activities.HostSettings
  langs:
  - csharp
  name: UseNoPersistHandle
  nameWithType: HostSettings.UseNoPersistHandle
  fullName: System.ServiceModel.Activities.HostSettings.UseNoPersistHandle
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities
  summary: Gets or sets a value that indicates whether to use non-persistent handle.
  syntax:
    content: public bool UseNoPersistHandle { get; set; }
    return:
      type: System.Boolean
      description: '`true` if non-persistent handle is used; otherwise, `false`.'
  overload: System.ServiceModel.Activities.HostSettings.UseNoPersistHandle*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.ServiceModel.Activities\HostSettings.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.ServiceModel.Activities/HostSettings.xml
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.Activities.HostSettings.#ctor
  parent: System.ServiceModel.Activities.HostSettings
  isExternal: false
  name: HostSettings()
  nameWithType: HostSettings.HostSettings()
  fullName: System.ServiceModel.Activities.HostSettings.HostSettings()
- uid: System.ServiceModel.Activities.HostSettings.IncludeExceptionDetailInFaults
  parent: System.ServiceModel.Activities.HostSettings
  isExternal: false
  name: IncludeExceptionDetailInFaults
  nameWithType: HostSettings.IncludeExceptionDetailInFaults
  fullName: System.ServiceModel.Activities.HostSettings.IncludeExceptionDetailInFaults
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Activities.HostSettings.ScopeName
  parent: System.ServiceModel.Activities.HostSettings
  isExternal: false
  name: ScopeName
  nameWithType: HostSettings.ScopeName
  fullName: System.ServiceModel.Activities.HostSettings.ScopeName
- uid: System.Xml.Linq.XName
  parent: System.Xml.Linq
  isExternal: false
  name: XName
  nameWithType: XName
  fullName: System.Xml.Linq.XName
- uid: System.ServiceModel.Activities.HostSettings.UseNoPersistHandle
  parent: System.ServiceModel.Activities.HostSettings
  isExternal: false
  name: UseNoPersistHandle
  nameWithType: HostSettings.UseNoPersistHandle
  fullName: System.ServiceModel.Activities.HostSettings.UseNoPersistHandle
- uid: System.ServiceModel.Activities.HostSettings.#ctor*
  parent: System.ServiceModel.Activities.HostSettings
  isExternal: false
  name: HostSettings
  nameWithType: HostSettings.HostSettings
- uid: System.ServiceModel.Activities.HostSettings.IncludeExceptionDetailInFaults*
  parent: System.ServiceModel.Activities.HostSettings
  isExternal: false
  name: IncludeExceptionDetailInFaults
  nameWithType: HostSettings.IncludeExceptionDetailInFaults
- uid: System.ServiceModel.Activities.HostSettings.ScopeName*
  parent: System.ServiceModel.Activities.HostSettings
  isExternal: false
  name: ScopeName
  nameWithType: HostSettings.ScopeName
- uid: System.ServiceModel.Activities.HostSettings.UseNoPersistHandle*
  parent: System.ServiceModel.Activities.HostSettings
  isExternal: false
  name: UseNoPersistHandle
  nameWithType: HostSettings.UseNoPersistHandle
