### YamlMime:ManagedReference
items:
- uid: System.Configuration.RegexStringValidatorAttribute
  id: RegexStringValidatorAttribute
  children:
  - System.Configuration.RegexStringValidatorAttribute.#ctor(System.String)
  - System.Configuration.RegexStringValidatorAttribute.Regex
  - System.Configuration.RegexStringValidatorAttribute.ValidatorInstance
  langs:
  - csharp
  name: RegexStringValidatorAttribute
  nameWithType: RegexStringValidatorAttribute
  fullName: System.Configuration.RegexStringValidatorAttribute
  type: Class
  summary: Declaratively instructs the .NET Framework to perform string validation on a configuration property using a regular expression. This class cannot be inherited.
  remarks: "You use the RegexStringValidatorAttribute to decorate a configuration property, which will instruct the .NET Framework to validate the property using the <xref:System.Configuration.RegexStringValidator> and pass to it the value of the decorating parameters.  \n  \n You may apply RegexStringValidatorAttribute objects to property types only."
  example:
  - "The following example shows how to decorate the properties of a custom <xref:System.Configuration.ConfigurationSection> object using the RegexStringValidatorAttribute object.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#4](~/add/codesnippet/visualbasic/t-system.configuration.r_2_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#4](~/add/codesnippet/csharp/t-system.configuration.r_2_1.cs)]"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class RegexStringValidatorAttribute : System.Configuration.ConfigurationValidatorAttribute
  inheritance:
  - System.Object
  - System.Attribute
  - System.Configuration.ConfigurationValidatorAttribute
  implements: []
  inheritedMembers:
  - System.Attribute.Equals(System.Object)
  - System.Attribute.GetCustomAttribute(System.Reflection.Assembly,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.Module,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.GetHashCode
  - System.Attribute.IsDefaultAttribute
  - System.Attribute.IsDefined(System.Reflection.Assembly,System.Type)
  - System.Attribute.IsDefined(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.IsDefined(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.Module,System.Type)
  - System.Attribute.IsDefined(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.IsDefined(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.Match(System.Object)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetIDsOfNames(System.Guid@,System.IntPtr,System.UInt32,System.UInt32,System.IntPtr)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetTypeInfo(System.UInt32,System.UInt32,System.IntPtr)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetTypeInfoCount(System.UInt32@)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#Invoke(System.UInt32,System.Guid@,System.UInt32,System.Int16,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr)
  - System.Attribute.TypeId
  - System.Configuration.ConfigurationValidatorAttribute.ValidatorType
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  platform:
  - netframework-2.0
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
- uid: System.Configuration.RegexStringValidatorAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.RegexStringValidatorAttribute
  langs:
  - csharp
  name: RegexStringValidatorAttribute(String)
  nameWithType: RegexStringValidatorAttribute.RegexStringValidatorAttribute(String)
  fullName: System.Configuration.RegexStringValidatorAttribute.RegexStringValidatorAttribute(String)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Initializes a new instance of the <xref href="System.Configuration.RegexStringValidatorAttribute"></xref> object.
  remarks: "The `regex` parameter contains the regular expression pattern that a string must match before it can be assigned to the decorated configuration-element property.  \n  \n You use this constructor in the attributed model to ensure that the string value assigned to the related property contains only the allowed characters."
  example:
  - "The following example shows how to use the RegexStringValidatorAttribute constructor.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#4](~/add/codesnippet/visualbasic/m-system.configuration.r_0_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#4](~/add/codesnippet/csharp/m-system.configuration.r_0_1.cs)]"
  syntax:
    content: public RegexStringValidatorAttribute (string regex);
    parameters:
    - id: regex
      type: System.String
      description: The string to use for regular expression validation.
  overload: System.Configuration.RegexStringValidatorAttribute.#ctor*
  exceptions: []
  platform:
  - netframework-2.0
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
- uid: System.Configuration.RegexStringValidatorAttribute.Regex
  id: Regex
  parent: System.Configuration.RegexStringValidatorAttribute
  langs:
  - csharp
  name: Regex
  nameWithType: RegexStringValidatorAttribute.Regex
  fullName: System.Configuration.RegexStringValidatorAttribute.Regex
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Gets the string used to perform regular-expression validation.
  remarks: ''
  example:
  - "The following example shows how to use the Regex property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#16](~/add/codesnippet/visualbasic/p-system.configuration.r_1_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#16](~/add/codesnippet/csharp/p-system.configuration.r_1_1.cs)]"
  syntax:
    content: public string Regex { get; }
    return:
      type: System.String
      description: The string containing the regular expression used to filter the string assigned to the decorated configuration-element property.
  overload: System.Configuration.RegexStringValidatorAttribute.Regex*
  exceptions: []
  platform:
  - netframework-2.0
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
- uid: System.Configuration.RegexStringValidatorAttribute.ValidatorInstance
  id: ValidatorInstance
  parent: System.Configuration.RegexStringValidatorAttribute
  langs:
  - csharp
  name: ValidatorInstance
  nameWithType: RegexStringValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.RegexStringValidatorAttribute.ValidatorInstance
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Gets an instance of the <xref href="System.Configuration.RegexStringValidator"></xref> class.
  remarks: You use the ValidatorInstance property to perform string validation by calling its <xref:System.Configuration.StringValidator.Validate%2A> method.
  example:
  - "The following example shows how to use the ValidatorInstance method.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#15](~/add/codesnippet/visualbasic/p-system.configuration.r_0_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#15](~/add/codesnippet/csharp/p-system.configuration.r_0_1.cs)]"
  syntax:
    content: public override System.Configuration.ConfigurationValidatorBase ValidatorInstance { get; }
    return:
      type: System.Configuration.ConfigurationValidatorBase
      description: The <xref href="System.Configuration.ConfigurationValidatorBase"></xref> validator instance.
  overload: System.Configuration.RegexStringValidatorAttribute.ValidatorInstance*
  exceptions: []
  platform:
  - netframework-2.0
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
references:
- uid: System.Configuration.ConfigurationValidatorAttribute
  isExternal: false
  name: System.Configuration.ConfigurationValidatorAttribute
- uid: System.Configuration.RegexStringValidatorAttribute.#ctor(System.String)
  parent: System.Configuration.RegexStringValidatorAttribute
  isExternal: false
  name: RegexStringValidatorAttribute(String)
  nameWithType: RegexStringValidatorAttribute.RegexStringValidatorAttribute(String)
  fullName: System.Configuration.RegexStringValidatorAttribute.RegexStringValidatorAttribute(String)
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.RegexStringValidatorAttribute.Regex
  parent: System.Configuration.RegexStringValidatorAttribute
  isExternal: false
  name: Regex
  nameWithType: RegexStringValidatorAttribute.Regex
  fullName: System.Configuration.RegexStringValidatorAttribute.Regex
- uid: System.Configuration.RegexStringValidatorAttribute.ValidatorInstance
  parent: System.Configuration.RegexStringValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: RegexStringValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.RegexStringValidatorAttribute.ValidatorInstance
- uid: System.Configuration.ConfigurationValidatorBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.RegexStringValidatorAttribute.#ctor*
  parent: System.Configuration.RegexStringValidatorAttribute
  isExternal: false
  name: RegexStringValidatorAttribute
  nameWithType: RegexStringValidatorAttribute.RegexStringValidatorAttribute
- uid: System.Configuration.RegexStringValidatorAttribute.Regex*
  parent: System.Configuration.RegexStringValidatorAttribute
  isExternal: false
  name: Regex
  nameWithType: RegexStringValidatorAttribute.Regex
- uid: System.Configuration.RegexStringValidatorAttribute.ValidatorInstance*
  parent: System.Configuration.RegexStringValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: RegexStringValidatorAttribute.ValidatorInstance
