### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.ConfigurationDuplexChannelFactory`1
  id: ConfigurationDuplexChannelFactory`1
  children:
  - System.ServiceModel.Configuration.ConfigurationDuplexChannelFactory`1.#ctor(System.Object,System.String,System.ServiceModel.EndpointAddress,System.Configuration.Configuration)
  langs:
  - csharp
  name: ConfigurationDuplexChannelFactory<TChannel>
  nameWithType: ConfigurationDuplexChannelFactory<TChannel>
  fullName: System.ServiceModel.Configuration.ConfigurationDuplexChannelFactory<TChannel>
  type: Class
  summary: Provides the functionality to create and manage duplex channels of different types that are used to send and receive messages to and from service endpoints.
  syntax:
    content: 'public sealed class ConfigurationDuplexChannelFactory<TChannel> : System.ServiceModel.DuplexChannelFactory<TChannel>'
    typeParameters:
    - id: TChannel
      description: The type of communications channel for the endpoint element that is created.
  inheritance:
  - System.Object
  - System.ServiceModel.Channels.CommunicationObject
  - System.ServiceModel.ChannelFactory
  - System.ServiceModel.ChannelFactory`1
  - System.ServiceModel.DuplexChannelFactory`1
  implements: []
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.ServiceModel.ChannelFactory.ApplyConfiguration(System.String)
  - System.ServiceModel.ChannelFactory.CreateFactory
  - System.ServiceModel.ChannelFactory.Credentials
  - System.ServiceModel.ChannelFactory.DefaultCloseTimeout
  - System.ServiceModel.ChannelFactory.DefaultOpenTimeout
  - System.ServiceModel.ChannelFactory.Endpoint
  - System.ServiceModel.ChannelFactory.EnsureOpened
  - System.ServiceModel.ChannelFactory.GetProperty``1
  - System.ServiceModel.ChannelFactory.InitializeEndpoint(System.ServiceModel.Channels.Binding,System.ServiceModel.EndpointAddress)
  - System.ServiceModel.ChannelFactory.InitializeEndpoint(System.ServiceModel.Description.ServiceEndpoint)
  - System.ServiceModel.ChannelFactory.InitializeEndpoint(System.String,System.ServiceModel.EndpointAddress)
  - System.ServiceModel.ChannelFactory.OnAbort
  - System.ServiceModel.ChannelFactory.OnBeginClose(System.TimeSpan,System.AsyncCallback,System.Object)
  - System.ServiceModel.ChannelFactory.OnBeginOpen(System.TimeSpan,System.AsyncCallback,System.Object)
  - System.ServiceModel.ChannelFactory.OnClose(System.TimeSpan)
  - System.ServiceModel.ChannelFactory.OnEndClose(System.IAsyncResult)
  - System.ServiceModel.ChannelFactory.OnEndOpen(System.IAsyncResult)
  - System.ServiceModel.ChannelFactory.OnOpen(System.TimeSpan)
  - System.ServiceModel.ChannelFactory.OnOpened
  - System.ServiceModel.ChannelFactory.OnOpening
  - System.ServiceModel.ChannelFactory.System#IDisposable#Dispose
  - System.ServiceModel.ChannelFactory`1.CreateChannel
  - System.ServiceModel.ChannelFactory`1.CreateChannel(System.ServiceModel.Channels.Binding,System.ServiceModel.EndpointAddress)
  - System.ServiceModel.ChannelFactory`1.CreateChannel(System.ServiceModel.Channels.Binding,System.ServiceModel.EndpointAddress,System.Uri)
  - System.ServiceModel.ChannelFactory`1.CreateChannel(System.ServiceModel.EndpointAddress)
  - System.ServiceModel.ChannelFactory`1.CreateChannel(System.String)
  - System.ServiceModel.ChannelFactory`1.CreateChannelWithActAsToken(System.IdentityModel.Tokens.SecurityToken)
  - System.ServiceModel.ChannelFactory`1.CreateChannelWithActAsToken(System.IdentityModel.Tokens.SecurityToken,System.ServiceModel.EndpointAddress)
  - System.ServiceModel.ChannelFactory`1.CreateChannelWithActAsToken(System.IdentityModel.Tokens.SecurityToken,System.ServiceModel.EndpointAddress,System.Uri)
  - System.ServiceModel.ChannelFactory`1.CreateChannelWithIssuedToken(System.IdentityModel.Tokens.SecurityToken)
  - System.ServiceModel.ChannelFactory`1.CreateChannelWithIssuedToken(System.IdentityModel.Tokens.SecurityToken,System.ServiceModel.EndpointAddress)
  - System.ServiceModel.ChannelFactory`1.CreateChannelWithIssuedToken(System.IdentityModel.Tokens.SecurityToken,System.ServiceModel.EndpointAddress,System.Uri)
  - System.ServiceModel.ChannelFactory`1.CreateChannelWithOnBehalfOfToken(System.IdentityModel.Tokens.SecurityToken)
  - System.ServiceModel.ChannelFactory`1.CreateChannelWithOnBehalfOfToken(System.IdentityModel.Tokens.SecurityToken,System.ServiceModel.EndpointAddress)
  - System.ServiceModel.ChannelFactory`1.CreateChannelWithOnBehalfOfToken(System.IdentityModel.Tokens.SecurityToken,System.ServiceModel.EndpointAddress,System.Uri)
  - System.ServiceModel.ChannelFactory`1.CreateDescription
  - System.ServiceModel.Channels.CommunicationObject.Abort
  - System.ServiceModel.Channels.CommunicationObject.BeginClose(System.AsyncCallback,System.Object)
  - System.ServiceModel.Channels.CommunicationObject.BeginClose(System.TimeSpan,System.AsyncCallback,System.Object)
  - System.ServiceModel.Channels.CommunicationObject.BeginOpen(System.AsyncCallback,System.Object)
  - System.ServiceModel.Channels.CommunicationObject.BeginOpen(System.TimeSpan,System.AsyncCallback,System.Object)
  - System.ServiceModel.Channels.CommunicationObject.Close
  - System.ServiceModel.Channels.CommunicationObject.Close(System.TimeSpan)
  - System.ServiceModel.Channels.CommunicationObject.Closed
  - System.ServiceModel.Channels.CommunicationObject.Closing
  - System.ServiceModel.Channels.CommunicationObject.EndClose(System.IAsyncResult)
  - System.ServiceModel.Channels.CommunicationObject.EndOpen(System.IAsyncResult)
  - System.ServiceModel.Channels.CommunicationObject.Fault
  - System.ServiceModel.Channels.CommunicationObject.Faulted
  - System.ServiceModel.Channels.CommunicationObject.GetCommunicationObjectType
  - System.ServiceModel.Channels.CommunicationObject.IsDisposed
  - System.ServiceModel.Channels.CommunicationObject.OnClosed
  - System.ServiceModel.Channels.CommunicationObject.OnClosing
  - System.ServiceModel.Channels.CommunicationObject.OnFaulted
  - System.ServiceModel.Channels.CommunicationObject.Open
  - System.ServiceModel.Channels.CommunicationObject.Open(System.TimeSpan)
  - System.ServiceModel.Channels.CommunicationObject.Opened
  - System.ServiceModel.Channels.CommunicationObject.Opening
  - System.ServiceModel.Channels.CommunicationObject.State
  - System.ServiceModel.Channels.CommunicationObject.ThisLock
  - System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposed
  - System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrImmutable
  - System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen
  - System.ServiceModel.DuplexChannelFactory`1.CreateChannel(System.Object,System.ServiceModel.Channels.Binding,System.ServiceModel.EndpointAddress)
  - System.ServiceModel.DuplexChannelFactory`1.CreateChannel(System.Object,System.ServiceModel.Channels.Binding,System.ServiceModel.EndpointAddress,System.Uri)
  - System.ServiceModel.DuplexChannelFactory`1.CreateChannel(System.Object,System.String)
  - System.ServiceModel.DuplexChannelFactory`1.CreateChannel(System.ServiceModel.EndpointAddress,System.Uri)
  - System.ServiceModel.DuplexChannelFactory`1.CreateChannel(System.ServiceModel.InstanceContext)
  - System.ServiceModel.DuplexChannelFactory`1.CreateChannel(System.ServiceModel.InstanceContext,System.ServiceModel.Channels.Binding,System.ServiceModel.EndpointAddress)
  - System.ServiceModel.DuplexChannelFactory`1.CreateChannel(System.ServiceModel.InstanceContext,System.ServiceModel.Channels.Binding,System.ServiceModel.EndpointAddress,System.Uri)
  - System.ServiceModel.DuplexChannelFactory`1.CreateChannel(System.ServiceModel.InstanceContext,System.ServiceModel.EndpointAddress)
  - System.ServiceModel.DuplexChannelFactory`1.CreateChannel(System.ServiceModel.InstanceContext,System.ServiceModel.EndpointAddress,System.Uri)
  - System.ServiceModel.DuplexChannelFactory`1.CreateChannel(System.ServiceModel.InstanceContext,System.String)
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.ServiceModel.Configuration\ConfigurationDuplexChannelFactory`1.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.ServiceModel.Configuration/ConfigurationDuplexChannelFactory`1.xml
  version:
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.ServiceModel.Configuration.ConfigurationDuplexChannelFactory`1.#ctor(System.Object,System.String,System.ServiceModel.EndpointAddress,System.Configuration.Configuration)
  id: '#ctor(System.Object,System.String,System.ServiceModel.EndpointAddress,System.Configuration.Configuration)'
  parent: System.ServiceModel.Configuration.ConfigurationDuplexChannelFactory`1
  langs:
  - csharp
  name: ConfigurationDuplexChannelFactory<TChannel>(Object,String,EndpointAddress,Configuration)
  nameWithType: ConfigurationDuplexChannelFactory<TChannel>.ConfigurationDuplexChannelFactory<TChannel>(Object,String,EndpointAddress,Configuration)
  fullName: System.ServiceModel.Configuration.ConfigurationDuplexChannelFactory<TChannel>.ConfigurationDuplexChannelFactory<TChannel>(Object,String,EndpointAddress,Configuration)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Creates a new instance of the <xref href="stem.ServiceModel.Configuration.ConfigurationDuplexChannelFactory%601"></xref> class with the specified callback object, endpoint configuration name, remote address, and configuration settings.
  syntax:
    content: public ConfigurationDuplexChannelFactory (object callbackObject, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress, System.Configuration.Configuration configuration);
    parameters:
    - id: callbackObject
      type: System.Object
      description: The process that responds to a message from the client.
    - id: endpointConfigurationName
      type: System.String
      description: The name property in an endpoint configuration element.
    - id: remoteAddress
      type: System.ServiceModel.EndpointAddress
      description: The IP address of a destination endpoint in a client or server session.
    - id: configuration
      type: System.Configuration.Configuration
      description: The settings that define the information presented in the endpoint element.
  overload: System.ServiceModel.Configuration.ConfigurationDuplexChannelFactory`1.#ctor*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: <code>configuration</code> is `null`.
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.ServiceModel.Configuration\ConfigurationDuplexChannelFactory`1.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.ServiceModel.Configuration/ConfigurationDuplexChannelFactory`1.xml
  version:
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
references:
- uid: System.ServiceModel.DuplexChannelFactory`1
  isExternal: false
  name: System.ServiceModel.DuplexChannelFactory<TChannel>
- uid: System.ArgumentNullException
  parent: System
  isExternal: false
  name: ArgumentNullException
  nameWithType: ArgumentNullException
  fullName: System.ArgumentNullException
- uid: System.ServiceModel.Configuration.ConfigurationDuplexChannelFactory`1.#ctor(System.Object,System.String,System.ServiceModel.EndpointAddress,System.Configuration.Configuration)
  parent: System.ServiceModel.Configuration.ConfigurationDuplexChannelFactory`1
  isExternal: false
  name: ConfigurationDuplexChannelFactory<TChannel>(Object,String,EndpointAddress,Configuration)
  nameWithType: ConfigurationDuplexChannelFactory<TChannel>.ConfigurationDuplexChannelFactory<TChannel>(Object,String,EndpointAddress,Configuration)
  fullName: System.ServiceModel.Configuration.ConfigurationDuplexChannelFactory<TChannel>.ConfigurationDuplexChannelFactory<TChannel>(Object,String,EndpointAddress,Configuration)
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.EndpointAddress
  parent: System.ServiceModel
  isExternal: false
  name: EndpointAddress
  nameWithType: EndpointAddress
  fullName: System.ServiceModel.EndpointAddress
- uid: System.Configuration.Configuration
  parent: System.Configuration
  isExternal: false
  name: Configuration
  nameWithType: Configuration
  fullName: System.Configuration.Configuration
- uid: System.ServiceModel.Configuration.ConfigurationDuplexChannelFactory`1.#ctor*
  parent: System.ServiceModel.Configuration.ConfigurationDuplexChannelFactory`1
  isExternal: false
  name: ConfigurationDuplexChannelFactory<TChannel>
  nameWithType: ConfigurationDuplexChannelFactory<TChannel>.ConfigurationDuplexChannelFactory<TChannel>
