### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Channels.ApplicationContainerSettings
  id: ApplicationContainerSettings
  children:
  - System.ServiceModel.Channels.ApplicationContainerSettings.CurrentSession
  - System.ServiceModel.Channels.ApplicationContainerSettings.PackageFullName
  - System.ServiceModel.Channels.ApplicationContainerSettings.ServiceSession
  - System.ServiceModel.Channels.ApplicationContainerSettings.SessionId
  langs:
  - csharp
  name: ApplicationContainerSettings
  nameWithType: ApplicationContainerSettings
  fullName: System.ServiceModel.Channels.ApplicationContainerSettings
  type: Class
  summary: Specifies application container settings.
  syntax:
    content: public sealed class ApplicationContainerSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.ServiceModel.Channels\ApplicationContainerSettings.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.ServiceModel.Channels/ApplicationContainerSettings.xml
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.ServiceModel.Channels.ApplicationContainerSettings.CurrentSession
  id: CurrentSession
  parent: System.ServiceModel.Channels.ApplicationContainerSettings
  langs:
  - csharp
  name: CurrentSession
  nameWithType: ApplicationContainerSettings.CurrentSession
  fullName: System.ServiceModel.Channels.ApplicationContainerSettings.CurrentSession
  type: Field
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: The current session settings.
  syntax:
    content: public const int CurrentSession = -1;
    return:
      type: System.Int32
      description: To be added.
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.ServiceModel.Channels\ApplicationContainerSettings.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.ServiceModel.Channels/ApplicationContainerSettings.xml
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.ServiceModel.Channels.ApplicationContainerSettings.PackageFullName
  id: PackageFullName
  parent: System.ServiceModel.Channels.ApplicationContainerSettings
  langs:
  - csharp
  name: PackageFullName
  nameWithType: ApplicationContainerSettings.PackageFullName
  fullName: System.ServiceModel.Channels.ApplicationContainerSettings.PackageFullName
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: Gets the fullname of the package.
  syntax:
    content: public string PackageFullName { get; set; }
    return:
      type: System.String
      description: The fullname of the package.
  overload: System.ServiceModel.Channels.ApplicationContainerSettings.PackageFullName*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.ServiceModel.Channels\ApplicationContainerSettings.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.ServiceModel.Channels/ApplicationContainerSettings.xml
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.ServiceModel.Channels.ApplicationContainerSettings.ServiceSession
  id: ServiceSession
  parent: System.ServiceModel.Channels.ApplicationContainerSettings
  langs:
  - csharp
  name: ServiceSession
  nameWithType: ApplicationContainerSettings.ServiceSession
  fullName: System.ServiceModel.Channels.ApplicationContainerSettings.ServiceSession
  type: Field
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: The service session settings.
  syntax:
    content: public const int ServiceSession = 0;
    return:
      type: System.Int32
      description: To be added.
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.ServiceModel.Channels\ApplicationContainerSettings.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.ServiceModel.Channels/ApplicationContainerSettings.xml
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.ServiceModel.Channels.ApplicationContainerSettings.SessionId
  id: SessionId
  parent: System.ServiceModel.Channels.ApplicationContainerSettings
  langs:
  - csharp
  name: SessionId
  nameWithType: ApplicationContainerSettings.SessionId
  fullName: System.ServiceModel.Channels.ApplicationContainerSettings.SessionId
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: Gets or sets the session identifier of the application container settings.
  syntax:
    content: public int SessionId { get; set; }
    return:
      type: System.Int32
      description: The session identifier of the application container settings.
  overload: System.ServiceModel.Channels.ApplicationContainerSettings.SessionId*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.ServiceModel.Channels\ApplicationContainerSettings.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.ServiceModel.Channels/ApplicationContainerSettings.xml
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.Channels.ApplicationContainerSettings.CurrentSession
  parent: System.ServiceModel.Channels.ApplicationContainerSettings
  isExternal: false
  name: CurrentSession
  nameWithType: ApplicationContainerSettings.CurrentSession
  fullName: System.ServiceModel.Channels.ApplicationContainerSettings.CurrentSession
- uid: System.Int32
  parent: System
  isExternal: false
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Channels.ApplicationContainerSettings.PackageFullName
  parent: System.ServiceModel.Channels.ApplicationContainerSettings
  isExternal: false
  name: PackageFullName
  nameWithType: ApplicationContainerSettings.PackageFullName
  fullName: System.ServiceModel.Channels.ApplicationContainerSettings.PackageFullName
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Channels.ApplicationContainerSettings.ServiceSession
  parent: System.ServiceModel.Channels.ApplicationContainerSettings
  isExternal: false
  name: ServiceSession
  nameWithType: ApplicationContainerSettings.ServiceSession
  fullName: System.ServiceModel.Channels.ApplicationContainerSettings.ServiceSession
- uid: System.ServiceModel.Channels.ApplicationContainerSettings.SessionId
  parent: System.ServiceModel.Channels.ApplicationContainerSettings
  isExternal: false
  name: SessionId
  nameWithType: ApplicationContainerSettings.SessionId
  fullName: System.ServiceModel.Channels.ApplicationContainerSettings.SessionId
- uid: System.ServiceModel.Channels.ApplicationContainerSettings.PackageFullName*
  parent: System.ServiceModel.Channels.ApplicationContainerSettings
  isExternal: false
  name: PackageFullName
  nameWithType: ApplicationContainerSettings.PackageFullName
- uid: System.ServiceModel.Channels.ApplicationContainerSettings.SessionId*
  parent: System.ServiceModel.Channels.ApplicationContainerSettings
  isExternal: false
  name: SessionId
  nameWithType: ApplicationContainerSettings.SessionId
