### YamlMime:ManagedReference
items:
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  id: XmlFormatExtensionPointAttribute
  children:
  - System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.#ctor(System.String)
  - System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.AllowElements
  - System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName
  langs:
  - csharp
  name: XmlFormatExtensionPointAttribute
  nameWithType: XmlFormatExtensionPointAttribute
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  type: Class
  summary: Specifies the XML namespace and XML namespace prefix to use for a service description format extension within a service description. This class cannot be inherited.
  remarks: "A service description format extension extends how a service description is generated for an XML Web service created using ASP.NET. Specifically, a service description format extension adds XML elements to the service description. This is useful when a SOAP extension is built to run on both the client and server side of an XML Web service, as information about SOAP extensions is not automatically placed in the service description. If you add information about the SOAP extension to the service description, a client can thus interpret that it must run the specific SOAP extension. An example of a SOAP extension that must run on both the client and server is an encryption SOAP extension. If an encryption SOAP extension runs on only the server, and it encrypts return values before sending them back to the client, the client must have the SOAP extension running to decrypt the SOAP message. Otherwise, the client cannot process the return value.  \n  \n Use the following steps to build a service description format extension:  \n  \n1.  Build a class that derives from <xref:System.Web.Services.Description.ServiceDescriptionFormatExtension>.  \n  \n2.  Apply a <xref:System.Web.Services.Configuration.XmlFormatExtensionAttribute> to the class and specify the extension points at which the service description format extension should run.  \n  \n3.  Optionally, apply a XmlFormatExtensionPointAttribute to the class and specify a member within the class to act as a new extension point.  \n  \n4.  Optionally, apply a <xref:System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute> to the class and specify the XML namespace prefix to be associated with XML elements generated by the service description format extension.  \n  \n5.  Configure the service description format extension to run within the `serviceDescriptionFormatExtensionTypes` section of the configuration file."
  example:
  - >-
    [!code-cs[ServiceDescriptionFormatExtension#1](~/add/codesnippet/csharp/t-system.web.services.co_1_1.cs)]
     [!code-vb[ServiceDescriptionFormatExtension#1](~/add/codesnippet/visualbasic/t-system.web.services.co_1_1.vb)]
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Class)]

      public sealed class XmlFormatExtensionPointAttribute : Attribute
  inheritance:
  - System.Object
  - System.Attribute
  implements: []
  inheritedMembers:
  - System.Attribute.Equals(System.Object)
  - System.Attribute.GetCustomAttribute(System.Reflection.Assembly,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.Module,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.GetHashCode
  - System.Attribute.IsDefaultAttribute
  - System.Attribute.IsDefined(System.Reflection.Assembly,System.Type)
  - System.Attribute.IsDefined(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.IsDefined(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.Module,System.Type)
  - System.Attribute.IsDefined(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.IsDefined(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.Match(System.Object)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetIDsOfNames(System.Guid@,System.IntPtr,System.UInt32,System.UInt32,System.IntPtr)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetTypeInfo(System.UInt32,System.UInt32,System.IntPtr)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetTypeInfoCount(System.UInt32@)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#Invoke(System.UInt32,System.Guid@,System.UInt32,System.Int16,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr)
  - System.Attribute.TypeId
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-20
  - netframework-30
  - netframework-35
  - netframework-40
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  langs:
  - csharp
  name: XmlFormatExtensionPointAttribute(String)
  nameWithType: XmlFormatExtensionPointAttribute.XmlFormatExtensionPointAttribute(String)
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.XmlFormatExtensionPointAttribute(String)
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: Initializes a new instance of the <xref href="System.Web.Services.Configuration.XmlFormatExtensionPointAttribute"></xref> class.
  syntax:
    content: public XmlFormatExtensionPointAttribute (string memberName);
    parameters:
    - id: memberName
      type: System.String
      description: The member of the class that implements the service description format extension that can have a service description format extension associated with it.
  overload: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.#ctor*
  exceptions: []
  version:
  - netframework-20
  - netframework-30
  - netframework-35
  - netframework-40
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.AllowElements
  id: AllowElements
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  langs:
  - csharp
  name: AllowElements
  nameWithType: XmlFormatExtensionPointAttribute.AllowElements
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.AllowElements
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: Gets or sets a value that indicates whether the member of the class that implements the service description format extension specified in the <xref:System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName*> property can accept raw XML elements.
  syntax:
    content: public bool AllowElements { get; set; }
    return:
      type: System.Boolean
      description: '`true` if the member of the class that implements the service description format extension specified in the <xref:System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName*> property can accept raw XML elements; otherwise, `false`. The default is `true`.'
  overload: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.AllowElements*
  exceptions: []
  version:
  - netframework-20
  - netframework-30
  - netframework-35
  - netframework-40
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName
  id: MemberName
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  langs:
  - csharp
  name: MemberName
  nameWithType: XmlFormatExtensionPointAttribute.MemberName
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: Specifies that the member of the class that implements the service description format extension can have a service description format extension associated with it.
  syntax:
    content: public string MemberName { get; set; }
    return:
      type: System.String
      description: The member of the class that implements the service description format extension that can have a service description format extension associated with it.
  overload: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName*
  exceptions: []
  version:
  - netframework-20
  - netframework-30
  - netframework-35
  - netframework-40
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.#ctor(System.String)
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  isExternal: false
  name: XmlFormatExtensionPointAttribute(String)
  nameWithType: XmlFormatExtensionPointAttribute.XmlFormatExtensionPointAttribute(String)
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.XmlFormatExtensionPointAttribute(String)
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.AllowElements
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  isExternal: false
  name: AllowElements
  nameWithType: XmlFormatExtensionPointAttribute.AllowElements
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.AllowElements
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  isExternal: false
  name: MemberName
  nameWithType: XmlFormatExtensionPointAttribute.MemberName
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.#ctor*
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  isExternal: false
  name: XmlFormatExtensionPointAttribute
  nameWithType: XmlFormatExtensionPointAttribute.XmlFormatExtensionPointAttribute
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.AllowElements*
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  isExternal: false
  name: AllowElements
  nameWithType: XmlFormatExtensionPointAttribute.AllowElements
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName*
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  isExternal: false
  name: MemberName
  nameWithType: XmlFormatExtensionPointAttribute.MemberName
