### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationPermissionAttribute
  id: ConfigurationPermissionAttribute
  children:
  - System.Configuration.ConfigurationPermissionAttribute.#ctor(System.Security.Permissions.SecurityAction)
  - System.Configuration.ConfigurationPermissionAttribute.CreatePermission
  langs:
  - csharp
  name: ConfigurationPermissionAttribute
  nameWithType: ConfigurationPermissionAttribute
  fullName: System.Configuration.ConfigurationPermissionAttribute
  type: Class
  summary: Creates a <xref href="System.Configuration.ConfigurationPermission"></xref> object that either grants or denies the marked target permission to access sections of configuration files.
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.All, AllowMultiple=true, Inherited=false)]

      public sealed class ConfigurationPermissionAttribute : System.Security.Permissions.CodeAccessSecurityAttribute
  inheritance:
  - System.Object
  - System.Attribute
  - System.Security.Permissions.SecurityAttribute
  - System.Security.Permissions.CodeAccessSecurityAttribute
  implements: []
  inheritedMembers:
  - System.Attribute.Equals(System.Object)
  - System.Attribute.GetCustomAttribute(System.Reflection.Assembly,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.Module,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.GetHashCode
  - System.Attribute.IsDefaultAttribute
  - System.Attribute.IsDefined(System.Reflection.Assembly,System.Type)
  - System.Attribute.IsDefined(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.IsDefined(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.Module,System.Type)
  - System.Attribute.IsDefined(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.IsDefined(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.Match(System.Object)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetIDsOfNames(System.Guid@,System.IntPtr,System.UInt32,System.UInt32,System.IntPtr)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetTypeInfo(System.UInt32,System.UInt32,System.IntPtr)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetTypeInfoCount(System.UInt32@)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#Invoke(System.UInt32,System.Guid@,System.UInt32,System.Int16,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr)
  - System.Attribute.TypeId
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.Security.Permissions.SecurityAttribute.Action
  - System.Security.Permissions.SecurityAttribute.Unrestricted
  platform:
  - netframework-2.0
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
- uid: System.Configuration.ConfigurationPermissionAttribute.#ctor(System.Security.Permissions.SecurityAction)
  id: '#ctor(System.Security.Permissions.SecurityAction)'
  parent: System.Configuration.ConfigurationPermissionAttribute
  langs:
  - csharp
  name: ConfigurationPermissionAttribute(SecurityAction)
  nameWithType: ConfigurationPermissionAttribute.ConfigurationPermissionAttribute(SecurityAction)
  fullName: System.Configuration.ConfigurationPermissionAttribute.ConfigurationPermissionAttribute(SecurityAction)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Initializes a new instance of the <xref href="System.Configuration.ConfigurationPermissionAttribute"></xref> class.
  syntax:
    content: public ConfigurationPermissionAttribute (System.Security.Permissions.SecurityAction action);
    parameters:
    - id: action
      type: System.Security.Permissions.SecurityAction
      description: The security action represented by an enumeration member of <xref href="System.Security.Permissions.SecurityAction"></xref>. Determines the permission state of the attribute.
  overload: System.Configuration.ConfigurationPermissionAttribute.#ctor*
  exceptions: []
  platform:
  - netframework-2.0
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
- uid: System.Configuration.ConfigurationPermissionAttribute.CreatePermission
  id: CreatePermission
  parent: System.Configuration.ConfigurationPermissionAttribute
  langs:
  - csharp
  name: CreatePermission()
  nameWithType: ConfigurationPermissionAttribute.CreatePermission()
  fullName: System.Configuration.ConfigurationPermissionAttribute.CreatePermission()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Creates and returns an object that implements the <xref href="System.Security.IPermission"></xref> interface.
  remarks: This method returns a new <xref:System.Configuration.ConfigurationPermission> object.
  syntax:
    content: public override System.Security.IPermission CreatePermission ();
    parameters: []
    return:
      type: System.Security.IPermission
      description: Returns an object that implements <xref href="System.Security.IPermission"></xref>.
  overload: System.Configuration.ConfigurationPermissionAttribute.CreatePermission*
  exceptions: []
  platform:
  - netframework-2.0
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
references:
- uid: System.Security.Permissions.CodeAccessSecurityAttribute
  isExternal: false
  name: System.Security.Permissions.CodeAccessSecurityAttribute
- uid: System.Configuration.ConfigurationPermissionAttribute.#ctor(System.Security.Permissions.SecurityAction)
  parent: System.Configuration.ConfigurationPermissionAttribute
  isExternal: false
  name: ConfigurationPermissionAttribute(SecurityAction)
  nameWithType: ConfigurationPermissionAttribute.ConfigurationPermissionAttribute(SecurityAction)
  fullName: System.Configuration.ConfigurationPermissionAttribute.ConfigurationPermissionAttribute(SecurityAction)
- uid: System.Security.Permissions.SecurityAction
  parent: System.Security.Permissions
  isExternal: false
  name: SecurityAction
  nameWithType: SecurityAction
  fullName: System.Security.Permissions.SecurityAction
- uid: System.Configuration.ConfigurationPermissionAttribute.CreatePermission
  parent: System.Configuration.ConfigurationPermissionAttribute
  isExternal: false
  name: CreatePermission()
  nameWithType: ConfigurationPermissionAttribute.CreatePermission()
  fullName: System.Configuration.ConfigurationPermissionAttribute.CreatePermission()
- uid: System.Security.IPermission
  parent: System.Security
  isExternal: false
  name: IPermission
  nameWithType: IPermission
  fullName: System.Security.IPermission
- uid: System.Configuration.ConfigurationPermissionAttribute.#ctor*
  parent: System.Configuration.ConfigurationPermissionAttribute
  isExternal: false
  name: ConfigurationPermissionAttribute
  nameWithType: ConfigurationPermissionAttribute.ConfigurationPermissionAttribute
- uid: System.Configuration.ConfigurationPermissionAttribute.CreatePermission*
  parent: System.Configuration.ConfigurationPermissionAttribute
  isExternal: false
  name: CreatePermission
  nameWithType: ConfigurationPermissionAttribute.CreatePermission
