### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs
  id: FederationConfigurationCreatedEventArgs
  children:
  - System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.#ctor(System.IdentityModel.Services.Configuration.FederationConfiguration)
  - System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration
  langs:
  - csharp
  name: FederationConfigurationCreatedEventArgs
  nameWithType: FederationConfigurationCreatedEventArgs
  fullName: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs
  type: Class
  summary: Provides data for the <xref href="System.IdentityModel.Services.FederatedAuthentication.FederationConfigurationCreated"></xref> event.
  remarks: The <xref:System.IdentityModel.Services.FederatedAuthentication.FederationConfigurationCreated?displayProperty=fullName> event is raised when the first HTTP module in the web application references the <xref:System.IdentityModel.Services.FederatedAuthentication.FederationConfiguration%2A?displayProperty=fullName> property. The first access of the this property causes a <xref:System.IdentityModel.Services.Configuration.FederationConfiguration> object to be created and initialized from configuration. The <xref:System.IdentityModel.Services.FederatedAuthentication.FederationConfigurationCreated?displayProperty=fullName> event is then raised. You can access the newly created <xref:System.IdentityModel.Services.Configuration.FederationConfiguration> object through the <xref:System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration%2A?displayProperty=fullName> property in an event handler in order to examine or modify it.
  syntax:
    content: 'public class FederationConfigurationCreatedEventArgs : EventArgs'
  inheritance:
  - System.Object
  - System.EventArgs
  implements: []
  inheritedMembers:
  - System.EventArgs.Empty
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.IdentityModel.Services.Configuration\FederationConfigurationCreatedEventArgs.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.IdentityModel.Services.Configuration/FederationConfigurationCreatedEventArgs.xml
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.#ctor(System.IdentityModel.Services.Configuration.FederationConfiguration)
  id: '#ctor(System.IdentityModel.Services.Configuration.FederationConfiguration)'
  parent: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs
  langs:
  - csharp
  name: FederationConfigurationCreatedEventArgs(FederationConfiguration)
  nameWithType: FederationConfigurationCreatedEventArgs.FederationConfigurationCreatedEventArgs(FederationConfiguration)
  fullName: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfigurationCreatedEventArgs(FederationConfiguration)
  type: Constructor
  assemblies:
  - System.IdentityModel.Services
  namespace: System.IdentityModel.Services.Configuration
  summary: Initializes a new instance of the <xref href="System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs"></xref> class with the specified federation configuration object.
  remarks: Initializes the <xref:System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration%2A> property to the federation configuration object specified by `config`.
  syntax:
    content: public FederationConfigurationCreatedEventArgs (System.IdentityModel.Services.Configuration.FederationConfiguration config);
    parameters:
    - id: config
      type: System.IdentityModel.Services.Configuration.FederationConfiguration
      description: The federation configuration object. A <xref href="System.IdentityModel.Services.Configuration.FederationConfiguration"></xref> object contains the configurable properties for the WS-Federation Authentication Module (<xref href="System.IdentityModel.Services.WSFederationAuthenticationModule"></xref>) and the Session Authentication Module (<xref href="System.IdentityModel.Services.SessionAuthenticationModule"></xref>) in a web application.
  overload: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.#ctor*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.IdentityModel.Services.Configuration\FederationConfigurationCreatedEventArgs.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.IdentityModel.Services.Configuration/FederationConfigurationCreatedEventArgs.xml
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration
  id: FederationConfiguration
  parent: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs
  langs:
  - csharp
  name: FederationConfiguration
  nameWithType: FederationConfigurationCreatedEventArgs.FederationConfiguration
  fullName: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration
  type: Property
  assemblies:
  - System.IdentityModel.Services
  namespace: System.IdentityModel.Services.Configuration
  summary: Gets or sets the federation configuration object that was initialized from the configuration file.
  remarks: "The <xref:System.IdentityModel.Services.Configuration.FederationConfiguration> object contains the configurable properties for the WS-Federation Authentication Module (<xref:System.IdentityModel.Services.WSFederationAuthenticationModule>) and the Session Authentication Module (<xref:System.IdentityModel.Services.SessionAuthenticationModule>) in a web application.  \n  \n To modify the configuration settings, you can set properties on the <xref:System.IdentityModel.Services.Configuration.FederationConfiguration> object that is referenced by this property, or you can provide an new <xref:System.IdentityModel.Services.Configuration.FederationConfiguration> object."
  syntax:
    content: public System.IdentityModel.Services.Configuration.FederationConfiguration FederationConfiguration { get; set; }
    return:
      type: System.IdentityModel.Services.Configuration.FederationConfiguration
      description: The federation configuration object that was initialized from configuration.
  overload: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.IdentityModel.Services.Configuration\FederationConfigurationCreatedEventArgs.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.IdentityModel.Services.Configuration/FederationConfigurationCreatedEventArgs.xml
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
references:
- uid: System.EventArgs
  isExternal: false
  name: System.EventArgs
- uid: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.#ctor(System.IdentityModel.Services.Configuration.FederationConfiguration)
  parent: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs
  isExternal: false
  name: FederationConfigurationCreatedEventArgs(FederationConfiguration)
  nameWithType: FederationConfigurationCreatedEventArgs.FederationConfigurationCreatedEventArgs(FederationConfiguration)
  fullName: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfigurationCreatedEventArgs(FederationConfiguration)
- uid: System.IdentityModel.Services.Configuration.FederationConfiguration
  parent: System.IdentityModel.Services.Configuration
  isExternal: false
  name: FederationConfiguration
  nameWithType: FederationConfiguration
  fullName: System.IdentityModel.Services.Configuration.FederationConfiguration
- uid: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration
  parent: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs
  isExternal: false
  name: FederationConfiguration
  nameWithType: FederationConfigurationCreatedEventArgs.FederationConfiguration
  fullName: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration
- uid: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.#ctor*
  parent: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs
  isExternal: false
  name: FederationConfigurationCreatedEventArgs
  nameWithType: FederationConfigurationCreatedEventArgs.FederationConfigurationCreatedEventArgs
- uid: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration*
  parent: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs
  isExternal: false
  name: FederationConfiguration
  nameWithType: FederationConfigurationCreatedEventArgs.FederationConfiguration
