### YamlMime:ManagedReference
items:
- uid: System.Configuration.PropertyValueOrigin
  id: PropertyValueOrigin
  children:
  - System.Configuration.PropertyValueOrigin.Default
  - System.Configuration.PropertyValueOrigin.Inherited
  - System.Configuration.PropertyValueOrigin.SetHere
  langs:
  - csharp
  name: PropertyValueOrigin
  nameWithType: PropertyValueOrigin
  fullName: System.Configuration.PropertyValueOrigin
  type: Enum
  summary: Specifies the level in the configuration hierarchy where a configuration property value originated.
  syntax:
    content: public enum PropertyValueOrigin
  inheritance:
  - System.Object
  - System.ValueType
  - System.Enum
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Configuration\PropertyValueOrigin.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Configuration/PropertyValueOrigin.xml
  version:
  - netframework-3.0
  - netframework-3.5-client
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.Configuration.PropertyValueOrigin.Default
  id: Default
  parent: System.Configuration.PropertyValueOrigin
  langs:
  - csharp
  name: Default
  nameWithType: PropertyValueOrigin.Default
  fullName: System.Configuration.PropertyValueOrigin.Default
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: The configuration property value originates from the <xref href="stem.Configuration.ConfigurationProperty.DefaultValue%2A"></xref> property.
  syntax:
    content: Default
    return:
      type: System.Configuration.PropertyValueOrigin
      description: To be added.
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Configuration\PropertyValueOrigin.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Configuration/PropertyValueOrigin.xml
  version:
  - netframework-3.0
  - netframework-3.5-client
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.Configuration.PropertyValueOrigin.Inherited
  id: Inherited
  parent: System.Configuration.PropertyValueOrigin
  langs:
  - csharp
  name: Inherited
  nameWithType: PropertyValueOrigin.Inherited
  fullName: System.Configuration.PropertyValueOrigin.Inherited
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: The configuration property value is inherited from a parent level in the configuration.
  syntax:
    content: Inherited
    return:
      type: System.Configuration.PropertyValueOrigin
      description: To be added.
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Configuration\PropertyValueOrigin.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Configuration/PropertyValueOrigin.xml
  version:
  - netframework-3.0
  - netframework-3.5-client
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.Configuration.PropertyValueOrigin.SetHere
  id: SetHere
  parent: System.Configuration.PropertyValueOrigin
  langs:
  - csharp
  name: SetHere
  nameWithType: PropertyValueOrigin.SetHere
  fullName: System.Configuration.PropertyValueOrigin.SetHere
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: The configuration property value is defined at the current level of the hierarchy.
  syntax:
    content: SetHere
    return:
      type: System.Configuration.PropertyValueOrigin
      description: To be added.
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.Configuration\PropertyValueOrigin.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.Configuration/PropertyValueOrigin.xml
  version:
  - netframework-3.0
  - netframework-3.5-client
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.PropertyValueOrigin.Default
  parent: System.Configuration.PropertyValueOrigin
  isExternal: false
  name: Default
  nameWithType: PropertyValueOrigin.Default
  fullName: System.Configuration.PropertyValueOrigin.Default
- uid: System.Configuration.PropertyValueOrigin
  parent: System.Configuration
  isExternal: false
  name: PropertyValueOrigin
  nameWithType: PropertyValueOrigin
  fullName: System.Configuration.PropertyValueOrigin
- uid: System.Configuration.PropertyValueOrigin.Inherited
  parent: System.Configuration.PropertyValueOrigin
  isExternal: false
  name: Inherited
  nameWithType: PropertyValueOrigin.Inherited
  fullName: System.Configuration.PropertyValueOrigin.Inherited
- uid: System.Configuration.PropertyValueOrigin.SetHere
  parent: System.Configuration.PropertyValueOrigin
  isExternal: false
  name: SetHere
  nameWithType: PropertyValueOrigin.SetHere
  fullName: System.Configuration.PropertyValueOrigin.SetHere
