### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement
  id: ServiceModelExtensionElement
  children:
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.#ctor
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.ConfigurationElementName
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.IsModified
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.Reset(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  langs:
  - csharp
  name: ServiceModelExtensionElement
  nameWithType: ServiceModelExtensionElement
  fullName: System.ServiceModel.Configuration.ServiceModelExtensionElement
  type: Class
  summary: An abstract base class for a configuration element that contains a dynamic collection of heterogeneous child elements.
  syntax:
    content: 'public abstract class ServiceModelExtensionElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.ServiceModelExtensionElement
  langs:
  - csharp
  name: ServiceModelExtensionElement()
  nameWithType: ServiceModelExtensionElement.ServiceModelExtensionElement()
  fullName: System.ServiceModel.Configuration.ServiceModelExtensionElement.ServiceModelExtensionElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.ServiceModelExtensionElement"></xref> class.
  syntax:
    content: protected ServiceModelExtensionElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.ServiceModelExtensionElement.#ctor*
  exceptions: []
  version:
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement.ConfigurationElementName
  id: ConfigurationElementName
  parent: System.ServiceModel.Configuration.ServiceModelExtensionElement
  langs:
  - csharp
  name: ConfigurationElementName
  nameWithType: ServiceModelExtensionElement.ConfigurationElementName
  fullName: System.ServiceModel.Configuration.ServiceModelExtensionElement.ConfigurationElementName
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets the name of this configuration element.
  syntax:
    content: public string ConfigurationElementName { get; }
    return:
      type: System.String
      description: The unique name of this configuration element.
  overload: System.ServiceModel.Configuration.ServiceModelExtensionElement.ConfigurationElementName*
  exceptions:
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: The configuration extension collection does not exist.
  version:
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  id: CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  parent: System.ServiceModel.Configuration.ServiceModelExtensionElement
  langs:
  - csharp
  name: CopyFrom(ServiceModelExtensionElement)
  nameWithType: ServiceModelExtensionElement.CopyFrom(ServiceModelExtensionElement)
  fullName: System.ServiceModel.Configuration.ServiceModelExtensionElement.CopyFrom(ServiceModelExtensionElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Copies the content of the specified configuration element to this configuration element.
  syntax:
    content: public virtual void CopyFrom (System.ServiceModel.Configuration.ServiceModelExtensionElement from);
    parameters:
    - id: from
      type: System.ServiceModel.Configuration.ServiceModelExtensionElement
      description: The configuration element to be copied.
  overload: System.ServiceModel.Configuration.ServiceModelExtensionElement.CopyFrom*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: <code>from</code> is `null`.
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: The configuration file is read-only.
  version:
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement.IsModified
  id: IsModified
  parent: System.ServiceModel.Configuration.ServiceModelExtensionElement
  langs:
  - csharp
  name: IsModified()
  nameWithType: ServiceModelExtensionElement.IsModified()
  fullName: System.ServiceModel.Configuration.ServiceModelExtensionElement.IsModified()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets a value that specifies whether this configuration element has been modified.
  syntax:
    content: protected override bool IsModified ();
    parameters: []
    return:
      type: System.Boolean
      description: '`true` if this configuration element has been modified; otherwise, `false`.'
  overload: System.ServiceModel.Configuration.ServiceModelExtensionElement.IsModified*
  exceptions: []
  version:
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement.Reset(System.Configuration.ConfigurationElement)
  id: Reset(System.Configuration.ConfigurationElement)
  parent: System.ServiceModel.Configuration.ServiceModelExtensionElement
  langs:
  - csharp
  name: Reset(ConfigurationElement)
  nameWithType: ServiceModelExtensionElement.Reset(ConfigurationElement)
  fullName: System.ServiceModel.Configuration.ServiceModelExtensionElement.Reset(ConfigurationElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Resets the internal state of this configuration element object, including the locks and the properties collections.
  syntax:
    content: protected override void Reset (System.Configuration.ConfigurationElement parentElement);
    parameters:
    - id: parentElement
      type: System.Configuration.ConfigurationElement
      description: The parent node of this configuration element.
  overload: System.ServiceModel.Configuration.ServiceModelExtensionElement.Reset*
  exceptions: []
  version:
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  id: SerializeElement(System.Xml.XmlWriter,System.Boolean)
  parent: System.ServiceModel.Configuration.ServiceModelExtensionElement
  langs:
  - csharp
  name: SerializeElement(XmlWriter,Boolean)
  nameWithType: ServiceModelExtensionElement.SerializeElement(XmlWriter,Boolean)
  fullName: System.ServiceModel.Configuration.ServiceModelExtensionElement.SerializeElement(XmlWriter,Boolean)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Writes the contents of this configuration element to the configuration file.
  syntax:
    content: protected override bool SerializeElement (System.Xml.XmlWriter writer, bool serializeCollectionKey);
    parameters:
    - id: writer
      type: System.Xml.XmlWriter
      description: The <xref href="System.Xml.XmlWriter"></xref> that is used to write to the configuration file.
    - id: serializeCollectionKey
      type: System.Boolean
      description: '`true` to serialize only the collection key properties; otherwise, `false`.'
    return:
      type: System.Boolean
      description: '`true` if any data was actually serialized; otherwise, `false`.'
  overload: System.ServiceModel.Configuration.ServiceModelExtensionElement.SerializeElement*
  exceptions: []
  version:
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Configuration.ConfigurationErrorsException
  parent: System.Configuration
  isExternal: false
  name: ConfigurationErrorsException
  nameWithType: ConfigurationErrorsException
  fullName: System.Configuration.ConfigurationErrorsException
- uid: System.ArgumentNullException
  parent: System
  isExternal: false
  name: ArgumentNullException
  nameWithType: ArgumentNullException
  fullName: System.ArgumentNullException
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement.#ctor
  parent: System.ServiceModel.Configuration.ServiceModelExtensionElement
  isExternal: false
  name: ServiceModelExtensionElement()
  nameWithType: ServiceModelExtensionElement.ServiceModelExtensionElement()
  fullName: System.ServiceModel.Configuration.ServiceModelExtensionElement.ServiceModelExtensionElement()
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement.ConfigurationElementName
  parent: System.ServiceModel.Configuration.ServiceModelExtensionElement
  isExternal: false
  name: ConfigurationElementName
  nameWithType: ServiceModelExtensionElement.ConfigurationElementName
  fullName: System.ServiceModel.Configuration.ServiceModelExtensionElement.ConfigurationElementName
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  parent: System.ServiceModel.Configuration.ServiceModelExtensionElement
  isExternal: false
  name: CopyFrom(ServiceModelExtensionElement)
  nameWithType: ServiceModelExtensionElement.CopyFrom(ServiceModelExtensionElement)
  fullName: System.ServiceModel.Configuration.ServiceModelExtensionElement.CopyFrom(ServiceModelExtensionElement)
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ServiceModelExtensionElement
  nameWithType: ServiceModelExtensionElement
  fullName: System.ServiceModel.Configuration.ServiceModelExtensionElement
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement.IsModified
  parent: System.ServiceModel.Configuration.ServiceModelExtensionElement
  isExternal: false
  name: IsModified()
  nameWithType: ServiceModelExtensionElement.IsModified()
  fullName: System.ServiceModel.Configuration.ServiceModelExtensionElement.IsModified()
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement.Reset(System.Configuration.ConfigurationElement)
  parent: System.ServiceModel.Configuration.ServiceModelExtensionElement
  isExternal: false
  name: Reset(ConfigurationElement)
  nameWithType: ServiceModelExtensionElement.Reset(ConfigurationElement)
  fullName: System.ServiceModel.Configuration.ServiceModelExtensionElement.Reset(ConfigurationElement)
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  parent: System.ServiceModel.Configuration.ServiceModelExtensionElement
  isExternal: false
  name: SerializeElement(XmlWriter,Boolean)
  nameWithType: ServiceModelExtensionElement.SerializeElement(XmlWriter,Boolean)
  fullName: System.ServiceModel.Configuration.ServiceModelExtensionElement.SerializeElement(XmlWriter,Boolean)
- uid: System.Xml.XmlWriter
  parent: System.Xml
  isExternal: false
  name: XmlWriter
  nameWithType: XmlWriter
  fullName: System.Xml.XmlWriter
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement.#ctor*
  parent: System.ServiceModel.Configuration.ServiceModelExtensionElement
  isExternal: false
  name: ServiceModelExtensionElement
  nameWithType: ServiceModelExtensionElement.ServiceModelExtensionElement
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement.ConfigurationElementName*
  parent: System.ServiceModel.Configuration.ServiceModelExtensionElement
  isExternal: false
  name: ConfigurationElementName
  nameWithType: ServiceModelExtensionElement.ConfigurationElementName
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement.CopyFrom*
  parent: System.ServiceModel.Configuration.ServiceModelExtensionElement
  isExternal: false
  name: CopyFrom
  nameWithType: ServiceModelExtensionElement.CopyFrom
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement.IsModified*
  parent: System.ServiceModel.Configuration.ServiceModelExtensionElement
  isExternal: false
  name: IsModified
  nameWithType: ServiceModelExtensionElement.IsModified
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement.Reset*
  parent: System.ServiceModel.Configuration.ServiceModelExtensionElement
  isExternal: false
  name: Reset
  nameWithType: ServiceModelExtensionElement.Reset
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement.SerializeElement*
  parent: System.ServiceModel.Configuration.ServiceModelExtensionElement
  isExternal: false
  name: SerializeElement
  nameWithType: ServiceModelExtensionElement.SerializeElement
