### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.TcpTransportSecurity
  id: TcpTransportSecurity
  children:
  - System.ServiceModel.TcpTransportSecurity.#ctor
  - System.ServiceModel.TcpTransportSecurity.ClientCredentialType
  - System.ServiceModel.TcpTransportSecurity.ExtendedProtectionPolicy
  - System.ServiceModel.TcpTransportSecurity.ProtectionLevel
  - System.ServiceModel.TcpTransportSecurity.ShouldSerializeExtendedProtectionPolicy
  - System.ServiceModel.TcpTransportSecurity.SslProtocols
  langs:
  - csharp
  name: TcpTransportSecurity
  nameWithType: TcpTransportSecurity
  fullName: System.ServiceModel.TcpTransportSecurity
  type: Class
  summary: Provides properties that control authentication parameters and protection level for the TCP transport.
  remarks: This class is used by <xref:System.ServiceModel.NetTcpSecurity.Transport%2A> to set the transport-level security settings for a binding.
  syntax:
    content: public sealed class TcpTransportSecurity
  inheritance:
  - System.Object
  implements: []
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.ServiceModel\TcpTransportSecurity.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.ServiceModel/TcpTransportSecurity.xml
  version:
  - netframework-3.0
  - netframework-3.5-client
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.ServiceModel.TcpTransportSecurity.#ctor
  id: '#ctor'
  parent: System.ServiceModel.TcpTransportSecurity
  langs:
  - csharp
  name: TcpTransportSecurity()
  nameWithType: TcpTransportSecurity.TcpTransportSecurity()
  fullName: System.ServiceModel.TcpTransportSecurity.TcpTransportSecurity()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: Initializes a new instance of the <xref href="System.ServiceModel.TcpTransportSecurity"></xref> class.
  syntax:
    content: public TcpTransportSecurity ();
    parameters: []
  overload: System.ServiceModel.TcpTransportSecurity.#ctor*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.ServiceModel\TcpTransportSecurity.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.ServiceModel/TcpTransportSecurity.xml
  version:
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.ServiceModel.TcpTransportSecurity.ClientCredentialType
  id: ClientCredentialType
  parent: System.ServiceModel.TcpTransportSecurity
  langs:
  - csharp
  name: ClientCredentialType
  nameWithType: TcpTransportSecurity.ClientCredentialType
  fullName: System.ServiceModel.TcpTransportSecurity.ClientCredentialType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: Gets or sets the type of client credential used for authentication.
  remarks: "The return value can be one of the following enumeration members:  \n  \n-   <xref:System.ServiceModel.HttpClientCredentialType>  \n  \n-   <xref:System.ServiceModel.HttpClientCredentialType>  \n  \n-   <xref:System.ServiceModel.HttpClientCredentialType>  \n  \n-   <xref:System.ServiceModel.HttpClientCredentialType>  \n  \n-   <xref:System.ServiceModel.HttpClientCredentialType>  \n  \n-   <xref:System.ServiceModel.HttpClientCredentialType>"
  example:
  - "The following code shows how to access and set this property.  \n  \n [!code-vb[c_ProgrammingSecurity#13](~/add/codesnippet/visualbasic/p-system.servicemodel.tc_1.vb)]\n [!code-cs[c_ProgrammingSecurity#13](~/add/codesnippet/csharp/p-system.servicemodel.tc_1.cs)]"
  syntax:
    content: public System.ServiceModel.TcpClientCredentialType ClientCredentialType { get; set; }
    return:
      type: System.ServiceModel.TcpClientCredentialType
      description: Returns the <xref href="System.ServiceModel.TcpClientCredentialType"></xref>.
  overload: System.ServiceModel.TcpTransportSecurity.ClientCredentialType*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.ServiceModel\TcpTransportSecurity.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.ServiceModel/TcpTransportSecurity.xml
  version:
  - netframework-3.0
  - netframework-3.5-client
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.ServiceModel.TcpTransportSecurity.ExtendedProtectionPolicy
  id: ExtendedProtectionPolicy
  parent: System.ServiceModel.TcpTransportSecurity
  langs:
  - csharp
  name: ExtendedProtectionPolicy
  nameWithType: TcpTransportSecurity.ExtendedProtectionPolicy
  fullName: System.ServiceModel.TcpTransportSecurity.ExtendedProtectionPolicy
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: Gets or sets the extended protection policy for the TCP transport.
  syntax:
    content: public System.Security.Authentication.ExtendedProtection.ExtendedProtectionPolicy ExtendedProtectionPolicy { get; set; }
    return:
      type: System.Security.Authentication.ExtendedProtection.ExtendedProtectionPolicy
      description: The extended protection policy for the TCP transport.
  overload: System.ServiceModel.TcpTransportSecurity.ExtendedProtectionPolicy*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.ServiceModel\TcpTransportSecurity.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.ServiceModel/TcpTransportSecurity.xml
  version:
  - netframework-3.0
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.ServiceModel.TcpTransportSecurity.ProtectionLevel
  id: ProtectionLevel
  parent: System.ServiceModel.TcpTransportSecurity
  langs:
  - csharp
  name: ProtectionLevel
  nameWithType: TcpTransportSecurity.ProtectionLevel
  fullName: System.ServiceModel.TcpTransportSecurity.ProtectionLevel
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: Gets or sets the <xref href="System.Net.Security.ProtectionLevel"></xref> for the TCP stream.
  syntax:
    content: public System.Net.Security.ProtectionLevel ProtectionLevel { get; set; }
    return:
      type: System.Net.Security.ProtectionLevel
      description: Returns the <xref href="System.Net.Security.ProtectionLevel"></xref>.
  overload: System.ServiceModel.TcpTransportSecurity.ProtectionLevel*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.ServiceModel\TcpTransportSecurity.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.ServiceModel/TcpTransportSecurity.xml
  version:
  - netframework-3.0
  - netframework-3.5-client
  - netframework-3.5
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.ServiceModel.TcpTransportSecurity.ShouldSerializeExtendedProtectionPolicy
  id: ShouldSerializeExtendedProtectionPolicy
  parent: System.ServiceModel.TcpTransportSecurity
  langs:
  - csharp
  name: ShouldSerializeExtendedProtectionPolicy()
  nameWithType: TcpTransportSecurity.ShouldSerializeExtendedProtectionPolicy()
  fullName: System.ServiceModel.TcpTransportSecurity.ShouldSerializeExtendedProtectionPolicy()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: Returns a value that indicates whether the <xref href="stem.ServiceModel.TcpTransportSecurity.ExtendedProtectionPolicy%2A"></xref> property has changed from its default value and should be serialized. It is used by WCF for XAML integration.
  syntax:
    content: public bool ShouldSerializeExtendedProtectionPolicy ();
    parameters: []
    return:
      type: System.Boolean
      description: '`true` if the <xref href="stem.ServiceModel.TcpTransportSecurity.ExtendedProtectionPolicy%2A"></xref> property value should be serialized; otherwise, `false`.'
  overload: System.ServiceModel.TcpTransportSecurity.ShouldSerializeExtendedProtectionPolicy*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.ServiceModel\TcpTransportSecurity.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.ServiceModel/TcpTransportSecurity.xml
  version:
  - netframework-4.0-client
  - netframework-4.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.ServiceModel.TcpTransportSecurity.SslProtocols
  id: SslProtocols
  parent: System.ServiceModel.TcpTransportSecurity
  langs:
  - csharp
  name: SslProtocols
  nameWithType: TcpTransportSecurity.SslProtocols
  fullName: System.ServiceModel.TcpTransportSecurity.SslProtocols
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: 'Specifies the list of SSL/TLS protocols to negotiate when using a client credential type of TcpClientCredentialType.Certificate. The value can be a combination of one of more of the following enumeration members: Ssl3, Tls, Tls11, Tls12.'
  remarks: The default value is Ssl3 &#124; Tls &#124; Tls11 &#124; Tls12. Versions of the framework prior to 4.6 only support Ssl3 and Tls. If these are not included, communication with earlier versions of the framework will not be possible. Specifying Tls11 and/or Tls12 will disable the usage of Ssl3, even if it has been included.
  example:
  - "```c#  \nNetTcpBinding b = new NetTcpBinding();  \nb.Security.Mode = SecurityMode.Transport;  \nb.Security.Transport.ClientCredentialType = TcpClientCredentialType.Certificate;  \nb.Security.Transport.SslProtocols = SslProtocols.Tls11 | SslProtocols.Tls12;  \nEndpointAddress a = new EndpointAddress(\"net.tcp://contoso.com/TcpAddress\");  \nChannelFactory<ICalculator> cf = new ChannelFactory<ICalculator>(b, a);  \ncf.Credentials.ClientCertificate.SetCertificate(  \n    StoreLocation.LocalMachine,  \n    StoreName.My,  \n    X509FindType.FindByThumbprint,  \n    \"0000000000000000000000000000000000000000\");  \n```"
  syntax:
    content: public System.Security.Authentication.SslProtocols SslProtocols { get; set; }
    return:
      type: System.Security.Authentication.SslProtocols
      description: Returns <xref href="System.Security.Authentication.SslProtocols"></xref>.
  overload: System.ServiceModel.TcpTransportSecurity.SslProtocols*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.ServiceModel\TcpTransportSecurity.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.ServiceModel/TcpTransportSecurity.xml
  version:
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.TcpTransportSecurity.#ctor
  parent: System.ServiceModel.TcpTransportSecurity
  isExternal: false
  name: TcpTransportSecurity()
  nameWithType: TcpTransportSecurity.TcpTransportSecurity()
  fullName: System.ServiceModel.TcpTransportSecurity.TcpTransportSecurity()
- uid: System.ServiceModel.TcpTransportSecurity.ClientCredentialType
  parent: System.ServiceModel.TcpTransportSecurity
  isExternal: false
  name: ClientCredentialType
  nameWithType: TcpTransportSecurity.ClientCredentialType
  fullName: System.ServiceModel.TcpTransportSecurity.ClientCredentialType
- uid: System.ServiceModel.TcpClientCredentialType
  parent: System.ServiceModel
  isExternal: false
  name: TcpClientCredentialType
  nameWithType: TcpClientCredentialType
  fullName: System.ServiceModel.TcpClientCredentialType
- uid: System.ServiceModel.TcpTransportSecurity.ExtendedProtectionPolicy
  parent: System.ServiceModel.TcpTransportSecurity
  isExternal: false
  name: ExtendedProtectionPolicy
  nameWithType: TcpTransportSecurity.ExtendedProtectionPolicy
  fullName: System.ServiceModel.TcpTransportSecurity.ExtendedProtectionPolicy
- uid: System.Security.Authentication.ExtendedProtection.ExtendedProtectionPolicy
  parent: System.Security.Authentication.ExtendedProtection
  isExternal: false
  name: ExtendedProtectionPolicy
  nameWithType: ExtendedProtectionPolicy
  fullName: System.Security.Authentication.ExtendedProtection.ExtendedProtectionPolicy
- uid: System.ServiceModel.TcpTransportSecurity.ProtectionLevel
  parent: System.ServiceModel.TcpTransportSecurity
  isExternal: false
  name: ProtectionLevel
  nameWithType: TcpTransportSecurity.ProtectionLevel
  fullName: System.ServiceModel.TcpTransportSecurity.ProtectionLevel
- uid: System.Net.Security.ProtectionLevel
  parent: System.Net.Security
  isExternal: false
  name: ProtectionLevel
  nameWithType: ProtectionLevel
  fullName: System.Net.Security.ProtectionLevel
- uid: System.ServiceModel.TcpTransportSecurity.ShouldSerializeExtendedProtectionPolicy
  parent: System.ServiceModel.TcpTransportSecurity
  isExternal: false
  name: ShouldSerializeExtendedProtectionPolicy()
  nameWithType: TcpTransportSecurity.ShouldSerializeExtendedProtectionPolicy()
  fullName: System.ServiceModel.TcpTransportSecurity.ShouldSerializeExtendedProtectionPolicy()
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.TcpTransportSecurity.SslProtocols
  parent: System.ServiceModel.TcpTransportSecurity
  isExternal: false
  name: SslProtocols
  nameWithType: TcpTransportSecurity.SslProtocols
  fullName: System.ServiceModel.TcpTransportSecurity.SslProtocols
- uid: System.Security.Authentication.SslProtocols
  parent: System.Security.Authentication
  isExternal: false
  name: SslProtocols
  nameWithType: SslProtocols
  fullName: System.Security.Authentication.SslProtocols
- uid: System.ServiceModel.TcpTransportSecurity.#ctor*
  parent: System.ServiceModel.TcpTransportSecurity
  isExternal: false
  name: TcpTransportSecurity
  nameWithType: TcpTransportSecurity.TcpTransportSecurity
- uid: System.ServiceModel.TcpTransportSecurity.ClientCredentialType*
  parent: System.ServiceModel.TcpTransportSecurity
  isExternal: false
  name: ClientCredentialType
  nameWithType: TcpTransportSecurity.ClientCredentialType
- uid: System.ServiceModel.TcpTransportSecurity.ExtendedProtectionPolicy*
  parent: System.ServiceModel.TcpTransportSecurity
  isExternal: false
  name: ExtendedProtectionPolicy
  nameWithType: TcpTransportSecurity.ExtendedProtectionPolicy
- uid: System.ServiceModel.TcpTransportSecurity.ProtectionLevel*
  parent: System.ServiceModel.TcpTransportSecurity
  isExternal: false
  name: ProtectionLevel
  nameWithType: TcpTransportSecurity.ProtectionLevel
- uid: System.ServiceModel.TcpTransportSecurity.ShouldSerializeExtendedProtectionPolicy*
  parent: System.ServiceModel.TcpTransportSecurity
  isExternal: false
  name: ShouldSerializeExtendedProtectionPolicy
  nameWithType: TcpTransportSecurity.ShouldSerializeExtendedProtectionPolicy
- uid: System.ServiceModel.TcpTransportSecurity.SslProtocols*
  parent: System.ServiceModel.TcpTransportSecurity
  isExternal: false
  name: SslProtocols
  nameWithType: TcpTransportSecurity.SslProtocols
