### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Channels.HttpMessageSettings
  id: HttpMessageSettings
  children:
  - System.ServiceModel.Channels.HttpMessageSettings.#ctor
  - System.ServiceModel.Channels.HttpMessageSettings.Equals(System.ServiceModel.Channels.HttpMessageSettings)
  - System.ServiceModel.Channels.HttpMessageSettings.HttpMessagesSupported
  langs:
  - csharp
  name: HttpMessageSettings
  nameWithType: HttpMessageSettings
  fullName: System.ServiceModel.Channels.HttpMessageSettings
  type: Class
  summary: A binding parameter that can be used with the HTTP Transport to  specify the setting for HttpMessage support.
  syntax:
    content: 'public sealed class HttpMessageSettings : IEquatable<System.ServiceModel.Channels.HttpMessageSettings>'
  inheritance:
  - System.Object
  implements:
  - System.IEquatable<System.ServiceModel.Channels.HttpMessageSettings>
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.ServiceModel.Channels\HttpMessageSettings.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.ServiceModel.Channels/HttpMessageSettings.xml
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.ServiceModel.Channels.HttpMessageSettings.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Channels.HttpMessageSettings
  langs:
  - csharp
  name: HttpMessageSettings()
  nameWithType: HttpMessageSettings.HttpMessageSettings()
  fullName: System.ServiceModel.Channels.HttpMessageSettings.HttpMessageSettings()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Channels.HttpMessageSettings"></xref> class.
  syntax:
    content: public HttpMessageSettings ();
    parameters: []
  overload: System.ServiceModel.Channels.HttpMessageSettings.#ctor*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.ServiceModel.Channels\HttpMessageSettings.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.ServiceModel.Channels/HttpMessageSettings.xml
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.ServiceModel.Channels.HttpMessageSettings.Equals(System.ServiceModel.Channels.HttpMessageSettings)
  id: Equals(System.ServiceModel.Channels.HttpMessageSettings)
  parent: System.ServiceModel.Channels.HttpMessageSettings
  langs:
  - csharp
  name: Equals(HttpMessageSettings)
  nameWithType: HttpMessageSettings.Equals(HttpMessageSettings)
  fullName: System.ServiceModel.Channels.HttpMessageSettings.Equals(HttpMessageSettings)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: Determines whether the specified Object is equal to the current Object.
  syntax:
    content: public bool Equals (System.ServiceModel.Channels.HttpMessageSettings other);
    parameters:
    - id: other
      type: System.ServiceModel.Channels.HttpMessageSettings
      description: The object to compare with the current object.
    return:
      type: System.Boolean
      description: '`true` if the specified Object is equal to the current Object; otherwise, `false`.'
  overload: System.ServiceModel.Channels.HttpMessageSettings.Equals*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.ServiceModel.Channels\HttpMessageSettings.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.ServiceModel.Channels/HttpMessageSettings.xml
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
- uid: System.ServiceModel.Channels.HttpMessageSettings.HttpMessagesSupported
  id: HttpMessagesSupported
  parent: System.ServiceModel.Channels.HttpMessageSettings
  langs:
  - csharp
  name: HttpMessagesSupported
  nameWithType: HttpMessageSettings.HttpMessagesSupported
  fullName: System.ServiceModel.Channels.HttpMessageSettings.HttpMessagesSupported
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: Gets or sets a value indicating whether the HTTP transport should support <xref href="System.Net.Http.HttpRequestMessage"></xref> and <xref href="System.Net.Http.HttpResponseMessage"></xref> instances.
  syntax:
    content: public bool HttpMessagesSupported { get; set; }
    return:
      type: System.Boolean
      description: '`true` if the HTTP transport supports <xref href="System.Net.Http.HttpRequestMessage"></xref> and <xref href="System.Net.Http.HttpResponseMessage"></xref> instances; otherwise, `false`.'
  overload: System.ServiceModel.Channels.HttpMessageSettings.HttpMessagesSupported*
  exceptions: []
  original_ecmaxml_local_path: E:\mdoc\ECMA2YamlTestRepo2\fulldocset\xml\System.ServiceModel.Channels\HttpMessageSettings.xml
  content_git_url: https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/masterwithyml/fulldocset/xml/System.ServiceModel.Channels/HttpMessageSettings.xml
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.Channels.HttpMessageSettings.#ctor
  parent: System.ServiceModel.Channels.HttpMessageSettings
  isExternal: false
  name: HttpMessageSettings()
  nameWithType: HttpMessageSettings.HttpMessageSettings()
  fullName: System.ServiceModel.Channels.HttpMessageSettings.HttpMessageSettings()
- uid: System.ServiceModel.Channels.HttpMessageSettings.Equals(System.ServiceModel.Channels.HttpMessageSettings)
  parent: System.ServiceModel.Channels.HttpMessageSettings
  isExternal: false
  name: Equals(HttpMessageSettings)
  nameWithType: HttpMessageSettings.Equals(HttpMessageSettings)
  fullName: System.ServiceModel.Channels.HttpMessageSettings.Equals(HttpMessageSettings)
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Channels.HttpMessageSettings
  parent: System.ServiceModel.Channels
  isExternal: false
  name: HttpMessageSettings
  nameWithType: HttpMessageSettings
  fullName: System.ServiceModel.Channels.HttpMessageSettings
- uid: System.ServiceModel.Channels.HttpMessageSettings.HttpMessagesSupported
  parent: System.ServiceModel.Channels.HttpMessageSettings
  isExternal: false
  name: HttpMessagesSupported
  nameWithType: HttpMessageSettings.HttpMessagesSupported
  fullName: System.ServiceModel.Channels.HttpMessageSettings.HttpMessagesSupported
- uid: System.ServiceModel.Channels.HttpMessageSettings.#ctor*
  parent: System.ServiceModel.Channels.HttpMessageSettings
  isExternal: false
  name: HttpMessageSettings
  nameWithType: HttpMessageSettings.HttpMessageSettings
- uid: System.ServiceModel.Channels.HttpMessageSettings.Equals*
  parent: System.ServiceModel.Channels.HttpMessageSettings
  isExternal: false
  name: Equals
  nameWithType: HttpMessageSettings.Equals
- uid: System.ServiceModel.Channels.HttpMessageSettings.HttpMessagesSupported*
  parent: System.ServiceModel.Channels.HttpMessageSettings
  isExternal: false
  name: HttpMessagesSupported
  nameWithType: HttpMessageSettings.HttpMessagesSupported
